<style>
    .errorAjax{
        background-color: #e8a4a4;
        border: 2px solid #e06767;
        height: auto;
        font-family: arial;
        font-size: 9pt;
        padding: 5px;
        margin: 0px;
    }
    .tabela th{
        text-align: left;
    }
    .descEmpresa{
        display: none;
    }
    .descEmpresa label{
        cursor: default;
    }
    #msgAjaxPJ{
        display: none;
        color: red;
        cursor: default;
    }
    #msgAjaxPF{
        display: none;
        color: red;
        cursor: default;
    }
</style>
<div id="conteudo">
    <div id="iframe" style="display:none; margin-bottom: -10px;">
        <iframe name="_frameForm" id="_frameForm" style="border: 0px #fff solid; width: 100%; height: 110px;" ></iframe>
    </div>
    <form id="cadastroBeneficiaria" target="_frameForm" action="<?php echo $this->url(array('module' => 'beneficiaria', 'controller' => 'cadastro', 'action' => 'cadastrar')); ?>" method="post">
        <input type="hidden" name="IDPJ" id="IDPJ" value="0" />
        <input type="hidden" name="IDPF" id="IDPF" value="0" />
        <input type="hidden" name="ID_ENDERECO" id="ID_ENDERECO" value="0" />
        <table align="center" border="0" class="tabela" width="95%" background="<?php echo $this->baseUrl('img/benificiario.png') ?>">
            <tr>
                <td colspan="3" style="text-align: center;">
                    <p style="font-size: 16px;">
                        Este cadastro é específico para empresas interessadas em oferecer o Vale-Cultura aos seus funcionários.
                    </p>
                    <p style="font-size: 16px; color: red;">
                        Trabalhador, se deseja receber o Vale-Cultura
                        <a
                            style="color: #000; font-weight: bold;"
                            href="http://www.cultura.gov.br/por-dentro-do-vale-cultura1/-/asset_publisher/ElnqtJzm0xST/content/para-o-trabalhador/10895?redirect=http%3A%2F%2Fwww.cultura.gov.br%2Fpor-dentro-do-vale-cultura1%3Fp_p_id%3D101_INSTANCE_ElnqtJzm0xST%26p_p_lifecycle%3D0%26p_p_state%3Dnormal%26p_p_mode%3Dview%26p_p_col_id%3Dcolumn-2%26p_p_col_pos%3D1%26p_p_col_count%3D2"
                            >
                            clique aqui
                        </a> e saiba como.
                    </p>
                </td>
            </tr>
            <tr>
                <td colspan="3" style="text-align: center;"><h3 class="footer-headline"><span>Dados da Empresa Benefici&aacute;ria</span></h3></td>
            </tr>
            <tr>
                <th valign="top" class="destacar bold top-left" colspan="3">CNPJ: </th>
            </tr>
            <tr>
                <td valign="top" width="33%"><input name="EMPRESA_CNPJ" id="EMPRESA_CNPJ" type="text" class="input_simples w200 cnpj" /></td>
                <td valign="top" colspan="2">
                    <img src="<?php echo $this->baseUrl('img/ajax-loader_4.gif');?>" id="imgPJ"  style="display: none;" />
                    <label id="msgAjaxPJ"></label>
                </td>
            </tr>
            <tr class="descEmpresa">
                <th valign="top">Raz&atilde;o Social: </th>
                <th valign="top">Nome Fantasia: </th>
                <th valign="top">Natureza Juridica: </th>
            </tr>
            <tr class="descEmpresa">
                <td valign="top"><label id="EMPRESA_RAZAOSOCIAL">&nbsp;</label></td>
                <td valign="top"><label id="EMPRESA_NOMEFANTASIA">&nbsp;</label></td>
                <td valign="top"><label id="NATUREZA_JURIDICA">&nbsp;</label></td>
            </tr>
            <tr class="descEmpresa">
                <th valign="top">Atividade Econ&ocirc;mica Principal: </th>
                <th valign="top" colspan="2">Atividades Econ&ocirc;micas Secund&aacute;rias: </th>
            </tr>
            <tr class="descEmpresa">
                <td valign="top"><label id="CNAE_PRIMARIO">&nbsp;</label></td>
                <td valign="top" colspan="2"><label id="CNAE_SECUNDARIOS">&nbsp;</label></td>
            </tr>
            <tr class="descEmpresa">
                <th class="destacar bold">Regime de tributa&ccedil;&atilde;o</th>
                <th class="destacar bold" colspan="2">Operadora</th>
            </tr>
            <tr class="descEmpresa">
                <td>
                    <select name="EMPRESA_TIPO_LUCRO" id="EMPRESA_TIPO_LUCRO" class="select_simples w200">
                        <option value=""> - Selecione - </option>
                        <?php foreach ($this->tipoLucro as $lucro) { ?>
                            <option value="<?php echo $lucro['ID_TIPO_LUCRO'] ?>"> <?php echo $lucro['DS_TIPO_LUCRO'] ?> </option>
                        <?php } ?>
                    </select>
                </td>
                <td colspan="2">
                    <select name="EMPRESA_OPERADORA" id="EMPRESA_OPERADORA" class="select_simples">
                        <option value=""> - Selecione - </option>
                        <?php foreach ($this->operadorasAtivas as $operadora) { ?>
                            <option value="<?php echo $operadora['idOperadora'] ?>"> <?php echo $operadora['nmFantasia'] ?> </option>
                        <?php } ?>
                    </select>
                </td>
            </tr>
        </table>

        <table align="center" border="0" class="tabela" width="95%" background="<?php echo $this->baseUrl('img/benificiario.png') ?>">
            <tr>
                <td colspan="3" style="text-align: center;"><h3 class="footer-headline">Endere&ccedil;o comercial</h3></td>
            </tr>
            <tr>
                <th valign="top" class="destacar bold">CEP:</th>
                <td valign="top" colspan="2"><img src="<?php echo $this->baseUrl('img/ajax-loader_4.gif');?>" id="imgPJ"  style="display: none;" /></td>
            </tr>
            <tr>
                <td valign="top">
                    <input name="EMPRESA_CEP" id="EMPRESA_CEP" valor="" onchange="buscaCep(this)" type="text" class="input_simples w500 block cep" />
                    <label for="EMPRESA_CEP" id="EMPRESA_CEP_VALIDADOR" class="error" style="display: none"></label>
                </td>
                <td align="left" colspan="2">
                    <a href="http://www.buscacep.correios.com.br/" target="_blank" class="btn">Busca CEP</a>
                </td>
            </tr>
            <tr>
                <th valign="top" class="destacar bold">Estado:</th>
                <th valign="top" class="destacar bold">Munic&iacute;pio:</th>
                <th valign="top" class="destacar bold">Bairro:</th>
            </tr>
            <tr>
                <td valign="top">
                    <select name="EMPRESA_UF" id="EMPRESA_UF" disabled="true" class="select_simples w200 block">
                        <option> - Informe o CEP - </option>
                    </select>
                </td>
                <td valign="top">
                    <select name="EMPRESA_MUNICIPIO" id="EMPRESA_MUNICIPIO" disabled="true" class="select_simples w200 block">
                        <option> - Informe o CEP - </option>
                    </select>
                </td>
                <td valign="top">
                    <select name="EMPRESA_BAIRRO" id="EMPRESA_BAIRRO" disabled="true" class="select_simples w200 block">
                        <option> - Informe o CEP - </option>
                    </select>
                </td>
            </tr>
            <tr>
                <th valign="top" class="destacar bold">Endere&ccedil;o:</th>
                <th valign="top" class="destacar bold">Complemento:</th>
                <th valign="top" class="destacar bold">Numero:</th>
            </tr>
            <tr>
                <td valign="top">
                    <input name="EMPRESA_ENDERECO" id="EMPRESA_ENDERECO" disabled="true" value="- Informe o CEP -" type="text" class="input_simples w200 block" />
                </td>
                <td valign="top"><input name="EMPRESA_COMPLEMENTO" id="EMPRESA_COMPLEMENTO" type="text" class="input_simples w200 block" /></td>
                <td valign="top"><input name="EMPRESA_NUMERO" id="EMPRESA_NUMERO" maxlength="10" type="text" class="input_simples w100 block" /></td>
            </tr>
        </table>

        <table width="95%" align="center" class="tabela">
            <tr>
                <td colspan="2" style="text-align: center;"><h3 class="footer-headline"><span>Faixas Salariais</span></h3></td>
            </tr>
            <tr>
                <td colspan="2" class="destacar bold">Informe abaixo o n&uacute;mero de funcion&aacute;rios de acordo com a faixa salarial</td>
            </tr>


            <?php
            foreach ($this->faixasSalarial as $faixaSalarial) {
                ?>
                <tr>
                    <td><?php echo $faixaSalarial['DS_TIPO_FAIXA_SALARIAL'] ?></td>
                    <td><input type="text" onkeyup="num(this);" maxlength="8" class="nrFuncionarios input_simples numerico" name="IDFAIXASALARIAL[<?php echo $faixaSalarial['ID_TIPO_FAIXA_SALARIAL'] ?>]" /></td>
                </tr>
                <?php
            }
            ?>


            <tr>
                <td>Total de funcion&aacute;rios:</td>
                <td><input type="text" id="totalFuncionarios" disabled="true" class="input_simples" /></td>
            </tr>
        </table>

        <table width="95%" align="center" class="tabela">
            <tr>
                <th colspan="3" style="text-align: center;"><h3 class="footer-headline"><span>RESPONSÁVEL PELA GESTÃO DO PROGRAMA JUNTO AO MINC</span></h3></th>
            </tr>
            <tr>
                <td colspan="3">
                    <div id="msgAjax" class="errorAjax" style="display:none;"></div>
                </td>
            </tr>
            <tr>
                <td colspan="3" class="destacar bold">Informe abaixo os dados da pessoa responsável pela inserção das informações da empresa junto ao Ministério da Cultura.</td>
            </tr>
            <tr>
                <td valign="top" class="w100">CPF: <img src="<?php echo $this->baseUrl('img/ajax-loader_4.gif');?>" id="imgPF" style="display: none;" /></td>
                <td valign="top">Nome:</td>
                <td valign="top" class="destacar bold">Cargo:</td>
            </tr>
            <tr>
                <td valign="top"><input name="RESPONSAVEL_CPF" id="RESPONSAVEL_CPF" type="text" class="input_simples cpf" /></td>
                <td valign="top"><input disabled="true" name="RESPONSAVEL_NOME" id="RESPONSAVEL_NOME" type="text" class="input_simples" /></td>
                <td valign="top">
                    <select name="RESPONSAVEL_CARGO" id="RESPONSAVEL_CARGO">
                        <option> - SELECIONE - </option>
                        <?php
                        foreach ($this->CBOs as $CBO) {
                            ?>
                            <option value="<?php echo $CBO['CD_CBO'] ?>">
                                <?php echo $CBO['NM_CBO'] ?>
                            </option>
                            <?php
                        }
                        ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td valign="top" class="destacar bold">E-mail:</td>
                <td valign="top" class="destacar bold">Fone:</td>
                <td valign="top" class="destacar bold" colspan="2">Fax:</td>
            </tr>
            <tr>
                <td><input name="RESPONSAVEL_EMAIL" id="RESPONSAVEL_EMAIL" type="text" class="input_simples w300" /></td>
                <td valign="top"><input name="RESPONSAVEL_FONE" id="RESPONSAVEL_FONE" type="text" class="input_simples w100 telefone" /></td>
                <td valign="top"><input name="RESPONSAVEL_FAX" id="RESPONSAVEL_FAX" type="text" class="input_simples w100 telefone"  colspan="2" /></td>
            </tr>
            <tr>
                <td valign="top" class="destacar bold">Confirme o E-mail:</td>
                <td colspan="2"></td>
            </tr>
            <tr>
                <td><input name="RESPONSAVEL_EMAIL_COMFIRMA" id="RESPONSAVEL_EMAIL_COMFIRMA" type="text" class="input_simples w300" /></td>
                <td colspan="2"></td>
            </tr>
            <tr>
                <td colspan="3" valign="top">
                    <input type="checkbox" name="AUTORIZO_MINC" id="AUTORIZO_MINC" checked="checked"/>
                    Autorizo o MinC a divulgar que sou empresa beneficiária cadastrada junto ao Programa de Cultura do Trabalhador.
                </td>
            </tr>
            <tr>
                <td colspan="3" valign="top" class="destacar bold">
                    <input type="radio" value="1" name="AUTORIZO_OPERADORA" checked="checked">
                    Autorizo o MinC a divulgar meus dados de contato a operadora selecionada.
                </td>
            </tr>
            <tr>
                <td colspan="3" valign="top" class="destacar bold">
                    <input type="radio" value="2" name="AUTORIZO_OPERADORA">
                    Autorizo o MinC a divulgar meus dados de contato a todas operadoras cadastradas no sistema Vale-Cultura.
                </td>
            </tr>

        </table>

        <table width="95%" align="center" class="tabela">
            <tr>
                <th style="text-align: center;"><h3 class="footer-headline"><span>Veracidade</span></h3></th>
            </tr>
            <tr>
                <td>
                    <input type="checkbox" name="ConfimaLei" id="ConfimaLei" style="float:left" />
                    <div>&nbsp; Confirmo sob pena de lei a veracidade de todas as informa&ccedil;&otilde;es prestadas neste cadastro.</div>
                </td>
            </tr>
            <tr>
                <td>Digite o c&oacute;digo abaixo: <input name="captcha[input]" id="captcha[input]" class="input_simples" type="text"></td>
            </tr>
            <tr>
                <td id="captcha" style="height: 80px">

                </td>
            </tr>
        </table>
        <br />
        <table class="tabela">
            <tr>
                <td class="centro">
                    <button id="btnSalvar"   class="btn btn-large btn btn-inverse" type="submit" style="float:center;" id="enviaForm">Salvar</button>
                    <button id="btnCancelar" class="btn btn-large btn btn-inverse" type="button" style="float:center;" onclick="fechaModal();">Cancelar</button>
                    <button id="btnResetar"  class="btn btn-large btn btn-inverse" type="reset" style="float:center;">Limpar</button>
                </td>
            </tr>
        </table>

        <br clear="all" />

        <table id="btFechar" style="display:none" class="tabela">
            <tr></tr>
        </table>
    </form>

</div>

<div style="position: absolute; width: 80%; margin-top: -50px; z-index:9900; display: none;" id="myModal">
    <div class="alert alert-error">
        <!--button type="button" class="close" onclick="$('#mascara2').fadeOut();" data-dismiss="alert">&times;</button-->
        <strong>ATENÇÃO!</strong> <br><br>
        Prezado Beneficiário,

        Você não está autorizando a liberação do seu contato para nenhuma empresa operadora.
        Isto poderá dificultar o contato da operadora com a sua empresa.
        Favor entrar em contato com a empresa operadora de sua preferência para viabilizar a contratação dos serviços.
        <br><br>
        <button class="btn btn-mini btn-success" onclick="enviarForm()" value="Submit">Confirmar</button>
        <button class="btn btn-mini btn-warning" onclick="$('#myModal').fadeOut(); $('#mascara2').fadeOut();">Cancelar</button>
    </div>
</div>
<div class="mascara" id="mascara2"></div>

<script>

    function num(dom){
        dom.value=dom.value.replace(/\D/g,'');
    }

    var confirmado = false;

    jQuery(document).ready(function() {

        $(".cep").mask("99999-999");
        $(".data").mask("99/99/9999");
        $(".cpf").mask("999.999.999-99");
        $(".cnpj").mask("99.999.999/9999-99");
        $(".telefone").mask("(99) 9999-9999?9");

        gerarCaptcha();
        calculaTotalFuncionarios();

        $('#btnResetar').click(function(){
            $('#IDPJ').val('');
            $('#EMPRESA_RAZAOSOCIAL').html('');
            $('#EMPRESA_NOMEFANTASIA').html('');
            $('#NATUREZA_JURIDICA').html('');
            $('#CNAE_PRIMARIO').html('');
            $('#CNAE_SECUNDARIOS').html('');
            $('#EMPRESA_COMPLEMENTO').val('');
            $('#EMPRESA_NUMERO').val('');
            $('#EMPRESA_CEP').val('');
            $('#EMPRESA_CEP').attr('valor','');
            $('#ID_ENDERECO').val('0');

            $('#EMPRESA_UF').html('<option> - Informe o CEP - </option>');
            $('#EMPRESA_MUNICIPIO').html('<option> - Informe o CEP - </option>');
            $('#EMPRESA_BAIRRO').html('<option> - Informe o CEP - </option>');
            $('#EMPRESA_ENDERECO').html('- Informe o CEP -');

            $('#msgAjaxPJ').html('');
            $('#msgAjaxPJ').show();
            $('#msgAjaxPF').html('');
            $('#msgAjaxPF').show();
        });

        // Vamos buscar os dados do CNPJ Agora!
        $('#EMPRESA_CNPJ').focusout(function(){

            $('#IDPJ').val('');
            $('#EMPRESA_RAZAOSOCIAL').html('');
            $('#EMPRESA_NOMEFANTASIA').html('');
            $('#NATUREZA_JURIDICA').html('');
            $('#CNAE_PRIMARIO').html('');
            $('#CNAE_SECUNDARIOS').html('');
            $('#EMPRESA_COMPLEMENTO').val('');
            $('#EMPRESA_NUMERO').val('');
            $('#EMPRESA_CEP').val('');
            $('#EMPRESA_CEP').attr('valor','');
            $('#ID_ENDERECO').val('0');

//            $('.descEmpresa').hide();
            $('#msgAjaxPJ').html('');
            $('#imgPJ').show();

            bloqueaCadastro();

            var txt = $(this).val();

            if(txt == '__.___.___/____-__'){
                $('#imgPJ').hide();
            }else{

                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->url(array('module' => 'operadora', 'controller' => 'cadastro', 'action' => 'busca-pessoa-juridica')); ?>',
                    data: {EMPRESA_CNPJ: $(this).val(), tipoPJ: 'B'},
                    dataType: 'json',
                    success: function(data) {

                        $('#imgPJ').hide();
                        if(data.error != ''){
                            $('#msgAjaxPJ').html(data.error);
                            $('#msgAjaxPJ').show();
                        }else{
                            // Preenche os dados
                            $('#IDPJ').val(data.dados.idpj);
                            $('#EMPRESA_RAZAOSOCIAL').html(data.dados.razaosocial);
                            if(data.dados.nomefantasia===" "){
                                $('#EMPRESA_NOMEFANTASIA').html('<input name="EMPRESA_NMFANTASIA" id="EMPRESA_NMFANTASIA" type="text" class="input_simples w200 block" />');
                            }else{
                                $('#EMPRESA_NOMEFANTASIA').html(data.dados.nomefantasia);
                            }
                            $('#NATUREZA_JURIDICA').html(data.dados.naturezajuridica);
                            $('#CNAE_PRIMARIO').html(data.dados.CNAEPrimario);
                            $('#CNAE_SECUNDARIOS').html(data.dados.CNAESecundarios);
                            $('#EMPRESA_COMPLEMENTO').val(data.dados.dscomplementoendereco);
                            $('#EMPRESA_NUMERO').val(data.dados.nrcomplemento);
                            if(data.dados.cep != 'N'){
                                $('#EMPRESA_CEP').val(data.dados.cep);
                                $('#EMPRESA_CEP').attr('valor', data.dados.cep);
                                $('#ID_ENDERECO').val(data.dados.idendereco);
                                $.ajax({
                                    type: "POST",
                                    url: '<?php echo $this->url(array('module' => 'operadora', 'controller' => 'cadastro', 'action' => 'buscaenderecoporcep')); ?>',
                                    data: {CEP: data.dados.cep},
                                    dataType: 'json',
                                    success: function(data) {
                                        carregaEndereco(data);
                                    }
                                });
                                $('#EMPRESA_TIPO_LUCRO').focus();
                            }
                            $('.descEmpresa').show();
                            desbloqueaCadastro();
                        }

                    },error: function(data) {
                        $('#msgAjaxPJ').html(data.error);
                        $('#msgAjaxPJ').show();
                        $('#imgPJ').hide();
                    }
                });
            }

        });


        // Vamos buscar os dados do CNPJ Agora!
        $('#RESPONSAVEL_CPF').focusout(function(){

            $('#IDPF').val('');
            $('#RESPONSAVEL_NOME').val('');
            $('#msgAjax').hide();
            $('#imgPF').show();

            var txt = $(this).val();

            if(txt == '___.___.___-__'){
                $('#imgPF').hide();
            }else{

                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->url(array('module' => 'operadora', 'controller' => 'cadastro', 'action' => 'busca-pessoa-fisica')); ?>',
                    data: {RESPONSAVEL_CPF: $(this).val(), TIPO_VINCULO: 'B'},
                    dataType: 'json',
                    success: function(data) {

                        if(data.error != ''){
                            $('#msgAjax').html(data.error);
                            $('#msgAjax').show();
                            $('#imgPF').hide();
                        }else{
                            // Preenche os dados
                            $('#IDPF').val(data.dados.idpf);
                            $('#RESPONSAVEL_NOME').val(data.dados.nome);
                            $('#RESPONSAVEL_CARGO').focus();
                            $('#imgPF').hide();
                        }

                    },error: function(data) {
                        $('#msgAjax').html(data.error);
                        $('#msgAjax').show();
                        $('#imgPF').hide();
                    }
                });
            }

        });


        $('.nrFuncionarios').change(function() {
            calculaTotalFuncionarios();
        });

        $(".numerico").keyup(function() {
            if (isNaN($(this).val())) {
                $(this).val(0);
            }
        });

        $('.telefone').focusout(function() {
            var phone, element;
            element = $(this);
            element.unmask();
            phone = element.val().replace(/\D/g, '');
            if (phone.length > 10) {
                element.mask("(99) 99999-999?9");
            } else {
                element.mask("(99) 9999-9999?9");
            }
        }).trigger('focusout');


        $("#cadastroBeneficiaria").validate({
            rules: {
                EMPRESA_CNPJ: {
                    required: true
                },
                EMPRESA_CEP: {
                    required: true
                },
                RESPONSAVEL_EMAIL: {
                    required: true, email: true
                },
                RESPONSAVEL_EMAIL_COMFIRMA: 'emailcheck',
                RESPONSAVEL_CPF: {
                    required: true
                },
                captchaForm: {
                    required: true
                },
                RESPONSAVEL_FONE: {
                    required: true
                },
                EMPRESA_TIPO_LUCRO: {
                    minlength: 1
                },
                EMPRESA_OPERADORA: {
                    minlength: 1
                }
            },
            messages: {
                EMPRESA_CNPJ: {
                    required: "Informe o CNPJ"
                },
                EMPRESA_CEP: {
                    required: "Informe o CEP"
                },
                RESPONSAVEL_EMAIL: {
                    required: "Informe o E-mail do respons&aacute;vel",
                    email: "Digite um e-mail v&aacute;lido"
                },
                RESPONSAVEL_CPF: {
                    required: "Informe o CPF"
                },
                captchaForm: {
                    required: "Campo obrigat&oacute;rio"
                },
                RESPONSAVEL_FONE: {
                    required: "Campo obrigat&oacute;rio"
                },
                EMPRESA_TIPO_LUCRO: {
                    minlength: "Campo obrigat&oacute;rio"
                },
                EMPRESA_OPERADORA: {
                    minlength: "Campo obrigat&oacute;rio"
                }
            },
            submitHandler: function(form) {

               // if (!($('#AUTORIZO_OPERADORA_SELECIONADA').is(":checked") || $('#AUTORIZO_TODAS_OPERADORAS').is(":checked")) && !confirmado) {
               //     $('#mascara2').fadeIn();
               //     $('#myModal').slideDown();
               // } else {
                    form.submit();
               // }
            }
        });
        var left = ($('.window').width() / 2) - ($('#myModal').width() / 2);
        var top = ($('.window').height() / 2) - ($('#myModal').height() / 2);
        if (top < 0) {
            top = 10;
        }

        $('#myModal').css({'top': top, 'left': left});
        $('#mascara2').css({'width': $('.window').width() + 10, 'height': $('.window').height() + 10});

        $('#AUTORIZO_TODAS_OPERADORAS').change(function(){
            if($(this).is(":checked")){
                $('#AUTORIZO_OPERADORA_SELECIONADA').attr("checked",true);
                $('#AUTORIZO_OPERADORA_SELECIONADA').attr("disabled", true);
            }else{
                $('#AUTORIZO_OPERADORA_SELECIONADA').removeAttr("checked");
                $('#AUTORIZO_OPERADORA_SELECIONADA').removeAttr("disabled");
            }
        });


    });

    jQuery.validator.addMethod('emailcheck', function(value, element) {
        if ($('#RESPONSAVEL_EMAIL_COMFIRMA').val() != $('#RESPONSAVEL_EMAIL').val()) {
            return false;
        }
        return true;
    }, 'Verifique o E-mail');

    function fechaForm() {
        $("#cadastroBeneficiaria").fadeOut();
        $("#btFechar").show();
    }

    function exibeRetorno(top) {
        $('#myModal').fadeOut();
        $('#mascara2').fadeOut();

        if (top > 150) {
            top = 150;
        }

        if (top < 80) {
            top = 80;
        }

        top = top + 30;
        $('#_frameForm').css('height', top + 'px');
        $('#iframe').css('display', 'block');
        $('#janelaLoad').animate({scrollTop: 0}, 'slow');
        $('html body').animate({scrollTop: 0}, 'slow');
        gerarCaptcha();
    }

    function buscaCep(obj) {

        valor       = $(obj).attr('valor');
        valorAtual  = $(obj).val().replace("-", "");

        if((valor != '') && valor == valorAtual){
            return false;
        }

        $('#EMPRESA_COMPLEMENTO').val('');
        $('#EMPRESA_NUMERO').val('');
        $.ajax({
            type: "POST",
            url: '<?php echo $this->url(array('module' => 'operadora', 'controller' => 'cadastro', 'action' => 'buscaenderecoporcep')); ?>',
            data: {CEP: $(obj).val()},
            dataType: 'json',
            success: function(data) {
                carregaEndereco(data);
            }
        });
    }

    function enviarForm() {
        confirmado = true;
        $('#enviaForm').click();
    }

    function gerarCaptcha() {
        $.ajax({
            type: "GET",
            url: '<?php echo $this->url(array('module' => 'operadora', 'controller' => 'cadastro', 'action' => 'gerarcaptcha')); ?>',
            success: function(data) {
                $('#captcha').html(data);
                setTimeout('gerarCaptcha()', 600000);
            }
        });
    }

    function carregaEndereco(data) {
        if (!data.error) {
            $('#EMPRESA_CEP_VALIDADOR').fadeOut();
            if (data.dados.TP_CEP != 0) {
                if (data.dados.NM_LOGRADOURO.length > 0) {
                    $('#EMPRESA_ENDERECO').val(data.dados.DS_TIPO_LOGRADOURO+' '+data.dados.NM_LOGRADOURO);
                    if(data.dados.DS_TIPO_LOGRADOURO !== 'M' && data.dados.DS_TIPO_LOGRADOURO !== 'D' && data.dados.DSTIPOLOGRADOURO !== 'P'){
                        $('#EMPRESA_ENDERECO').attr('disabled', 'true');
                    }else{
                        $('#EMPRESA_ENDERECO').val('');
                        $('#EMPRESA_ENDERECO').removeAttr('disabled');
                    }
                }
                if (data.dados.DS_COMPLEMENTO.length > 2) {
                    $('#EMPRESA_COMPLEMENTO').val(data.dados.DS_COMPLEMENTO);
                    $('#EMPRESA_COMPLEMENTO').attr('disabled', 'true');
                }

                $('#EMPRESA_BAIRRO').html('');

                for (var i = 0; i < data.dados.bairros.length; i++)
                {
                    var complemento = '';
                    if (i == 0) {
                        complemento = 'selected';
                    }
                    var option = "<option value='" + data.dados.bairros[i].ID_BAIRRO + "' " + complemento + ">" + data.dados.bairros[i].NM_BAIRRO + "</option>";
                    $('#EMPRESA_BAIRRO').append(option);
                }
                if (data.dados.bairros.length > 1) {
                    $('#EMPRESA_BAIRRO').removeAttr('disabled');
                } else {
                    $('#EMPRESA_BAIRRO').attr('disabled', 'true');
                }

                $('#EMPRESA_UF').html('');
                var option = "<option value='" + data.dados.SG_UF + "' selected >" + data.dados.NM_UF + "</option>";
                $('#EMPRESA_UF').append(option);
                $('#EMPRESA_UF').attr('disabled', 'true');

                $('#EMPRESA_MUNICIPIO').html('');
                var option = "<option value='" + data.dados.ID_MUNICIPIO + "' selected >" + data.dados.NM_MUNICIPIO + "</option>";
                $('#EMPRESA_MUNICIPIO').append(option);
                $('#EMPRESA_MUNICIPIO').attr('disabled', 'true');

            } else {
                //libera campos para preenchimento
                $('#EMPRESA_BAIRRO').removeAttr('disabled');
                $('#EMPRESA_ENDERECO').removeAttr('disabled');
            }
        } else {
            //CEP INVALIDO
            $('#EMPRESA_CEP_VALIDADOR').html('CEP inv&aacute;lido');
            $('#EMPRESA_CEP_VALIDADOR').fadeIn();

            var option = "<option> - Informe o CEP - </option>";
            $('#EMPRESA_BAIRRO').html(option);
            $('#EMPRESA_UF').html(option);
            $('#EMPRESA_MUNICIPIO').html(option);

            $('#EMPRESA_ENDERECO').val('');
            $('#EMPRESA_COMPLEMENTO').val('');
        }
    }

    function calculaTotalFuncionarios() {

        var totalFuncionaios;
        totalFuncionaios = 0;
        $("#cadastroBeneficiaria").find('.nrFuncionarios').each(function() {
            if (eval($(this).val()) > 0) {
                totalFuncionaios = eval(totalFuncionaios) + eval($(this).val());
            }
        });

        $('#totalFuncionarios').val(totalFuncionaios);
    }

    function buscaCNAE(obj) {
        $.ajax({
            type: "POST",
            url: '<?php echo $this->url(array('module' => 'beneficiaria', 'controller' => 'cadastro', 'action' => 'recupera-segundo-nivel-cnae')); ?>',
            data: {IDCNAE: $(obj).val()},
            dataType: 'json',
            success: function(data) {
                carregaCnaeSecundario(data['CNAEs']);
            }
        });
    }

    function carregaCnaeSecundario(Cnae) {
        var CnaeSecundario;
        CnaeSecundario = '';
        for (var i in Cnae) {
            if (i < Cnae.length) {
                CnaeSecundario += '<input name="IDCNAESECUNDARIO[]" type="checkbox" value="' + Cnae[i]['ID_CNAE'] + '"> ' + Cnae[i]['DS_CNAE'] + '<br>';
            }
        }
        $('#CNAE_Secundario').html(CnaeSecundario);
    }

    function print_r(arr, text, tab) {
        var text = (text ? text : "Array \n("), tab = (tab ? tab : "\t");

        for (key in arr) {
            if (typeof arr[key] == "object")
                text = print_r(arr[key], text + "\n" + tab + "[" + key + "] => Array \n" + tab + "(", "\t" + tab);
            else
                text += "\n" + tab + "[" + key + "] => " + arr[key];

            text += "\n" + (tab.substr(0, tab.length - 1)) + ")\n";
        }
        return text;

    }


    function bloqueaCadastro(){
        // Dados da empresa
        $('#EMPRESA_TIPO_LUCRO').attr('disabled', true);
        $('#EMPRESA_OPERADORA').attr('disabled', true);
        $('#EMPRESA_CEP').attr('disabled', true);
        $('#EMPRESA_COMPLEMENTO').attr('disabled', true);
        $('#EMPRESA_NUMERO').attr('disabled', true);
        // Quantidades de funcionarios
        $('.nrFuncionarios').attr('disabled', true);
        // Dados do Responsavel
        $('#RESPONSAVEL_CPF').attr('disabled', true);
        $('#RESPONSAVEL_CARGO').attr('disabled', true);
        $('#RESPONSAVEL_EMAIL').attr('disabled', true);
        $('#RESPONSAVEL_FONE').attr('disabled', true);
        $('#RESPONSAVEL_FAX').attr('disabled', true);
        $('#RESPONSAVEL_EMAIL_COMFIRMA').attr('disabled', true);
        // Botão de Salvar
        $('#btnSalvar').hide();
    }

    function desbloqueaCadastro(){
        // Dados da empresa
        $('#EMPRESA_TIPO_LUCRO').attr('disabled', false);
        $('#EMPRESA_OPERADORA').attr('disabled', false);
        $('#EMPRESA_CEP').attr('disabled', false);
        $('#EMPRESA_COMPLEMENTO').attr('disabled', false);
        $('#EMPRESA_NUMERO').attr('disabled', false);
        // Quantidades de funcionarios
        $('.nrFuncionarios').attr('disabled', false);
        // Dados do Responsavel
        $('#RESPONSAVEL_CPF').attr('disabled', false);
        $('#RESPONSAVEL_CARGO').attr('disabled', false);
        $('#RESPONSAVEL_EMAIL').attr('disabled', false);
        $('#RESPONSAVEL_FONE').attr('disabled', false);
        $('#RESPONSAVEL_FAX').attr('disabled', false);
        $('#RESPONSAVEL_EMAIL_COMFIRMA').attr('disabled', false);
        // Botão de Salvar
        $('#btnSalvar').show();
    }

</script>