<link href="<?php echo $this->baseUrl('js/circle/component.css') ?>" rel="stylesheet"/>
<style type="text/css">
    .errorAjax {
        background-color: #e8a4a4;
        border: 2px solid #e06767;
        height: auto;
        font-family: arial;
        font-size: 9pt;
        padding: 5px;
        margin: 0px;
    }

    .tabela th {
        text-align: left;
    }

    .descEmpresa {
        display: none;
    }

    .descEmpresa label {
        cursor: default;
    }

    #msgAjaxPJ {
        display: none;
        color: red;
        cursor: default;
    }

    #msgAjaxPF, #msgAjaxPFEmpresa, #msgAjaxPFNaoEmpresa {
        display: none;
        color: red;
        cursor: default;
    }

    #divOperadoras {
        height: 160px;
        margin-top: 10px;
        border: 1px solid #000000;
        z-index: 9999999;
    }

    #divOperadorasUl {
        height: 120px;
        overflow-y: auto;
        z-index: 99999999;
    }

    #divOperadoras h4 {
        text-align: left;
        border-bottom: 1px solid #000000;
        background-color: #d0d0d0;
        margin: 0;
        padding: 5px;
    }

    #divOperadorasUl ul {
        margin: 10px 0 10px 25px;
    }

    #divOperadorasUl li {
        list-style: none;
    }

    #divOperadorasUl li label.error {
        float: right;
    }

    #divOperadorasUl li input {
        z-index: 1;
    }

    .action-pass {
        width: 95%;
        margin: 0;
        padding: 0;
        position: absolute;
        top: 500px;
    }
</style>

<div id="conteudo" class="" style="">
    <div id="iframe" style="display:none; margin-bottom: -10px;">
        <iframe name="_frameForm" id="_frameForm" style="border: 0px #fff solid; width: 100%; height: 110px;"></iframe>
    </div>
    <form id="cadastroBeneficiaria" target="_frameForm"
          action="<?php echo $this->url(array('module' => 'beneficiaria', 'controller' => 'cadastro', 'action' => 'cadastrar')); ?>"
          method="post">
        <input type="hidden" name="IDPJ" id="IDPJ" value="0"/>
        <input type="hidden" name="IDPF" id="IDPF" value="0"/>
        <input type="hidden" name="ID_EMPRESA_PF" id="ID_EMPRESA_PF" value="0"/>
        <input type="hidden" name="ID_NAO_EMPRESA_PF" id="ID_NAO_EMPRESA_PF" value="0"/>
        <input type="hidden" name="ID_ENDERECO" id="ID_ENDERECO" value="0"/>
        <table align="center" border="0" class="tabela" width="95%"
               background="<?php echo $this->baseUrl('img/benificiario.png') ?>">
            <tr>
                <td colspan="3" style="text-align: center;">
                    <p style="font-size: 16px;">
                        Este cadastro é específico para empresas interessadas em oferecer o Vale-Cultura aos seus
                        funcionários.
                    </p>
                    <p style="font-size: 16px; color: red;">
                        Trabalhador/a, se deseja receber o Vale-Cultura
                        <a style="color: #000; font-weight: bold;" target="_blank"
                           href="<?php echo $this->linkTrabalhador; ?>">
                            clique aqui
                        </a> e saiba como.
                    </p>
                </td>
            </tr>
            <tr>
                <td colspan="3" style="text-align: center;">
                    <h3 class="footer-headline">
                        <span>
                            Dados da Empresa Benefici&aacute;ria
                        </span>
                    </h3>
                </td>
            </tr>
            <tr>
                <th valign="top" class="destacar bold top-left" colspan="3">
                    CNPJ:
                    <a href="#myModalSobreBeneficiaria" role="" class="nextPassB"
                       data-val="passo1B" data-toggle="modal">
                        <img src="<?php echo $this->baseUrl('img/help-icon.png'); ?>"
                             style="width: 25px; height: 25px; cursor: pointer; margin-top: 0;border: 0; padding: 0;"
                             title="Sobre os Deveres da Beneficiária"/></a>
                </th>
            </tr>
            <tr>
                <td valign="top" width="33%"><input name="EMPRESA_CNPJ" id="EMPRESA_CNPJ" type="text"
                                                    class="input_simples w200 cnpj"/></td>
                <td valign="top" colspan="2">
                    <img src="<?php echo $this->baseUrl('img/ajax-loader_4.gif'); ?>" id="imgPJ"
                         style="display: none;"/>
                    <label id="msgAjaxPJ"></label>
                </td>
            </tr>
            <tr class="descEmpresa">
                <th valign="top" width="33%">Raz&atilde;o Social:</th>
                <th valign="top" width="34%">Nome Fantasia:</th>
                <th valign="top" width="33%">Natureza Juridica:</th>
            </tr>
            <tr class="descEmpresa">
                <td valign="top"><label id="EMPRESA_RAZAOSOCIAL">&nbsp;</label></td>
                <td valign="top"><label id="EMPRESA_NOMEFANTASIA">&nbsp;</label></td>
                <td valign="top"><label id="NATUREZA_JURIDICA">&nbsp;</label></td>
            </tr>
            <tr class="descEmpresa">
                <th valign="top">Atividade Econ&ocirc;mica Principal:</th>
                <th valign="top">Atividades Econ&ocirc;micas Secund&aacute;rias:</th>
                <th valign="top">Situação:</th>
            </tr>
            <tr class="descEmpresa">
                <td valign="top"><label id="CNAE_PRIMARIO">&nbsp;</label></td>
                <td valign="top"><label id="CNAE_SECUNDARIOS">&nbsp;</label></td>
                <td valign="top"><label id="EMPRESA_SITUACAO">&nbsp;</label></td>
            </tr>
            <tr class="descEmpresa">
                <th class="destacar bold" colspan="3">Regime de tributa&ccedil;&atilde;o</th>
            </tr>
            <tr class="descEmpresa">
                <td colspan="3">
                    <select name="EMPRESA_TIPO_LUCRO" id="EMPRESA_TIPO_LUCRO" class="select_simples w200">
                        <option value=""> - Selecione -</option>
                        <?php foreach ($this->tipoLucro as $lucro) { ?>
                            <option value="<?php echo $lucro['ID_TIPO_LUCRO'] ?>"> <?php echo $lucro['DS_TIPO_LUCRO'] ?> </option>
                        <?php } ?>
                    </select>
                </td>
            </tr>
        </table>

        <table align="center" border="0" class="tabela" width="95%"
               background="<?php echo $this->baseUrl('img/benificiario.png') ?>">
            <tr>
                <td colspan="3" style="text-align: center;"><h3 class="footer-headline">Endere&ccedil;o comercial</h3>
                </td>
            </tr>
            <tr>
                <th valign="top" class="destacar bold">CEP:</th>
                <td valign="top" colspan="2"><img src="<?php echo $this->baseUrl('img/ajax-loader_4.gif'); ?>"
                                                  id="imgPJ" style="display: none;"/></td>
            </tr>
            <tr>
                <td valign="top">
                    <input name="EMPRESA_CEP" id="EMPRESA_CEP" valor="" onchange="buscaCep(this)" type="text"
                           class="input_simples w500 block cep"/>
                    <label for="EMPRESA_CEP" id="EMPRESA_CEP_VALIDADOR" class="error" style="display: none"></label>
                </td>
                <td align="left" colspan="2">
                    <a href="http://www.buscacep.correios.com.br/" target="_blank" class="btn">Busca CEP</a>
                </td>
            </tr>
            <tr>
                <th valign="top" class="destacar bold">Estado:</th>
                <th valign="top" class="destacar bold">Munic&iacute;pio:</th>
                <th valign="top" class="destacar bold">Bairro:</th>
            </tr>
            <tr>
                <td valign="top">
                    <select name="EMPRESA_UF" id="EMPRESA_UF" disabled="true" class="select_simples w200 block">
                        <option> - Informe o CEP -</option>
                    </select>
                </td>
                <td valign="top">
                    <select name="EMPRESA_MUNICIPIO" id="EMPRESA_MUNICIPIO" disabled="true"
                            class="select_simples w200 block">
                        <option> - Informe o CEP -</option>
                    </select>
                </td>
                <td valign="top">
                    <select name="EMPRESA_BAIRRO" id="EMPRESA_BAIRRO" disabled="true" class="select_simples w200 block">
                        <option> - Informe o CEP -</option>
                    </select>
                </td>
            </tr>
            <tr>
                <th valign="top" class="destacar bold">Endere&ccedil;o:</th>
                <th valign="top" class="destacar bold">Complemento:</th>
                <th valign="top" class="destacar bold">Numero:</th>
            </tr>
            <tr>
                <td valign="top">
                    <input name="EMPRESA_ENDERECO" id="EMPRESA_ENDERECO" disabled="true" value="- Informe o CEP -"
                           type="text" class="input_simples w200 block"/>
                </td>
                <td valign="top"><input name="EMPRESA_COMPLEMENTO" id="EMPRESA_COMPLEMENTO" type="text"
                                        class="input_simples w200 block" maxlength="100"/></td>
                <td valign="top"><input name="EMPRESA_NUMERO" id="EMPRESA_NUMERO" maxlength="10" type="text"
                                        class="input_simples w100 block"/></td>
            </tr>
        </table>

        <table width="95%" align="center" class="tabela">
            <tr>
                <td colspan="2" style="text-align: center;"><h3 class="footer-headline"><span>Faixas Salariais</span>
                    </h3></td>
            </tr>

            <tr>
                <td colspan="2" class="destacar bold">
                    <b>Informe abaixo o n&uacute;mero de funcion&aacute;rios de acordo com a faixa salarial:</b>
                    <a href="#myModalSobreFaixaSalarial"
                       role="button"
                       class="" data-toggle="modal">
                        <img src="<?php echo $this->baseUrl('img/help-icon.png'); ?>"
                             style="width: 25px; height: 25px; cursor: pointer; margin-top: 0;border: 0; padding: 0;"
                             title="Sobre a Faixa Salarial"/></a>
                    <br/>
                </td>
            </tr>

            <?php
            foreach ($this->faixasSalarial as $faixaSalarial) {
                ?>
                <tr>
                    <td><?php echo $faixaSalarial['DS_TIPO_FAIXA_SALARIAL'] ?></td>
                    <td><input type="text" onkeyup="num(this);" maxlength="8"
                               class="nrFuncionarios input_simples numerico"
                               name="IDFAIXASALARIAL[<?php echo $faixaSalarial['ID_TIPO_FAIXA_SALARIAL'] ?>]"/></td>
                </tr>
                <?php
            }
            ?>

            <tr>
                <td>Total de funcion&aacute;rios:</td>
                <td><input type="text" id="totalFuncionarios" disabled="true" class="input_simples"/></td>
            </tr>

            <tr>
                <td colspan="3" valign="top" class="destacar bold">
                    <input type="radio" value="T" name="AUTORIZAR_VALE_TODOS_FUNCIONARIOS"
                           class="AUTORIZAR_VALE_TODOS_FUNCIONARIOS" checked="checked"/>
                    Você deseja ofertar o Vale-Cultura a todos os funcionários da empresa?
                </td>
            </tr>
            <tr>
                <td colspan="3" valign="top" class="destacar bold">
                    <input type="radio" value="S" name="AUTORIZAR_VALE_TODOS_FUNCIONARIOS"
                           class="AUTORIZAR_VALE_TODOS_FUNCIONARIOS"/>
                    Você deseja, inicialmente, ofertar o Vale-Cultura aos funcionários da empresa que recebem até cinco
                    salários mínimos?
                </td>
            </tr>
        </table>

        <table width="95%" align="center" class="tabela">
            <tr>
                <th style="text-align: center;">
                    <h3 class="footer-headline"><span>ESCOLHA DA OPERADORA</span></h3>
                </th>
            </tr>

            <tr>
                <td valign="top" class="destacar bold">
                    <b>Escolha uma entre as empresas operadoras cadastradas e autorizadas a emitir o cartão Vale-cultura
                        dos seus funcionários.</b>
                    <a href="#myModalSobreListaOperadoras"
                       role="button"
                       class="" data-toggle="modal">
                        <img src="<?php echo $this->baseUrl('img/help-icon.png'); ?>"
                             style="width: 25px; height: 25px; cursor: pointer; margin-top: 0;border: 0; padding: 0;"
                             title="Sobre a Lista de Operadoras"/></a>

                    <div id="divOperadoras">
                        <h4>Nome</h4>
                        <div id="divOperadorasUl">
                            <ul>
                                <?php foreach ($this->operadorasAtivas as $operadora) { ?>
                                    <li>
                                        <input type="radio" name="OPERADORA_VALE" class="OPERADORA_VALE"
                                               value="<?php echo $operadora['idOperadora'] ?>"/>
                                        &nbsp;
                                        <?php echo(!empty(trim($operadora['nmFantasia'])) ? $operadora['nmFantasia'] : $operadora['nmRazaoSocial']); ?>
                                    </li>
                                <?php } ?>
                            </ul>
                        </div>
                    </div>
                </td>
            </tr>
        </table>

        <table width="95%" align="center" class="tabela">
            <tr>
                <th colspan="2" style="text-align: center;">
                    <h3 class="footer-headline">
                        <span>Responsável pela empresa junto ao Programa de Cultura do Trabalhador</span>
                    </h3>
                </th>
            </tr>
            <tr>
                <td colspan="2" class="destacar bold">
                    <b>Informe abaixo os dados do responsável pela empresa junto ao Ministério da Cidadania.</b>
                </td>
            </tr>

            <tr>
                <td colspan="2" class="destacar bold">&nbsp;</td>
            </tr>

            <tr>
                <td colspan="2" class="destacar bold">
                    É o representante legal da empresa?
                    <input type="radio" value="1" name="responsavel_empresa" class="responsavel_empresa"
                           checked="checked"/> Sim
                    <input type="radio" value="0" name="responsavel_empresa" class="responsavel_empresa"/> Não
                </td>
            </tr>
            <tr>
                <td colspan="2" class="destacar bold">&nbsp;</td>
            </tr>

        </table>

        <table id="responsavel-nao-empresa" align="center" border="0" class="tabela hide" width="95%"
               background="<?php echo $this->baseUrl('img/benificiario.png') ?>">
            <tr>
                <td colspan="3"></td>
            </tr>
            <tr>
                <td colspan="3" class="destacar bold">
                    <h4 class="">Dados do responsável pelo preenchimento do formulário</h4>
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    <div id="msgAjaxNaoEmpresa" class="errorAjax" style="display:none;"></div>
                </td>
            </tr>
            <tr>
                <td valign="top" class="w100">CPF: <img src="<?php echo $this->baseUrl('img/ajax-loader_4.gif'); ?>"
                                                        id="imgPFNaoEmpresa" style="display: none;"/></td>
                <td valign="top">Nome:</td>
                <td valign="top" class="destacar bold">Cargo:</td>
            </tr>
            <tr>
                <td valign="top"><input name="RESPONSAVEL_NAO_EMPRESA_CPF" id="RESPONSAVEL_NAO_EMPRESA_CPF" type="text"
                                        class="input_simples cpf"/></td>
                <td valign="top"><input disabled="true" name="RESPONSAVEL_NAO_EMPRESA_NOME"
                                        id="RESPONSAVEL_NAO_EMPRESA_NOME" type="text"
                                        class="input_simples" maxlength="100"/></td>
                <td valign="top">
                    <select name="RESPONSAVEL_NAO_EMPRESA_CARGO" id="RESPONSAVEL_NAO_EMPRESA_CARGO">
                        <option> - SELECIONE -</option>
                        <?php
                        foreach ($this->CBOs as $CBO) {
                            ?>
                            <option value="<?php echo $CBO['CD_CBO'] ?>">
                                <?php echo $CBO['NM_CBO'] ?>
                            </option>
                            <?php
                        }
                        ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td valign="top" class="destacar bold">E-mail:</td>
                <td valign="top" class="destacar bold">Fone:</td>
                <td valign="top" class="destacar bold" colspan="2">Fax:</td>
            </tr>
            <tr>
                <td><input name="RESPONSAVEL_NAO_EMPRESA_EMAIL" id="RESPONSAVEL_NAO_EMPRESA_EMAIL" type="text"
                           class="input_simples w300" maxlength="80"/></td>
                <td valign="top"><input name="RESPONSAVEL_NAO_EMPRESA_FONE" id="RESPONSAVEL_NAO_EMPRESA_FONE"
                                        type="text"
                                        class="input_simples w100 telefone"/></td>
                <td valign="top"><input name="RESPONSAVEL_NAO_EMPRESA_FAX" id="RESPONSAVEL_NAO_EMPRESA_FAX" type="text"
                                        class="input_simples w100 telefone" colspan="2"/></td>
            </tr>
            <tr>
                <td valign="top" class="destacar bold">Confirme o E-mail:</td>
                <td colspan="2"></td>
            </tr>
            <tr>
                <td><input name="RESPONSAVEL_NAO_EMPRESA_EMAIL_CONFIRMA" id="RESPONSAVEL_NAO_EMPRESA_EMAIL_CONFIRMA"
                           type="text" maxlength="80"
                           class="input_simples w300"/></td>
                <td colspan="2"></td>
            </tr>
        </table>

        <table id="responsavel-empresa" align="center" border="0" class="tabela" width="95%"
               background="<?php echo $this->baseUrl('img/benificiario.png') ?>">
            <tr>
                <td colspan="3"></td>
            </tr>
            <tr>
                <td colspan="3" class="destacar bold">
                    <h4 class="">Dados do representante legal da empresa</h4>
                </td>
            </tr>

            <tr>
                <td colspan="3">
                    <div id="msgAjax" class="errorAjax" style="display:none;"></div>
                </td>
            </tr>

            <tr>
                <td valign="top" class="w100">CPF: <img src="<?php echo $this->baseUrl('img/ajax-loader_4.gif'); ?>"
                                                        id="imgPF" style="display: none;"/></td>
                <td valign="top">Nome:</td>
                <td valign="top" class="destacar bold">Cargo:</td>
            </tr>
            <tr>
                <td valign="top"><input name="RESPONSAVEL_CPF" id="RESPONSAVEL_CPF" type="text"
                                        class="input_simples cpf"/></td>
                <td valign="top"><input disabled="true" name="RESPONSAVEL_NOME" id="RESPONSAVEL_NOME" type="text"
                                        class="input_simples" maxlength="100"/></td>
                <td valign="top">
                    <select name="RESPONSAVEL_CARGO" id="RESPONSAVEL_CARGO">
                        <option> - SELECIONE -</option>
                        <?php
                        foreach ($this->CBOs as $CBO) {
                            ?>
                            <option value="<?php echo $CBO['CD_CBO'] ?>">
                                <?php echo $CBO['NM_CBO'] ?>
                            </option>
                            <?php
                        }
                        ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td valign="top" class="destacar bold">E-mail:</td>
                <td valign="top" class="destacar bold">Fone:</td>
                <td valign="top" class="destacar bold" colspan="2">Fax:</td>
            </tr>
            <tr>
                <td><input name="RESPONSAVEL_EMAIL" id="RESPONSAVEL_EMAIL" type="text" class="input_simples w300"
                           maxlength="80"/></td>
                <td valign="top"><input name="RESPONSAVEL_FONE" id="RESPONSAVEL_FONE" type="text"
                                        class="input_simples w100 telefone"/></td>
                <td valign="top"><input name="RESPONSAVEL_FAX" id="RESPONSAVEL_FAX" type="text"
                                        class="input_simples w100 telefone" colspan="2"/></td>
            </tr>
            <tr>
                <td valign="top" class="destacar bold">Confirme o E-mail:</td>
                <td colspan="2"></td>
            </tr>
            <tr>
                <td><input name="RESPONSAVEL_EMAIL_CONFIRMA" id="RESPONSAVEL_EMAIL_CONFIRMA" type="text"
                           class="input_simples w300" maxlength="80"/></td>
                <td colspan="2"></td>
            </tr>
            <tr id="arquivo_10">
                <td class="arquivoTd" colspan="3">
                    Procuração representante da empresa:
                    <input type="file" name="ANEXO_11" id="ANEXO_11" class="input_simples arquivosBlock files"/>
                    <label for="ANEXO_11" id="ERROR_ANEXO_11" class="error"
                           style="display: none; margin-top: 2px"></label>
                </td>
            </tr>
            <tr>
                <td colspan="3">&nbsp;</td>
            </tr>
            <tr>
                <td colspan="3" valign="top">
                    <input type="checkbox" name="AUTORIZO_MINC" id="AUTORIZO_MINC" checked="checked"/>
                    Autorizo o MC a divulgar que sou empresa beneficiária cadastrada junto ao Programa de Cultura do
                    Trabalhador.
                    <a href="#myModalSobreAutorizacaoBeneficiaria"
                       role="button"
                       class="" data-toggle="modal">
                        <img src="<?php echo $this->baseUrl('img/help-icon.png'); ?>"
                             style="width: 25px; height: 25px; cursor: pointer; margin-top: 0;border: 0; padding: 0;"
                             title="Sobre a Divulgação de Dados da Beneficiaria"/></a>
                </td>
            </tr>
            <tr>
                <td colspan="3" valign="top" class="destacar bold">
                    <input type="radio" value="1" name="AUTORIZO_OPERADORA" checked="checked">
                    Autorizo o MC a divulgar meus dados de contato a operadora selecionada.
                </td>
            </tr>
            <tr>
                <td colspan="3" valign="top" class="destacar bold">
                    <input type="radio" value="2" name="AUTORIZO_OPERADORA">
                    Autorizo o MC a divulgar meus dados de contato a todas operadoras cadastradas no sistema
                    Vale-Cultura.
                </td>
            </tr>

        </table>

        <table width="95%" align="center" class="tabela">
            <tr>
                <th style="text-align: center;"><h3 class="footer-headline"><span>Veracidade</span></h3></th>
            </tr>
            <tr>
                <td>
                    <input type="checkbox" name="ConfimaRegras" id="ConfimaRegras" style="float:left"/>
                    <div>&nbsp; Li e estou de acordo com as regras do Programa de Cultura do Trabalhador e confirmo, sob
                        as penas da lei, a veracidade de todas as informações prestadas neste cadastro.
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <input type="checkbox" name="ConfimaSecult" id="ConfimaSecult" style="float:left"/>
                    <div>&nbsp; Autorizo o MC a divulgar os dados da empresa como beneficiária do Programa de
                        Cultura do Trabalhador.
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <input type="checkbox" name="ConfimaLei" id="ConfimaLei" style="float:left"/>
                    <div>&nbsp; Confirmo sob pena de lei a veracidade de todas as informações prestadas neste cadastro.
                    </div>
                </td>
            </tr>
            <tr>
                <td>Digite o c&oacute;digo abaixo: <input name="captcha[input]" id="captcha[input]"
                                                          class="input_simples" type="text"></td>
            </tr>
            <tr>
                <td id="captcha" style="height: 80px"></td>
            </tr>
        </table>
        <br/>
        <table class="tabela">
            <tr>
                <td class="centro">
                    <button id="btnSalvar" class="btn btn btn-inverse" type="submit" style=""
                            id="enviaForm">Salvar
                    </button>
                    <button id="btnCancelar" class="btn btn btn-inverse" type="button" style=""
                            onclick="fechaModal();">Cancelar
                    </button>
                    <button id="btnResetar" class="btn btn btn-inverse" type="reset" style="">Limpar
                    </button>
                </td>
            </tr>
        </table>

        <br clear="all"/>

        <table id="btFechar" style="display:none" class="tabela">
            <tr></tr>
        </table>
    </form>

</div>

<div style="position: absolute; width: 80%; margin-top: -50px; z-index:9900; display: none;" id="myModal">
    <div class="alert alert-error">
        <strong>ATENÇÃO!</strong> <br><br>
        Prezado Beneficiário,

        Você não está autorizando a liberação do seu contato para nenhuma empresa operadora.
        Isto poderá dificultar o contato da operadora com a sua empresa.
        Favor entrar em contato com a empresa operadora de sua preferência para viabilizar a contratação dos serviços.
        <br><br>
        <button class="btn btn-mini btn-success" onclick="enviarForm()" value="Submit">Confirmar</button>
        <button class="btn btn-mini btn-warning" onclick="$('#myModal').fadeOut(); $('#mascara2').fadeOut();">Cancelar
        </button>
    </div>
</div>

<div class="mascara" id="mascara2"></div>

<script type="text/javascript">

    function num(dom) {
        dom.value = dom.value.replace(/\D/g, '');
    }

    var confirmado = false;

    jQuery(document).ready(function () {

        $(".cep").mask("99999-999");
        $(".data").mask("99/99/9999");
        $(".cpf").mask("999.999.999-99");
        $(".cnpj").mask("99.999.999/9999-99");
        $(".telefone").mask("(99) 9999-9999?9");
        // $(".telefone-simples").mask("9999-9999?9");

        $(".telefone-simples").blur(function () {
            mascaraDeTelefone($(this)[0]);
        });

        $(".telefone-simples").focus(function () {
            tiraHifen($(this)[0]);
        });

        $(".data-simples").mask("99/99/9999");

        gerarCaptcha();
        calculaTotalFuncionarios();

        $('#btnResetar').click(function () {
            $('#IDPJ').val('');
            $('#ID_EMPRESA_PF').val('');
            $('#ID_NAO_EMPRESA_PF').val('');

            $('#EMPRESA_RAZAOSOCIAL').html('');
            $('#EMPRESA_NOMEFANTASIA').html('');
            $('#EMPRESA_SITUACAO').html('');
            $('#NATUREZA_JURIDICA').html('');
            $('#CNAE_PRIMARIO').html('');
            $('#CNAE_SECUNDARIOS').html('');
            $('#EMPRESA_COMPLEMENTO').val('');
            $('#EMPRESA_NUMERO').val('');
            $('#EMPRESA_CEP').val('');
            $('#EMPRESA_CEP').attr('valor', '');
            $('#ID_ENDERECO').val('0');

            $('#EMPRESA_UF').html('<option> - Informe o CEP - </option>');
            $('#EMPRESA_MUNICIPIO').html('<option> - Informe o CEP - </option>');
            $('#EMPRESA_BAIRRO').html('<option> - Informe o CEP - </option>');
            $('#EMPRESA_ENDERECO').html('- Informe o CEP -');

            $('#msgAjaxPJ').html('');
            $('#msgAjaxPJ').show();
            $('#msgAjaxPF').html('');
            $('#msgAjaxPF').show();

            $('#msgAjaxPFNaoEmpresa').html('');
            $('#msgAjaxPFNaoEmpresa').show();
        });

        $('.responsavel_empresa').click(function () {
            $('#responsavel-nao-empresa').addClass('hide');

            $("#RESPONSAVEL_NAO_EMPRESA_CPF").rules("remove");
            $("#RESPONSAVEL_NAO_EMPRESA_FONE").rules("remove");
            $("#RESPONSAVEL_NAO_EMPRESA_EMAIL").rules("remove");
            $("#RESPONSAVEL_NAO_EMPRESA_EMAIL_CONFIRMA").rules("remove");

            if ($(this).val() == 0) {
                $('#responsavel-nao-empresa').removeClass('hide');

                $("#RESPONSAVEL_NAO_EMPRESA_CPF").rules("add", {
                    required: true,
                    messages: {
                        required: "Informe o CPF"
                    }
                });

                $("#RESPONSAVEL_NAO_EMPRESA_FONE").rules("add", {
                    required: true,
                    messages: {
                        required: "Campo obrigat&oacute;rio"
                    }
                });

                $("#RESPONSAVEL_NAO_EMPRESA_EMAIL").rules("add", {
                    required: true,
                    email: true,
                    messages: {
                        required: "Informe o E-mail",
                        email: "Digite um e-mail v&aacute;lido"
                    }
                });

                $("#RESPONSAVEL_NAO_EMPRESA_EMAIL_CONFIRMA").rules("add", 'emailnaoempresacheck');
            }
        });

        // Vamos buscar os dados do CNPJ Agora!
        $('#EMPRESA_CNPJ').focusout(function () {

            $('#IDPJ').val('');
            $('#EMPRESA_RAZAOSOCIAL').html('');
            $('#EMPRESA_NOMEFANTASIA').html('');
            $('#NATUREZA_JURIDICA').html('');
            $('#CNAE_PRIMARIO').html('');
            $('#CNAE_SECUNDARIOS').html('');
            $('#EMPRESA_SITUACAO').html('');
            $('#EMPRESA_COMPLEMENTO').val('');
            $('#EMPRESA_NUMERO').val('');
            $('#EMPRESA_CEP').val('');
            $('#EMPRESA_CEP').attr('valor', '');
            $('#ID_ENDERECO').val('0');

//            $('.descEmpresa').hide();
            $('#msgAjaxPJ').html('');
            $('#imgPJ').show();

            bloqueaCadastro();

            var txt = $(this).val();

            if (txt == '__.___.___/____-__') {
                $('#imgPJ').hide();
            } else {

                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->url(array('module' => 'operadora', 'controller' => 'cadastro', 'action' => 'busca-pessoa-juridica')); ?>',
                    data: {EMPRESA_CNPJ: $(this).val(), tipoPJ: 'B'},
                    dataType: 'json',
                    success: function (data) {

                        $('#imgPJ').hide();
                        if (data.error != '') {
                            $('#msgAjaxPJ').html(data.error);
                            $('#msgAjaxPJ').show();
                        } else {
                            // Preenche os dados
                            $('#IDPJ').val(data.dados.idpj);
                            $('#EMPRESA_RAZAOSOCIAL').html(data.dados.razaosocial);
                            if (data.dados.nomefantasia === " ") {
                                $('#EMPRESA_NOMEFANTASIA').html('<input name="EMPRESA_NMFANTASIA" id="EMPRESA_NMFANTASIA" maxlength="100" type="text" class="input_simples w200 block" />');
                            } else {
                                $('#EMPRESA_NOMEFANTASIA').html(data.dados.nomefantasia);
                            }
                            $('#NATUREZA_JURIDICA').html(data.dados.naturezajuridica);
                            $('#CNAE_PRIMARIO').html(data.dados.CNAEPrimario);
                            $('#CNAE_SECUNDARIOS').html(data.dados.CNAESecundarios);
                            $('#EMPRESA_SITUACAO').html(data.dados.situacaocnpj);
                            $('#EMPRESA_COMPLEMENTO').val(data.dados.dscomplementoendereco);
                            $('#EMPRESA_NUMERO').val(data.dados.nrcomplemento);
                            if (data.dados.cep != 'N') {
                                $('#EMPRESA_CEP').val(data.dados.cep);
                                $('#EMPRESA_CEP').attr('valor', data.dados.cep);
                                $('#ID_ENDERECO').val(data.dados.idendereco);
                                $.ajax({
                                    type: "POST",
                                    url: '<?php echo $this->url(array('module' => 'operadora', 'controller' => 'cadastro', 'action' => 'buscaenderecoporcep')); ?>',
                                    data: {CEP: data.dados.cep},
                                    dataType: 'json',
                                    success: function (data) {
                                        carregaEndereco(data);
                                    }
                                });
                                $('#EMPRESA_TIPO_LUCRO').focus();
                            }
                            $('.descEmpresa').show();
                            desbloqueaCadastro();
                        }

                    }, error: function (data) {
                        $('#msgAjaxPJ').html(data.error);
                        $('#msgAjaxPJ').show();
                        $('#imgPJ').hide();
                    }
                });
            }

        });

        // Vamos buscar os dados do CNPJ Agora!
        $('#RESPONSAVEL_CPF').focusout(function () {

            $('#IDPF').val('');
            $('#RESPONSAVEL_NOME').val('');
            $('#msgAjax').hide();
            $('#imgPF').show();

            var txt = $(this).val();

            if (txt == '___.___.___-__') {
                $('#imgPF').hide();
            } else {

                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->url(array('module' => 'operadora', 'controller' => 'cadastro', 'action' => 'busca-pessoa-fisica')); ?>',
                    data: {RESPONSAVEL_CPF: $(this).val(), TIPO_VINCULO: 'B'},
                    dataType: 'json',
                    success: function (data) {

                        if (data.error != '') {
                            $('#msgAjax').html(data.error);
                            $('#msgAjax').show();
                            $('#imgPF').hide();
                        } else {
                            // Preenche os dados
                            $('#IDPF').val(data.dados.idpf);
                            $('#RESPONSAVEL_NOME').val(data.dados.nome);
                            $('#RESPONSAVEL_CARGO').focus();
                            $('#imgPF').hide();
                        }

                    }, error: function (data) {
                        $('#msgAjax').html(data.error);
                        $('#msgAjax').show();
                        $('#imgPF').hide();
                    }
                });
            }
        });

        // Vamos buscar os dados do CNPJ Agora!
        $('#RESPONSAVEL_NAO_EMPRESA_CPF').focusout(function () {

            $('#ID_NAO_EMPRESA_PF').val('');
            $('#RESPONSAVEL_NAO_EMPRESA_NOME').val('');
            $('#msgAjaxNaoEmpresa').hide();
            $('#imgPFNaoEmpresa').show();

            var txt = $(this).val();

            if (txt == '___.___.___-__') {
                $('#imgPFNaoEmpresa').hide();
            } else {

                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->url(array('module' => 'operadora', 'controller' => 'cadastro', 'action' => 'busca-pessoa-fisica')); ?>',
                    data: {RESPONSAVEL_CPF: $(this).val(), TIPO_VINCULO: 'B'},
                    dataType: 'json',
                    success: function (data) {

                        if (data.error != '') {
                            $('#msgAjaxNaoEmpresa').html(data.error);
                            $('#msgAjaxNaoEmpresa').show();
                            $('#imgPFNaoEmpresa').hide();
                        } else {
                            // Preenche os dados
                            $('#ID_NAO_EMPRESA_PF').val(data.dados.idpf);
                            $('#RESPONSAVEL_NAO_EMPRESA_NOME').val(data.dados.nome);
                            $('#RESPONSAVEL_NAO_EMPRESA_CARGO').focus();
                            $('#imgPFNaoEmpresa').hide();
                        }

                    }, error: function (data) {
                        $('#msgAjaxNaoEmpresa').html(data.error);
                        $('#msgAjaxNaoEmpresa').show();
                        $('#imgPFNaoEmpresa').hide();
                    }
                });
            }
        });

        $('.nrFuncionarios').change(function () {
            calculaTotalFuncionarios();
        });

        $(".numerico").keyup(function () {
            if (isNaN($(this).val())) {
                $(this).val(0);
            }
        });

        $('.telefone').focusout(function () {
            var phone, element;
            element = $(this);
            element.unmask();
            phone = element.val().replace(/\D/g, '');
            if (phone.length > 10) {
                element.mask("(99) 99999-999?9");
            } else {
                element.mask("(99) 9999-9999?9");
            }
        }).trigger('focusout');

        $.validator.addMethod('valueNotEquals', function (value, element, arg) {
            return arg !== value;
        }, "Campo obrigat&oacute;rio");

        $("#cadastroBeneficiaria").validate({
            rules: {
                EMPRESA_CNPJ: {
                    required: true
                },
                EMPRESA_CEP: {
                    required: true
                },
                RESPONSAVEL_EMAIL: {
                    required: true, email: true
                },
                RESPONSAVEL_EMAIL_CONFIRMA: 'emailcheck',
                RESPONSAVEL_CPF: {
                    required: true
                },
                captchaForm: {
                    required: true
                },
                RESPONSAVEL_FONE: {
                    required: true
                },
                EMPRESA_TIPO_LUCRO: {
                    valueNotEquals: ''
                },

                OPERADORA_VALE: {
                    required: true
                }
            },
            messages: {
                EMPRESA_CNPJ: {
                    required: "Informe o CNPJ"
                },
                EMPRESA_CEP: {
                    required: "Informe o CEP"
                },
                RESPONSAVEL_EMAIL: {
                    required: "Informe o E-mail do respons&aacute;vel",
                    email: "Digite um e-mail v&aacute;lido"
                },
                RESPONSAVEL_CPF: {
                    required: "Informe o CPF"
                },
                captchaForm: {
                    required: "Campo obrigat&oacute;rio"
                },
                RESPONSAVEL_FONE: {
                    required: "Campo obrigat&oacute;rio"
                },
                OPERADORA_VALE: {
                    required: "Campo obrigat&oacute;rio"
                }
            },
            submitHandler: function (form) {

                // if (!($('#AUTORIZO_OPERADORA_SELECIONADA').is(":checked") || $('#AUTORIZO_TODAS_OPERADORAS').is(":checked")) && !confirmado) {
                //     $('#mascara2').fadeIn();
                //     $('#myModal').slideDown();
                // } else {
                form.submit();
                // }
            }
        });
        var left = ($('.window').width() / 2) - ($('#myModal').width() / 2);
        var top = ($('.window').height() / 2) - ($('#myModal').height() / 2);
        if (top < 0) {
            top = 10;
        }

        $('#myModal').css({'top': top, 'left': left});
        $('#mascara2').css({'width': $('.window').width() + 10, 'height': $('.window').height() + 10});

        $('#AUTORIZO_TODAS_OPERADORAS').change(function () {
            if ($(this).is(":checked")) {
                $('#AUTORIZO_OPERADORA_SELECIONADA').attr("checked", true);
                $('#AUTORIZO_OPERADORA_SELECIONADA').attr("disabled", true);
            } else {
                $('#AUTORIZO_OPERADORA_SELECIONADA').removeAttr("checked");
                $('#AUTORIZO_OPERADORA_SELECIONADA').removeAttr("disabled");
            }
        });

        $("#AUTORIZO_MINC").change(function () {
            if (!$(this).is(':checked')) {
                var c = confirm('Tem certeza que não quer ter o nome da sua empresa no rol de beneficiárias que concedem o Vale-Cultura aos seus trabalhadores?');
                if (c == false) {
                    $(this).prop('checked', true);
                }
            }
        });

    });

    // Check for the various File API support.
    if (window.File && window.FileReader && window.FileList && window.Blob) {
        // Great success! All the File APIs are supported.
    } else {
        alert('The File APIs are not fully supported in this browser.');
    }

    function handleFileSelect(evt) {
        //alert(123);
        var files = evt.target.files; // FileList object

        // files is a FileList of File objects. List some properties.
        var output = [];
        for (var i = 0, f; f = files[i]; i++) {
            if (f.type !== 'application/pdf') {
                $('#ERROR_' + $(evt.currentTarget).attr('id')).html("Apenas aquivos no formato PDF são validos");
                $('#ERROR_' + $(evt.currentTarget).attr('id')).show();
            }

            if (f.size >= 5242880) {
                $('#ERROR_' + $(evt.currentTarget).attr('id')).html("Tamanho maximo do arquivo deve ser de 5mb");
                $('#ERROR_' + $(evt.currentTarget).attr('id')).show();
            }
            if (f.size < 5242880 && f.type === 'application/pdf') {
                $('#ERROR_' + $(evt.currentTarget).attr('id')).hide();
            }
        }
    }

    document.getElementById('ANEXO_11').addEventListener('change', handleFileSelect, false);

    jQuery.validator.addMethod('emailcheck', function (value, element) {
        if ($('#RESPONSAVEL_EMAIL_CONFIRMA').val() != $('#RESPONSAVEL_EMAIL').val()) {
            return false;
        }
        return true;
    }, 'Verifique o E-mail');

    jQuery.validator.addMethod('emailnaoempresacheck', function (value, element) {
        if ($('#RESPONSAVEL_NAO_EMPRESA_EMAIL_CONFIRMA').val() != $('#RESPONSAVEL_NAO_EMPRESA_EMAIL').val()) {
            return false;
        }
        return true;
    }, 'Verifique o E-mail');

    function fechaForm() {
        $("#cadastroBeneficiaria").fadeOut();
        $("#btFechar").show();
    }

    function exibeRetorno(top) {
        $('#myModal').fadeOut();
        $('#mascara2').fadeOut();

        if (top > 150) {
            top = 150;
        }

        if (top < 80) {
            top = 80;
        }

        top = top + 30;
        $('#_frameForm').css('height', top + 'px');
        $('#iframe').css('display', 'block');
        $('#janelaLoad').animate({scrollTop: 0}, 'slow');
        $('html body').animate({scrollTop: 0}, 'slow');
        gerarCaptcha();
    }

    function buscaCep(obj) {

        valor = $(obj).attr('valor');
        valorAtual = $(obj).val().replace("-", "");

        if ((valor != '') && valor == valorAtual) {
            return false;
        }

        $('#EMPRESA_COMPLEMENTO').val('');
        $('#EMPRESA_NUMERO').val('');
        $.ajax({
            type: "POST",
            url: '<?php echo $this->url(array('module' => 'operadora', 'controller' => 'cadastro', 'action' => 'buscaenderecoporcep')); ?>',
            data: {CEP: $(obj).val()},
            dataType: 'json',
            success: function (data) {
                carregaEndereco(data);
            }
        });
    }

    function enviarForm() {
        confirmado = true;
        $('#enviaForm').click();
    }

    function gerarCaptcha() {
        $.ajax({
            type: "GET",
            url: '<?php echo $this->url(array('module' => 'operadora', 'controller' => 'cadastro', 'action' => 'gerarcaptcha')); ?>',
            success: function (data) {
                $('#captcha').html(data);
                setTimeout('gerarCaptcha()', 600000);
            }
        });
    }

    function carregaEndereco(data) {
        if (!data.error) {
            $('#EMPRESA_CEP_VALIDADOR').fadeOut();
            if (data.dados.TP_CEP != 0) {
                if (data.dados.NM_LOGRADOURO.length > 0) {
                    $('#EMPRESA_ENDERECO').val(data.dados.DS_TIPO_LOGRADOURO + ' ' + data.dados.NM_LOGRADOURO);
                    if (data.dados.DS_TIPO_LOGRADOURO !== 'M' && data.dados.DS_TIPO_LOGRADOURO !== 'D' && data.dados.DSTIPOLOGRADOURO !== 'P') {
                        $('#EMPRESA_ENDERECO').attr('disabled', 'true');
                    } else {
                        $('#EMPRESA_ENDERECO').val('');
                        $('#EMPRESA_ENDERECO').removeAttr('disabled');
                    }
                }
                if (data.dados.DS_COMPLEMENTO.length > 2) {
                    $('#EMPRESA_COMPLEMENTO').val(data.dados.DS_COMPLEMENTO);
                    $('#EMPRESA_COMPLEMENTO').attr('disabled', 'true');
                }

                $('#EMPRESA_BAIRRO').html('');

                for (var i = 0; i < data.dados.bairros.length; i++) {
                    var complemento = '';
                    if (i == 0) {
                        complemento = 'selected';
                    }
                    var option = "<option value='" + data.dados.bairros[i].ID_BAIRRO + "' " + complemento + ">" + data.dados.bairros[i].NM_BAIRRO + "</option>";
                    $('#EMPRESA_BAIRRO').append(option);
                }
                if (data.dados.bairros.length > 1) {
                    $('#EMPRESA_BAIRRO').removeAttr('disabled');
                } else {
                    $('#EMPRESA_BAIRRO').attr('disabled', 'true');
                }

                $('#EMPRESA_UF').html('');
                var option = "<option value='" + data.dados.SG_UF + "' selected >" + data.dados.NM_UF + "</option>";
                $('#EMPRESA_UF').append(option);
                $('#EMPRESA_UF').attr('disabled', 'true');

                $('#EMPRESA_MUNICIPIO').html('');
                var option = "<option value='" + data.dados.ID_MUNICIPIO + "' selected >" + data.dados.NM_MUNICIPIO + "</option>";
                $('#EMPRESA_MUNICIPIO').append(option);
                $('#EMPRESA_MUNICIPIO').attr('disabled', 'true');

            } else {
                //libera campos para preenchimento
                $('#EMPRESA_BAIRRO').removeAttr('disabled');
                $('#EMPRESA_ENDERECO').removeAttr('disabled');
            }
        } else {
            //CEP INVALIDO
            $('#EMPRESA_CEP_VALIDADOR').html('CEP inv&aacute;lido');
            $('#EMPRESA_CEP_VALIDADOR').fadeIn();

            var option = "<option> - Informe o CEP - </option>";
            $('#EMPRESA_BAIRRO').html(option);
            $('#EMPRESA_UF').html(option);
            $('#EMPRESA_MUNICIPIO').html(option);

            $('#EMPRESA_ENDERECO').val('');
            $('#EMPRESA_COMPLEMENTO').val('');
        }
    }

    function calculaTotalFuncionarios() {

        var totalFuncionaios;
        totalFuncionaios = 0;
        $("#cadastroBeneficiaria").find('.nrFuncionarios').each(function () {
            if (eval($(this).val()) > 0) {
                totalFuncionaios = eval(totalFuncionaios) + eval($(this).val());
            }
        });

        $('#totalFuncionarios').val(totalFuncionaios);
    }

    function buscaCNAE(obj) {
        $.ajax({
            type: "POST",
            url: '<?php echo $this->url(array('module' => 'beneficiaria', 'controller' => 'cadastro', 'action' => 'recupera-segundo-nivel-cnae')); ?>',
            data: {IDCNAE: $(obj).val()},
            dataType: 'json',
            success: function (data) {
                carregaCnaeSecundario(data['CNAEs']);
            }
        });
    }

    function carregaCnaeSecundario(Cnae) {
        var CnaeSecundario;
        CnaeSecundario = '';
        for (var i in Cnae) {
            if (i < Cnae.length) {
                CnaeSecundario += '<input name="IDCNAESECUNDARIO[]" type="checkbox" value="' + Cnae[i]['ID_CNAE'] + '"> ' + Cnae[i]['DS_CNAE'] + '<br>';
            }
        }
        $('#CNAE_Secundario').html(CnaeSecundario);
    }

    function print_r(arr, text, tab) {
        var text = (text ? text : "Array \n("), tab = (tab ? tab : "\t");

        for (key in arr) {
            if (typeof arr[key] == "object")
                text = print_r(arr[key], text + "\n" + tab + "[" + key + "] => Array \n" + tab + "(", "\t" + tab);
            else
                text += "\n" + tab + "[" + key + "] => " + arr[key];

            text += "\n" + (tab.substr(0, tab.length - 1)) + ")\n";
        }
        return text;

    }


    function bloqueaCadastro() {
        // Dados da empresa
        $('#EMPRESA_TIPO_LUCRO').attr('disabled', true);
        $('#EMPRESA_CEP').attr('disabled', true);
        $('#EMPRESA_COMPLEMENTO').attr('disabled', true);
        $('#EMPRESA_NUMERO').attr('disabled', true);
        // Quantidades de funcionarios
        $('.nrFuncionarios').attr('disabled', true);
        // Dados do Responsavel
        $('#RESPONSAVEL_CPF').attr('disabled', true);
        $('#RESPONSAVEL_CARGO').attr('disabled', true);
        $('#RESPONSAVEL_EMAIL').attr('disabled', true);
        $('#RESPONSAVEL_FONE').attr('disabled', true);
        $('#RESPONSAVEL_FAX').attr('disabled', true);
        $('#RESPONSAVEL_EMAIL_CONFIRMA').attr('disabled', true);
        // Botão de Salvar
        $('#btnSalvar').hide();
    }

    function desbloqueaCadastro() {
        // Dados da empresa
        $('#EMPRESA_TIPO_LUCRO').attr('disabled', false);
        $('#EMPRESA_CEP').attr('disabled', false);
        $('#EMPRESA_COMPLEMENTO').attr('disabled', false);
        $('#EMPRESA_NUMERO').attr('disabled', false);
        // Quantidades de funcionarios
        $('.nrFuncionarios').attr('disabled', false);
        // Dados do Responsavel
        $('#RESPONSAVEL_CPF').attr('disabled', false);
        $('#RESPONSAVEL_CARGO').attr('disabled', false);
        $('#RESPONSAVEL_EMAIL').attr('disabled', false);
        $('#RESPONSAVEL_FONE').attr('disabled', false);
        $('#RESPONSAVEL_FAX').attr('disabled', false);
        $('#RESPONSAVEL_EMAIL_CONFIRMA').attr('disabled', false);
        // Botão de Salvar
        $('#btnSalvar').show();
    }

    function mascaraDeTelefone(telefone) {
        const textoAtual = telefone.value;
        const isCelular = textoAtual.length === 9;
        let textoAjustado;

        if (isCelular) {
            const parte1 = textoAtual.slice(0, 5);
            const parte2 = textoAtual.slice(5, 9);
            textoAjustado = `${parte1}-${parte2}`
        } else {
            const parte1 = textoAtual.slice(0, 4);
            const parte2 = textoAtual.slice(4, 8);
            textoAjustado = `${parte1}-${parte2}`
        }

        telefone.value = textoAjustado;
    }

    function tiraHifen(telefone) {
        const textoAtual = telefone.value;
        const textoAjustado = textoAtual.replace(/\-/g, '');

        telefone.value = textoAjustado;
    }
</script>
