<div class="container-fluid-full">
    <div class="row-fluid">

        <!-- start: Main Menu -->
        <div id="sidebar-left" class="span2">

            <div class="row-fluid actions">

                <input type="text" class="search span12" placeholder="O que deseja buscar?" />

            </div>	
            <?php include_once 'menu.phtml'; ?>
        </div>
        <!-- end: Main Menu -->

        <!-- start: Content -->
        <div id="content" class="span10">



            <div class="row-fluid"><!--/span-->

            </div>

            <div class="row-fluid"></div>	

            <div class="row-fluid">

                <div class="box span12">
                    <div class="box-header">
                        <h2><i class="icon-edit"></i>Arquivos Anexados</h2>
                        <div class="box-icon">

                        </div>
                    </div>
                    <div class="box-content">
                        <fieldset>
                            <div id="conteudo">

                                <table width="100%" class="table table-striped table-bordered bootstrap-datatable ">

                                    <?php
                                    $qtdObrigatorios = 8;
                                    for ($i = 0; $i < 10; $i++) {
                                        if (isset($this->arquivosOperadora[$i])) {
                                            $arquivoExiste = true;
                                            $nomeDocumento = $this->arquivosOperadora[$i]['dsArquivo'];
                                            $url = $this->baseUrl('arquivos/' . $this->arquivosOperadora[$i]['dsCaminhoArquivo']);
                                            $id = $this->arquivosOperadora[$i]['idArquivo'];
                                        } else {
                                            $arquivoExiste = false;
                                            $nomeDocumento = null;
                                            $url = null;
                                            $id = 'ANEXO_' . ($i + 1);
                                        }

                                        if ($i >= $qtdObrigatorios) {
                                            $campo = '<input type="text" name="ANEXO_NOME" style="width: 390px" value="' . $nomeDocumento . '">';
                                        } else {
                                            $campo = $nomeDocumento;
                                        }
                                        ?>
                                        <tr>
                                            <td>
                                                <form method="POST" id="FORM_<?php echo $i ?>"  enctype="multipart/form-data" action="<?php echo $this->url(array('module' => 'operadora', 'controller' => 'index', 'action' => 'arquivos-upload')); ?>" style="margin: 0px;">
                                                    <table width="100%" class="tabela">
                                                        <tr>
                                                            <td width="45%" style="background-color: transparent;">
                                                                <?php echo $campo ?>
                                                            </td>
                                                            <td width="15%" style="background-color: transparent;">
                                                                <a href="<?php echo $url ?>" target="_blank">
                                                                    <b>baixar o arquivo</b>
                                                                </a>
                                                            </td>
                                                            <td width="40%" style="background-color: transparent;">
                                                                <input type="file" name="<?php echo $id ?>"  value='substituir' />
                                                                <a id="btnAprovar" onclick="confirmaEnvio($('#FORM_<?php echo $i ?>'))" class="btn btn-primary" style="float:right">Enviar e substituir</a>

                                                            </td>
                                                        </tr>
                                                    </table>
                                                </form>
                                            </td>
                                        </tr>
                                        <?php
                                    }
                                    ?>
                                </table>

                                <br clear="all" />
                            </div>
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
        <!-- end: Content -->

    </div><!--/fluid-row-->


    <div class="clearfix"></div>
    <br>

</div>

<script>
                                                                    function confirmaEnvio(form) {
                                                                        var r = confirm("Tem certeza que deseja substituir esse documento?")
                                                                        if (r == true)
                                                                        {
                                                                            $(form).submit();
                                                                        }
                                                                    }
</script>