<div class="container-fluid-full">
    <div class="row-fluid">

        <!-- start: Main Menu -->
        <div id="sidebar-left" class="span2">

            <div class="row-fluid actions">

                <input type="text" class="search span12" placeholder="O que deseja buscar?" />

            </div>	
            <?php include_once 'menu.phtml'; ?>
        </div>
        <!-- end: Main Menu -->

        <!-- start: Content -->
        <div id="content" class="span10">



            <div class="row-fluid"><!--/span-->

            </div>

            <div class="row-fluid"></div>	

            <div class="row-fluid">

                <div class="box span12">
                    <div class="box-header">
                        <h2><i class="icon-edit"></i>CNAE</h2>
                        <div class="box-icon">

                        </div>
                    </div>
                    <div class="box-content">
                        <fieldset>
                            <table width="100%" class="table table-striped table-bordered bootstrap-datatable ">
                                <tr>
                                    <td class="destacar bold" style="width: 50%;">C&oacute;digo da Atividade Econ&ocirc;mica Principal</td>
                                    <td class="destacar bold" colspan="2">Codigos das Atividades Econ&ocirc;micas Secund&aacute;rias</td>
                                </tr>
                                <tr>
                                    <td valign="top">
                                        <select name="IDCNAE" onchange="buscaCNAE(this)" id="IDCNAE" class="select_simples" style="width: 99%;">
                                            <option value=""> - Selecione - </option>     
                                            <?php foreach ($this->CNAEPrincipal as $CNAE) { ?>
                                            <option value="<?php echo $CNAE['IDCNAE'] ?>" <?php if($this->idCNAEN1 == $CNAE['IDCNAE']){echo 'selected="selected"';} ?>><?php echo $CNAE['DSCNAE'] ?></option>     
                                            <?php } ?>
                                        </select>
                                    </td>
                                    <td class="destacar bold" id="CNAE_Secundario" colspan="2">
                                    </td>
                            </table>

                            <br clear="all" />
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end: Content -->

</div><!--/fluid-row-->


<div class="clearfix"></div>

<script>
    jQuery(document).ready(function() {
        
        $(".brn-atualizar-valor").hide();
        $(".imgConfirm").hide();
        
        $(".txt_qtd").keyup(function(){
            
            $(".imgConfirm").hide();
            var id_btn = $(this).attr('id_btn');
            var valorOriginal = parseInt($(this).attr('valor'));
            var valorReal = parseInt($(this).val());
            
            if(valorReal != valorOriginal){
                $("#"+id_btn).show();
            }
            
        });
        
        $(".brn-atualizar-valor").click(function(){
            var id_btn = $(this).attr('id');
            var valor = $('#qtd_'+id_btn).val();
        
            $.ajax({
                type: "POST",
                url: "<?php echo $this->url(array('module' => 'beneficiaria', 'controller' => 'index', 'action' => 'alterar-faixa-salarial')); ?>",
                data: {idTipoFaixaSalarial: id_btn, qtTrabalhadorFaixaSalarial:valor },
                dataType: 'json',
                success: function(json) {
            
                    if(json.msg = 'confirm'){
                        $('#'+id_btn).hide();
                        $('#qtd_'+id_btn).attr('valor',json.id);
                        $('#img_'+id_btn).show();
                    }
            
                },error: function(){
                    alert('Erro ao atualizar!');
                }
            });
        
        
        
            return false;
        });
        
    });
</script>