<div class="container-fluid-full">
    <div class="row-fluid">

        <!-- start: Main Menu -->
        <div id="sidebar-left" class="span2">
            <div class="row-fluid actions">
                <input type="text" class="search span12" placeholder="O que deseja buscar?" />
            </div>	
            <?php include_once 'menu.phtml'; ?>
        </div>
        <!-- end: Main Menu -->

        <!-- start: Content -->
        <div id="content" class="span10">
            <div class="row-fluid">

                <div class="box span12">
                    <div class="box-header">
                        <h2><i class="icon-edit"></i>Gerenciar Benefici&aacute;ria</h2>
                        <div class="box-icon">

                        </div>
                    </div>
                    <div class="box-content">
                        <fieldset>
                            <div id="conteudo">
                                <form id="dadosEmpresa" method="POST" action="<?php echo $this->url(array('module' => 'beneficiaria', 'controller' => 'index', 'action' => 'atualizar-dados-beneficiaria')); ?>" >
                                    <input type="hidden" name="EMPRESA_OPERADORA_ATUAL" value="<?php echo $this->beneficiaria['idOperadora']; ?>" />
                                    <table class="table table-striped table-bordered bootstrap-datatable ">
                                        <tr>
                                            <th colspan="3">Dados da Empresa Benefici&aacute;ria</th>
                                        </tr>
                                        <tr>
                                            <td class="destacar bold">CNPJ:</td>
                                            <td class="destacar bold" colspan="2">Raz&atilde;o Social:</td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <?php echo $this->beneficiaria['nrCnpj']; ?>
                                            </td>
                                            <td colspan="2"><?php echo $this->beneficiaria['nmRazaoSocial']; ?></td>
                                        </tr>
                                        <tr>
                                            <td class="destacar bold">Nome Fantasia:</td>
                                            <td class="destacar bold" colspan="2">CEP:</td>
                                        </tr>
                                        <tr>
                                            <td><?php echo $this->beneficiaria['nmFantasia']; ?></td>
                                            <td colspan="2">
                                                <input type="text" class="input_simples w150 cep" name="cep" id="cep" onchange="buscaCep(this)" value="<?php echo $this->beneficiaria['cep']; ?>">
                                                <label for="EMPRESA_CEP" id="EMPRESA_CEP_VALIDADOR" class="error" style="display: none"></label>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="destacar bold">Bairro:</td>
                                            <td class="destacar bold" colspan="2">Endere&ccedil;o:</td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <select class="input_simples w150" name="nmBairro" id="nmBairro">
                                                    <option value="<?php echo $this->beneficiaria['idBairro']; ?>"> <?php echo $this->beneficiaria['nmBairro']; ?> </option>
                                                </select>
                                            </td>
                                            <td colspan="2">
                                                <input type="text" class="input_simples w150" name="logradouro" id="logradouro" value="<?php echo $this->beneficiaria['logradouro']; ?>">
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="destacar bold">Complemento:</td>
                                            <td class="destacar bold" colspan="2">Número:</td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <input type="text" class="input_simples w150" name="dsComplementoEndereco" id="dsComplementoEndereco" maxlength="50" value="<?php echo $this->beneficiaria['dsComplementoEndereco']; ?>">
                                            </td>
                                            <td colspan="2">
                                                <input type="text" class="input_simples w150" name="nrComplemento" id="nrComplemento" maxlength="10" value="<?php echo $this->beneficiaria['nrComplemento']; ?>">
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="destacar bold">Pa&iacute;s:</td>
                                            <td class="destacar bold">Estado:</td>
                                            <td class="destacar bold">Munic&iacute;pio:</td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <input disabled="true" type="text" class="input_simples w150" name="Pais" id="Pais" value="<?php echo $this->beneficiaria['Pais']; ?>">
                                            </td>
                                            <td>
                                                <select class="input_simples w150" name="Estado" id="Estado">
                                                    <option value="<?php echo $this->beneficiaria['sgUF']; ?>"> <?php echo $this->beneficiaria['nmUf']; ?> </option>
                                                </select> 
                                            </td>
                                            <td>
                                                <select class="input_simples w150" name="Municipio" id="Municipio">
                                                    <option value="<?php echo $this->beneficiaria['idMunicipio']; ?>"> <?php echo $this->beneficiaria['nmMunicipio']; ?> </option>
                                                </select>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                Regime de tributação
                                            </td>
                                            <td>
                                                Natureza Jur&iacute;dica:
                                            </td>
                                            <td>
                                                Operadora
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <select name="EMPRESA_TIPO_LUCRO" id="EMPRESA_TIPO_LUCRO" class="select_simples w200">
                                                    <option value=""> - Selecione - </option>     
                                                    <?php foreach ($this->tipoLucro as $lucro) { ?>
                                                        <option value="<?php echo $lucro['ID_TIPO_LUCRO'] ?>"  <?php echo $lucro['ID_TIPO_LUCRO'] == $this->beneficiaria['idTipoLucro'] ? 'selected="selected"' : ''; ?>> <?php echo $lucro['DS_TIPO_LUCRO'] ?> </option>     
                                                    <?php } ?>
                                                </select>
                                            </td>
                                            <td><?php echo $this->beneficiaria['dsNaturezaJuridica']; ?></td>
                                            <td>
                                                <select name="EMPRESA_OPERADORA" id="EMPRESA_OPERADORA" class="select_simples">
                                                    <option value=""> - Selecione - </option>     
                                                    <?php foreach ($this->operadoras as $operadora) { ?>
                                                        <option value="<?php echo $operadora['idOperadora'] ?>" <?php echo $operadora['idOperadora'] == $this->beneficiaria['idOperadora'] ? 'selected="selected"' : '' ?>> <?php
                                                            echo $operadora['nmFantasia'];
                                                            echo $operadora['idSituacaoXX'] != 2 ? ' (Inativa)' : ''
                                                            ?> </option>     
                                                    <?php } ?>
                                                </select>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                Atividade Econômica Principal
                                            </td>
                                            <td colspan="2">
                                                Atividades Econômicas Secundárias
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <?php foreach ($this->CNAEPrincipal as $CNAE): ?>
                                                <?php echo $CNAE['ID_CNAE'] ?> - <?php echo $CNAE['dsCNAE'] ?><br />     
                                                <?php endforeach; ?>
                                            </td>
                                            <td class="destacar bold" colspan="2">
                                                <?php foreach ($this->CNAESecundarios as $CNAE): ?>
                                                <?php echo $CNAE['ID_CNAE'] ?> - <?php echo $CNAE['dsCNAE'] ?><br />     
                                                <?php endforeach; ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="3">
                                                <input type="radio" <?php
                                                if ($this->beneficiaria['ST_DIVULGAR_DADOS'] == 1) {
                                                    echo 'checked="checked"';
                                                }
                                                ?> name="AUTORIZO_OPERADORA" value="1" style="margin:0px">
                                                Autorizo o MinC a divulgar meus dados de contato a operadora selecionada.
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="3">
                                                <input type="radio" <?php
                                                if ($this->beneficiaria['ST_DIVULGAR_DADOS'] == 2) {
                                                    echo 'checked="checked"';
                                                }
                                                ?> name="AUTORIZO_OPERADORA" value="2" style="margin:0px">
                                                Autorizo o MinC a divulgar meus dados de contato a todas operadoras cadastradas no sistema Vale-Cultura.
                                            </td>
                                        </tr>
                                    </table>
                                    <table class="table table-striped table-bordered bootstrap-datatable ">
                                        <div class="box-header">
                                            <h2><i class="icon-edit"></i>Hist&oacute;rico de Status</h2>
                                            <div class="box-icon"></div>
                                        </div>
                                        <tr>
                                            <td class="destacar bold"><strong>Status</strong></td>
                                            <td class="destacar bold"><strong>Data da atualiza&ccedil;&atilde;o</strong></td>
                                            <td class="destacar bold"><strong>Justificativa</strong></td>
                                        </tr>
                                        <?php foreach ($this->historico as $h): ?>
                                            <tr>
                                                <td class=""><?php echo $h['dsTipoSituacao']; ?></td>
                                                <td class=""><?php echo $h['dtSituacao']; ?></td>
                                                <td class=""><?php echo $h['dsJustificativa']; ?></td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </table>
                            </div>

                            <div class="form-actions">
                                <a id="btnAprovar" onclick="$('#dadosEmpresa').submit();" class="btn btn-primary">Atualizar</a>
                                <a id="btnVoltar"   class="btn">Voltar</a>
                            </div>

                            <br clear="all" />
                    </div>
                    </fieldset>
                </div>
            </div>
        </div>
    </div>
    <!-- end: Content -->

</div><!--/fluid-row-->


<div class="clearfix"></div>
<br>

</div>

<script>


    jQuery(document).ready(function() {

//        $('#AUTORIZO_TODAS_OPERADORAS').change(function() {
//           $('#AUTORIZO_TODAS_OPERADORAS').attr("class",''); 
//           $('#AUTORIZO_OPERADORA_SELECIONADA').attr("class",''); 
//           $('#AUTORIZO_OPERADORA_SELECIONADA').attr("style",''); 
//            if ($(this).is(":checked")) {
//                $('#AUTORIZO_OPERADORA_SELECIONADA').attr("checked", "checked");
//                $('#AUTORIZO_OPERADORA_SELECIONADA').attr("disabled", true);
//           } else {
//                $('#AUTORIZO_OPERADORA_SELECIONADA').removeAttr("checked");
//                $('#AUTORIZO_OPERADORA_SELECIONADA').removeAttr("disabled");
//            }
//        });

        buscaCep($('#cep'));
        $(".data").mask("99/99/9999");
        $(".cpf").mask("999.999.999-99");
        $(".cnpj").mask("99.999.999/9999-99");
        $(".telefone").mask("(99) 9999-9999");
        $(".cep").mask("99999-999");
        $("#dadosEmpresa").validate({
            rules: {
                EMPRESA_CNPJ: {
                    required: true
                },
                EMPRESA_CEP: {
                    required: true
                },
                logradouro: {
                    required: true
                }
            },
            messages: {
                EMPRESA_CNPJ: {
                    required: "Informe o CNPJ"
                },
                EMPRESA_CEP: {
                    required: "Informe o CEP"
                },
                logradouro: {
                    required: "Informe o endereço"
                }
            }
        });

    });

    function buscaCep(obj) {
        var cep = $(obj).val();
        if (cep.length >= 9) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->url(array('module' => 'operadora', 'controller' => 'cadastro', 'action' => 'buscaenderecoporcep')); ?>',
                data: {CEP: $(obj).val()},
                dataType: 'json',
                success: function(data) {
                    carregaEndereco(data);
                }
            });
        } else {
            cepInvalido();
        }
    }

    function carregaEndereco(data) {
        if (!data.error) {
            $('#EMPRESA_CEP_VALIDADOR').fadeOut();
            if (data.dados.TP_CEP !== 0) {
                if (data.dados.NM_LOGRADOURO.length > 0) {
                    $('#logradouro').val(data.dados.DS_TIPO_LOGRADOURO + ' ' + data.dados.NM_LOGRADOURO);
                    if (data.dados.DS_TIPO_LOGRADOURO !== 'M' && data.dados.DS_TIPO_LOGRADOURO !== 'D' && data.dados.DS_TIPO_LOGRADOURO !== 'P') {
                        $('#logradouro').attr('disabled', 'true');
                    } else {
                        $('#logradouro').removeAttr('disabled');
                    }
                }

                if (data.dados.DS_COMPLEMENTO.length > 2) {
                    $('#dsComplementoEndereco').val(data.dados.DS_COMPLEMENTO);
                    $('#dsComplementoEndereco').attr('disabled', 'true');
                }

                $('#nmBairro').html('');
                for (var i = 0; i < data.dados.bairros.length; i++) {
                    var complemento = '';

                    if (i == 0) {
                        complemento = 'selected';
                    }

                    var option = "<option value='" + data.dados.bairros[i].ID_BAIRRO + "' " + complemento + ">" + data.dados.bairros[i].NM_BAIRRO + "</option>";
                    $('#nmBairro').append(option);
                }

                if (data.dados.bairros.length > 1) {
                    $('#nmBairro').removeAttr('disabled');
                } else {
                    $('#nmBairro').attr('disabled', 'true');
                }

                $('#Estado').html('');
                var option = "<option value='" + data.dados.SG_UF + "' selected >" + data.dados.NM_UF + "</option>";
                $('#Estado').append(option);
                $('#Estado').attr('disabled', 'true');
                $('#Municipio').html('');
                var option = "<option value='" + data.dados.ID_MUNICIPIO + "' selected >" + data.dados.NM_MUNICIPIO + "</option>";
                $('#Municipio').append(option);
                $('#Municipio').attr('disabled', 'true');
            } else {
                //libera campos para preenchimento
                $('#nmBairro').removeAttr('disabled');
                $('#logradouro').removeAttr('disabled');
            }
        } else {
            cepInvalido();
        }
    }

    function cepInvalido() {
        //CEP INVALIDO
        $('#EMPRESA_CEP_VALIDADOR').html('CEP inválido');
        $('#EMPRESA_CEP_VALIDADOR').fadeIn();
        var option = "<option> - Informe o CEP - </option>";
        $('#nmBairro').html(option);
        $('#Estado').html(option);
        $('#Municipio').html(option);
        $('#logradouro').val('');
        $('#dsComplementoEndereco').val('');
    }

    function inArray(needle, haystack) {
        var length = haystack.length;
        for (var i = 0; i < length; i++) {
            if (haystack[i] == needle)
                return true;
        }
        return false;
    }

</script>