<script>
    jQuery(document).ready(function() {
        $('input[name="solicitar_descredenciamento"]').on('change', function() {
        	if( $(this).val() === 'sim' ){
        		$('#form-disabled').removeClass('disabled');
        	} else {
				$('#form-disabled').addClass('disabled');
        	}
        });

        $('input[name="firmou_contrato"]').on('change', function() {
        	if( $(this).val() === 'sim' ){
        		$('#contrato_operadora').removeAttr('disabled');
        	} else {
        		$('#contrato_operadora').attr('disabled', true);
        	}
        });
    });
</script>
<style>
	#form-disabled > table{
		display: table;
	}
	#form-disabled #descredenciamento-btn{
		display: inline-block;
	}
	#form-disabled.disabled > table,
	#form-disabled.disabled #descredenciamento-btn{
		display: none;
	}
</style>
<div class="container-fluid-full">
	<div class="row-fluid">

		<!-- start: Main Menu -->
		<div id="sidebar-left" class="span2">

			<div class="row-fluid actions">
				<input type="text" class="search span12" placeholder="O que deseja buscar?" />
			</div>

			<?php include_once 'menu.phtml'; ?>

		</div>
		<!-- end: Main Menu -->

		<!-- start: Content -->
		<div id="content" class="span10">

			<div class="row-fluid">

				<div class="box span12">
					<div class="box-header">
						<h2><i class="icon-edit"></i>Solicitar descredenciamento</h2>
						<div class="box-icon">

						</div>
					</div>
					<div class="box-content">
						<fieldset>
							<div id="conteudo">
								<form method="post" action="">
									<table class="table table-striped table-bordered bootstrap-datatable ">
										<tbody>
											<tr>
												<th>Deseja solicitar o descredenciamento de sua empresa do Programa de Cultura do Trabalhador</th>
											</tr>
											<tr>
												<td>
													<label for="solicitar_descredenciamento-1">
														<input id="solicitar_descredenciamento-1" type="radio" name="solicitar_descredenciamento" value="sim"/> Sim
													</label>
													<label for="solicitar_descredenciamento-2">
														<input id="solicitar_descredenciamento-2" type="radio" name="solicitar_descredenciamento" value="nao" checked="checked"/> N&atilde;o
													</label>				
												</td>
											</tr>
										</tbody>
									</table>

									<div id="form-disabled" class="disabled">
										<table class="table table-striped table-bordered bootstrap-datatable ">
											<tbody>
												<tr>
													<th>Informar o motivo do descredenciamento</th>
												</tr>
												<tr>
													<td>
														<ul style="list-style-type: none; margin: 0;">
															<li>
																<label for="input-1">
																	<input id="input-1" type="checkbox" name="motivo" value="sem_conhecimento">N&atilde;o ter conhecimento de que o benef&iacute;cio &eacute; concedido pela pr&oacute;pria empresa
																</label>
															</li>
															<li>
																<label for="input-2">
																	<input id="input-2" type="checkbox" name="motivo" value="inviabilidade_financeira">Inviabilidade financeira da empresa em fornecer o Vale-Cultura a seus empregados
																</label>
															</li>
															<li>
																<label for="input-3">
																	<input id="input-3" type="checkbox" name="motivo" value="ma_utilizacao">M&aacute; utiliza&ccedil;&atilde;o dos trabalhadores com o Vale-Cultura
																</label>
															</li>
															<li>
																<label for="input-4">
																	<input id="input-4" type="checkbox" name="motivo" value="insatisfacao_trabalhadores">Insatisfa&ccedil;&atilde;o dos trabalhadores com o Vale-Cultura
																</label>
															</li>
															<li>
																<label for="input-5">
																	<input id="input-5" type="checkbox" name="motivo" value="insatisfacao_empresa_operadora">Insatisfa&ccedil;&atilde;o da empresa com os servi&ccedil;os prestados pela operada escolhida
																</label>
															</li>
															<li>
																<label for="input-6">
																	<input id="input-6" type="checkbox" name="motivo" value="insatisfacao_empresa_ministerio">Insatisfa&ccedil;&atilde;o da empresa com os servi&ccedil;os prestados Minist&eacute;rio da Cultura
																</label>
															</li>
															<li>
																<label for="input-7">
																	<input id="input-7" type="checkbox" name="motivo" value="indefinicao_incentivo">Indefini&ccedil;&atilde;o da continuidade do benef&iacute;cio de Incentivo Fiscal para empresas benefici&aacute;rias
																</label>
															</li>
															<li>
																<label for="input-8">
																	<input id="input-8" type="checkbox" name="motivo" value="outros" />Outros
																	<input type="text" name="outro_motivo"/>
																</label>
															</li>
														</ul>
													</td>
												</tr>
												<tr>
													<th>Sua empresa firmou contrato com alguma operadora?</th>
												</tr>
												<tr>
													<td>
														<label for="firmou_contrato-1">
															<input id="firmou_contrato-1" type="radio" name="firmou_contrato" value="sim"/> Sim
														</label>
														<label for="firmou_contrato-2">
															<input id="firmou_contrato-2" type="radio" name="firmou_contrato" value="nao" checked="checked"/> N&atilde;o
														</label>

														<?php 
															echo "<!--<pre>"; 
															var_dump($this->operadoras); 
															echo "</pre>-->"; 
														?>

														<select disabled id="contrato_operadora" name="contrato_operadora">
															<option>Selecione a operadora</option>
															<?php foreach ($this->operadoras as $idOperadora => $operadora): ?>													
															<option value="<?php echo $idOperadora; ?>"><?php echo ($operadora['nmFantasia'] && $operadora['nmFantasia'] !== ' ') ? $operadora['nmFantasia'] : $operadora['nmRazaoSocial']; ?></option>
															<?php endforeach; ?>
														</select>		
													</td>
												</tr>
											</tbody>
										</table>

										<div class="form-actions">
											<input id="descredenciamento-btn" name="autorizacao" value="Concluir solicita&ccedil;&atilde;o de descredenciamento" class="btn btn-primary" type="submit" />
											<a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'index', 'action' => 'index'), '',true); ?>" class="btn btn-danger">Cancelar solicita&ccedil;&atilde;o de descredenciamento</a>
										</div>
									</div>

								</form>
							</div>
						</fieldset>
					</form>
				</div>
			</div>
		</div>
	</div>
	<!-- end: Content -->

</div><!--/fluid-row-->

</div><!--/.fluid-container-->
