<div class="container-fluid-full">
    <div class="row-fluid">

        <!-- start: Main Menu -->
        <div id="sidebar-left" class="span2">

            <div class="row-fluid actions">

                <input type="text" class="search span12" placeholder="O que deseja buscar?"/>

            </div>
            <?php include_once 'menu.phtml'; ?>

        </div>
        <!-- end: Main Menu -->

        <!-- start: Content -->
        <div id="content" class="span10">


            <div class="row-fluid">


            </div>
            <div class="row-fluid"><!--/span-->

            </div>

            <div class="row-fluid"></div>

            <div class="row-fluid">

                <div class="box span8" ontablet="span12" ondesktop="span8">
                    <div class="box-header">
                        <h2>COMUNICADO</h2>
                    </div>
                    <div class="box-content" style="height:308px">
                        <div class="span12" style="height:308px">
                            Certificado indisponivel.<br>
                            Status da Baneficiária: <b><?php echo $this->dsSituacao ?></b>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- end: Content -->

    </div><!--/fluid-row-->


    </body>
    </html>