
<div class="container-fluid-full">
    <div class="row-fluid">

        <!-- start: Main Menu -->
        <div id="sidebar-left" class="span2">

            <div class="row-fluid actions">

                <input type="text" class="search span12" placeholder="O que deseja buscar?" />

            </div>	
            <?php include_once 'menu.phtml'; ?>
            
        </div>
        <!-- end: Main Menu -->

        <!-- start: Content -->
        <div id="content" class="span10">


            <div class="row-fluid">

                

            </div>
            <div class="row-fluid"><!--/span-->

            </div>

            <div class="row-fluid"></div>	

            <div class="row-fluid">

                <div class="box span8" ontablet="span12" ondesktop="span8">
                    <div class="box-header">
                        <h2>COMUNICADO</h2>
                    </div>
                    <div class="box-content" style="height:308px">
                        <div class="span12" style="height:308px"> Chegou o Vale-Cultura. Um benef&iacute;cio que pode chegar &agrave;s m&atilde;os de 42 milh&otilde;es de trabalhadores brasileiros. O cart&atilde;o magn&eacute;tico pr&eacute;-pago, v&aacute;lido em todo territ&oacute;rio nacional,  no valor de 50 reais mensais, vai possibilitar ao trabalhador de carteira assinada ir ao teatro, cinema, museus, espet&aacute;culos, shows, circo ou mesmo comprar ou alugar CDs, DVDs, livros, revistas e jornais. E para aqueles que quiserem comprar um instrumento musical ou mesmo fazer um programa cultural com um custo mais elevado, uma boa not&iacute;cia: o cr&eacute;dito &eacute; cumulativo e n&atilde;o tem validade. &Eacute; s&oacute; poupar por alguns meses e adquirir o bem cultural que desejar. O Vale tamb&eacute;m pode ser usado para fazer cursos de artes, audiovisual, dan&ccedil;a, circo, fotografia, m&uacute;sica, literatura ou teatro.<br><br>

Com o intuito de que o benef&iacute;cio chegue em primeira m&atilde;o aos trabalhadores de baixa e m&eacute;dia renda, a regra &eacute; clara: as empresas t&ecirc;m de oferecer o Vale-Cultura prioritariamente aos trabalhadores que recebem at&eacute; 5 sal&aacute;rios m&iacute;nimos. Mas se a empresa quiser tamb&eacute;m pode oferecer o benef&iacute;cio para todo o quadro de funcion&aacute;rios, sempre respeitando a exig&ecirc;ncia de ofertar o benef&iacute;cio primeiramente ao trabalhador com menor sal&aacute;rio.<br><br>

As empresas que desejam oferecer o benef&iacute;cio aos seus funcion&aacute;rios j&aacute; podem se habilitar no sistema de credenciamento que estar&aacute; dispon&iacute;vel no site do Minist&eacute;rio da Cultura. Neste momento, a empresa dever&aacute; indicar a operadora que quer trabalhar.<br><br>

S&atilde;o as operadoras que v&atilde;o produzir e distribuir os cart&otilde;es. S&atilde;o elas tamb&eacute;m que habilitar&atilde;o os estabelecimentos que quiserem aceitar o Vale-Cultura. A taxa de administra&ccedil;&atilde;o cobrada pela operadora aos comerciantes ser&aacute; de no m&aacute;ximo 6%.<br><br></div>
                    </div>	
                </div>
            </div>
        </div>
        <!-- end: Content -->

    </div><!--/fluid-row-->


</body>
</html>