<div class="container-fluid-full">
    <div class="row-fluid">

        <!-- start: Main Menu -->
        <div id="sidebar-left" class="span2">

            <div class="row-fluid actions">

                <input type="text" class="search span12" placeholder="O que deseja buscar?"/>

            </div>
            <?php include_once 'menu.phtml'; ?>
        </div>
        <!-- end: Main Menu -->

        <!-- start: Content -->
        <div id="content" class="span10">


            <div class="row-fluid">

                <div class="span3 smallstat box mobileHalf" ontablet="span6" ondesktop="span3">
                    <!--div class="boxchart-overlay blue">
                        <div class="boxchart">5,6,7,2,0,4,2,4,8,2,3,3,2</div>
                    </div-->
                    <span class="value"><?php echo $this->qtdOperadorasAprovadas; ?></span>
                    <span class="title">Cadastro de Operadoras Aprovados</span>
                </div>
                <div class="span3 smallstat box mobileHalf" ontablet="span6" ondesktop="span3">
                    <!--div class="boxchart-overlay red">
                        <div class="boxchart">5,6,7,2,0,4,2,4,8,2,3,3,2</div>
                    </div-->
                    <span class="value"><?php echo $this->qtdOperadorasReprovadas; ?></span>
                    <span class="title">Cadastro de Operadoras Aprovados</span>
                </div>
            </div>
            <div class="row-fluid"><!--/span-->

            </div>

            <div class="row-fluid"></div>

            <div class="row-fluid">

                <div class="box span12">
                    <div class="box-header">
                        <h2><i class="icon-edit"></i>Gerenciar Empresas Operadoras</h2>
                        <div class="box-icon">

                        </div>
                    </div>
                    <div class="box-content">
                        <fieldset>
                            <div id="conteudo">

                                <form method="post" action="listaOperadora.htm">
                                    <table width="100%" class="table table-striped table-bordered bootstrap-datatable "
                                           style="margin-bottom: 50px; margin-top: 20px;">
                                        <tr>

                                        </tr>

                                        <tr>
                                            <td class="destacar bold centro"><strong>CNPJ</strong></td>
                                            <td class="destacar bold centro"><strong>Nome</strong></td>
                                            <td class="destacar bold centro"><strong>Data de Cadastro</strong></td>
                                            <td class="destacar bold centro"><strong>Situa&ccedil;&atilde;o</strong>
                                            </td>
                                            <td class="destacar bold centro"><strong>Status</strong></td>
                                            <td class="destacar bold centro"><strong>Analisar</strong></td>
                                        </tr>
                                        <?php foreach ($this->operadoras as $op): ?>
                                            <tr>
                                                <td class="centro"><?php echo $op->nrCnpj; ?></td>
                                                <td><?php echo $op->nmFantasia; ?></td>
                                                <td class="centro"><?php echo $op->dtregistro; ?></td>
                                                <td style="color: <?php if ($op->idSituacao == 1) {
                                                    echo '#FF7B00';
                                                } else if ($op->idSituacao == 2) {
                                                    echo '#66B20A';
                                                } else {
                                                    echo '#E00000';
                                                }; ?>;">
                                                    <?php echo $op->dsTipoSituacao; ?>
                                                </td>
                                                <td class="centro"></td>
                                                <td class="centro">
                                                    <a class="btn btn-success"
                                                       href="<?php echo $this->url(array('module' => 'minc', 'controller' => 'admin', 'action' => 'avaliaroperadora', 'operadora' => $op->idOperadora)); ?>">
                                                        <i class="icon-zoom-in "></i>
                                                    </a>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                        <tr>
                                            <td align="center">56.700.718/0001-45</td>
                                            <td>CIELO</td>
                                            <td class="centro">01/03/2013</td>
                                            <td style="color: #66B20A;">Autorizado</td>
                                            <td class="centro">
                                                <select class="select_simples w80">
                                                    <option>Ativo</option>
                                                    <option>Inativo</option>
                                                </select>
                                            </td>
                                            <td class="centro">
                                                <a class="btn btn-success"
                                                   href="<?php echo $this->url(array('module' => 'minc', 'controller' => 'admin', 'action' => 'avaliaroperadora', 'operadora' => '1')); ?>">
                                                    <i class="icon-zoom-in "></i>
                                                </a>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="center">38.217.481/0001-64</td>
                                            <td>REDECARD</td>
                                            <td class="centro">07/03/2013</td>
                                            <td style="color: #E00000;">N&atilde;o Autorizado</td>
                                            <td class="centro"></td>
                                            <td class="centro">
                                                <a class="btn btn-success"
                                                   href="<?php echo $this->url(array('module' => 'minc', 'controller' => 'admin', 'action' => 'avaliaroperadora', 'operadora' => '1')); ?>">
                                                    <i class="icon-zoom-in "></i>
                                                </a>
                                            </td>
                                        </tr>

                                    </table>
                                </form>
                            </div>
                        </fieldset>
                        </form>

                    </div>
                </div>
            </div>
        </div>
        <!-- end: Content -->

    </div><!--/fluid-row-->

</div><!--/.fluid-container-->