<style>
    .descricao{
        min-height: 30px;
        line-height: 30px;
        border-bottom: solid 1px #f3f3f3;
    }
</style>
<div class="container-fluid-full">
    <div class="row-fluid">

        <!-- start: Main Menu -->
        <div id="sidebar-left" class="span2">

            <div class="row-fluid actions">

                <input type="text" class="search span12" placeholder="O que deseja buscar?" />

            </div>	
            <?php include_once 'menu.phtml'; ?>
        </div>
        <!-- end: Main Menu -->

        <!-- start: Content -->
        <div id="content" class="span10">



            <div class="row-fluid"><!--/span-->

            </div>

            <div class="row-fluid"></div>	

            <div class="row-fluid">

                <div class="box span12">
                    <div class="box-header">
                        <h2><i class="icon-edit"></i>Respons&aacute;veis pela Empresa</h2>
                        <div class="box-icon">

                        </div>
                    </div>
                    <div class="box-content">
                        <fieldset>
                            
                            <table class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>Nome:</th>
                                        <th width="130">CPF:</th>
                                        <th>Cargo:</th>
                                        <th width="250">Emails:</th>
                                        <th width="140">Telefones:</th>
                                        <th width="130">&nbsp;</th>
                                        <th width="100">&nbsp;</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach($this->responsaveis as $resp):?>
                                    <tr>
                                        <td><?php echo $resp['nmResponsavel']; ?></td>
                                        <td><?php echo $resp['nrCpfResponsavel']; ?></td>
                                        <td><?php echo $resp['cargoResponsavel']; ?></td>
                                        <td>
                                            <?php foreach($resp['emailsResponsavel'] as $em):?>
                                            <div class="descricao"><?php echo $em['dsEmail']; ?></div>
                                            <?php endforeach; ?>
                                        </td>
                                        <td>
                                            <?php foreach($resp['telefonesResponsavel'] as $tel):?>
                                            <?php if ($tel['idTipoTelefone'] == 2): ?>
                                            <div class="descricao"><?php echo $tel['TelResponsavel']; ?></div>
                                            <?php elseif ($tel['idTipoTelefone'] == 4): ?>
                                            <div class="descricao"><?php echo $tel['FaxResponsavel']; ?></div>
                                            <?php endif; ?>
                                            <?php endforeach; ?>
                                        </td>
                                        <td valig="center">
                                            <?php if ($resp['stAtivo'] == 'A'): ?>
                                                <?php if ($this->qtdAtivos > 1): ?>
                                                <a href="<?php echo $this->url(array('module' => 'beneficiaria', 'controller' => 'index', 'action' => 'ativacao-responsavel', 'id' => $resp['idResponsavel'], 'ativar' => 'N'), '', true);?>" style="width: 100px;" class="btn btn-danger">Desativar</a>
                                                <?php endif; ?>
                                            <?php else: ?>
                                            <a href="<?php echo $this->url(array('module' => 'beneficiaria', 'controller' => 'index', 'action' => 'ativacao-responsavel', 'id' => $resp['idResponsavel'], 'ativar' => 'S'), '', true);?>" style="width: 100px;" class="btn btn-success">Ativar</a>
                                            <?php endif; ?>
                                        </td>
                                        <td valig="center">
                                            <a href="<?php echo $this->url(array('module' => 'beneficiaria', 'controller' => 'index', 'action' => 'editar-responsavel', 'id' => $resp['idResponsavel']), '', true);?>" style="width: 70px;" class="btn btn-success">Editar</a>
                                        </td>
                                    </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                            
                            <div class="form-actions">
                                <a href="<?php echo $this->url(array('module' => 'beneficiaria', 'controller' => 'index', 'action' => 'novo-responsavel'), '', true);?>" class="btn btn-primary">Novo responsável</a>
                            </div>

                            <br clear="all" />
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end: Content -->

</div><!--/fluid-row-->
<div class="clearfix"></div>
<br>

</div>

<script>
    jQuery(document).ready(function() {
        
        
            
    });
</script>