<script>
    $(document).ready(function () {
        $('.html').hide();
    });
</script>
<?php

echo $this->partial('relatorio/relatorio-beneficiarias.phtml', array(
    'admin' => $this->admin,
    'cnpj' => $this->cnpj,
    'nome' => $this->nome,
    'situacao' => $this->situacao,
    'regiao' => $this->regiao,
    'uf' => $this->uf,
    'municipio' => $this->municipio,
    'operadora' => $this->operadora,
    'dtInicio' => $this->dtInicio,
    'dtFim' => $this->dtFim,
    'beneficiarias' => $this->beneficiarias,
    'qtdFuncionarios' => $this->qtdFuncionarios,
    'situacoes' => $this->situacoes,
    'ufs' => $this->ufs,
    'regioes' => $this->regioes,
    'operadorasAtivas' => $this->operadorasAtivas,
    'qtdBeneficiarias' => $this->qtdBeneficiarias,
    'pagina' => $this->pagina,
    'detalhamentoDeBeneficiariasExelUrl' => $this->detalhamentoDeBeneficiariasExelUrl,
    'tituloRelatorio' => 'Relatório de Detalhamento de Empresas Beneficiárias',
));
?>
