
<div class="pagination pagination-centered">
    <ul>
        <?php if (isset($this->previous)): ?>
            <li>
                <a class="enviar" title="Primeira Página" href="#">&laquo; Primeira</a>
            </li>
        <?php else: ?>
            <li class="active">
                <a class="enviar" title="Primeira Página" href="#">&laquo; Primeira</a>
            </li>
        <?php endif; ?>

        <?php if (isset($this->previous)): ?>
            <li>
                <a class="enviar" title="Página Anterior" valor="<?php echo $this->previous; ?>" href="#">&laquo; Anterior</a>
            </li>
        <?php else: ?>
            <li class="active">
                <a class="enviar" title="Página Anterior" valor="<?php echo $this->previous; ?>" href="#">&laquo; Anterior</a>
            </li>
        <?php endif; ?>
        <!-- Links numerados -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li>
                    <a class="enviar" title="<?php echo $page; ?>" valor="<?php echo $page; ?>" href="#"><?php echo $page; ?></a>
                </li>
            <?php else: ?>
                <li class="active">
                    <a class="enviar" title="<?php echo $page; ?>" valor="<?php echo $page; ?>" href="#"><?php echo $page; ?></a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
        <!-- Fim links numerados -->    
        <?php if (isset($this->next)): ?>
            <li>
                <a class="enviar" title="Próxima Página" valor="<?php echo $this->next; ?>" href="#">Próxima &raquo;</a>
            </li>
        <?php else: ?>
            <li class="active">
                <a class="enviar" title="Próxima Página" valor="<?php echo $this->next; ?>" href="#">Próxima &raquo;</a>
            </li>
        <?php endif; ?>
        <?php if (isset($this->next)): ?>
            <li>
                <a class="enviar" title="Última Página" valor="<?php echo $this->last; ?>" href="#">Última &raquo;</a>
            </li>
        <?php else: ?>
            <li class="active">
                <a class="enviar" title="Última Página" valor="<?php echo $this->last; ?>" href="#">Última &raquo;</a>
            </li>
        <?php endif; ?>
    </ul>
</div>  