<table class="table table-bordered table-striped">
    <tr>
        <th>Tipo de Faixa</th>
        <th width="30" style="text-align: center;">QTD</th>
    </tr>
    <?php foreach($this->faixas as $f):?>
    <tr>
        <td><?php echo $f['dsTipoFaixaSalarial']; ?></td>
        <td width="30" style="text-align: center;"><?php echo $f['qtTrabalhadorFaixaSalarial']; ?></td>
    </tr>
    <?php endforeach; ?>
</table>