<div class="container-fluid-full">
    <div class="row-fluid">

        <!-- start: Main Menu -->
        <div id="sidebar-left" class="span2">

            <div class="row-fluid actions">

                <input type="text" class="search span12" placeholder="O que deseja buscar?" />

            </div>	
            <?php include_once 'menu.phtml'; ?>
        </div>
        <!-- end: Main Menu -->

        <!-- start: Content -->
        <div id="content" class="span10">

            <div class="row-fluid"><!--/span-->

            </div>

            <div class="row-fluid"></div>	

            <div class="row-fluid">

                <div class="box span12">
                    <div class="box-header">
                        <h2><i class="icon-edit"></i>Consultar Empresas Beneficiárias</h2>
                        <div class="box-icon">

                        </div>
                    </div>
                    <div class="box-content">
                        <fieldset>
                            <form id="form" action="<?php echo $this->url(array('module' => 'operadora', 'controller' => 'index', 'action' => 'consultar-beneficiarias')); ?>" method="POST" >
                                <table class="table table-striped table-bordered bootstrap-datatable ">
                                    <tr>
                                        <td>
                                            CNPJ
                                        </td>
                                        <td>
                                            Nome
                                        </td>
                                        <td>
                                            Status
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <input type="text" name="CNPJ" id="CNPJ" value="<?php echo $this->cnpj ?>" class="input_simples w200 cnpj" />
                                        </td>
                                        <td>
                                            <input name="NOME" type="text" value="<?php echo $this->nome ?>" />
                                        </td>
                                        <td>
                                            <select name="SITUACAO">
                                                <option value="0">- SELECIONE -</option>
                                                <?php foreach ($this->situacoes as $situacao): ?>
                                                    <option value="<?php echo $situacao['ID_TIPO_SITUACAO'] ?>" <?php echo $situacao['ID_TIPO_SITUACAO'] == $this->situacao ? "selected" : '' ?>>
                                                        <?php echo $situacao['DS_TIPO_SITUACAO']; ?>
                                                    </option>
                                                <?php endforeach; ?>
                                            </select>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Data de Cadastro (Mínima)
                                        </td>
                                        <td colspan="2">
                                            Data de Cadastro (Máxima)
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <input type="text" name="DTINICIO" id="DTINICIO" value="<?php echo $this->dtInicio ?>" class="data" />
                                        </td>
                                        <td colspan="2">
                                            <input type="text" name="DTFIM" id="DTFIM" value="<?php echo $this->dtFim ?>" class="data" />
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="3">
                                            <input type="radio" <?php echo $this->filtro == 0 ? 'checked' : ''; ?> name="filtra" value="0" style="margin: 0px;" >Todas beneficiárias<Br>
                                            <input type="radio" <?php echo $this->filtro == 1 ? 'checked' : ''; ?> name="filtra" value="1" style="margin: 0px;" >Beneficiárias que optaram por esta operadora<br>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="3">
                                            <button class="btn btn-primary aprovar">Filtrar</button>
                                            <button class="btn btn-primary excel">Gerar Planilha</button>
                                        </td>
                                    </tr>
                                </table>
                            </form>


                            <?php if (count($this->beneficiarias) > 0): ?>
                                    <table class="table table-striped table-bordered bootstrap-datatable ">
                                <?php foreach ($this->beneficiarias as $b): ?>
                                        <tr>
                                            <td class="destacar bold centro" width="40%">
                                                <nobr><b style="font-size: 11pt;"><?php echo $b['nmFantasia']; ?></b></nobr>
                                            </td>
                                            <td width="40%">
                                                <nobr><?php echo $this->mascara($b["nrCnpj"], 'cnpj'); ?></nobr>
                                            </td>
                                            <td width="20%" style="color: <?php echo $this->verificarSituacao($b['situacao'], 'cor'); ?> ">
                                                <nobr><?php echo $this->verificarSituacao($b['situacao']); ?></nobr>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="destacar bold centro"><strong style="color:#666">Razão Social:</strong> <nobr><?php echo $b['nmRazaoSocial']; ?></nobr></td>
                                            <td class="destacar bold centro"><strong style="color:#666">Cadastrada em:</strong> <nobr><?php echo $b['dtInscricao']; ?></nobr></td>
                                            <td class="destacar bold centro"><strong style="color:#666">Operadora:</strong> <nobr><?php echo $b["nmOperadora"] ?></nobr></td>                   
                                        </tr>
                                        <?php foreach($b['responsaveis'] as $r):?>
                                            <tr>
                                                <th>Responsável: </th>
                                                <th>E-mails:</th>
                                                <th>Telefones:</th>
                                            </tr>
                                            <tr>
                                                <td><?php echo $r['nmPessoaFisica']; ?></td>
                                                <td>
                                                    <?php foreach($r['emailsResponsavel'] as $e):?>
                                                    <div><?php echo $e['emailResponsavel']; ?></div>
                                                    <?php endforeach; ?>
                                                </td>
                                                <td>
                                                    <?php foreach($r['telefonesResponsavel'] as $t):?>
                                                    <div><?php echo $t['telResponsavel']; ?></div>
                                                    <?php endforeach; ?>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                        <tr>
                                            <td>
                                                <strong style="color:#666">Quantidade de funcionários: </strong>
                                                <nobr><?php echo $b['qtdFuncionarios']; ?></nobr>
                                            </td>
                                            <td colspan="2">
                                                <a href="#modalFaixasAjax" nmBeneficiaria="<?php echo $b['nmRazaoSocial']; ?>" idBeneficiaria="<?php echo $b['idBeneficiaria']; ?>" role="button" class="btn btn-info modalFaixas" data-toggle="modal">Visualizar faixas salariais dos funcionários</a>
                                            </td>
                                        </tr>
                                        <tr style="background-color:#ccc">
                                            <td colspan="3"> </td>
                                        </tr>
                                <?php endforeach; ?>
                                    </table>
                            <?php else: ?>
                                    <table width="100%" class="table table-striped table-bordered bootstrap-datatable ">
                                        <tr>
                                            <td colspan='6' align='center'>
                                                <b>Nenhuma beneficiária localizada</b>  
                                            </td>
                                        </tr>
                                    </table>
                            <?php endif; ?>
                            <?php echo $this->paginationControl($this->beneficiarias, 'Sliding', 'paginador.phtml'); ?>
                            <b class="alarm"> *Apenas beneficiárias que autorizaram divulgar as informações </b>
                            </fieldset>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- end: Content -->

    </div><!--/fluid-row-->

</div><!--/.fluid-container-->

<div id="modalFaixasAjax" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="modalFaixasLabel" aria-hidden="true">
    <div class="modal-header">
        <h3 id="myModalLabel">Faixas Salariais</h3>
    </div>
    <div class="modal-body">
        <p id="corpoFaixasSalariais"></p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Fechar</button>
    </div>
</div>

<script>
    function exibe(obj) {
        
        $('.dadosResponsavel').fadeOut('fast', function() {
            $('#dados_' + obj).fadeIn('slow');
        });
        
    }

    jQuery(document).ready(function() {
        $(".data").mask("99/99/9999");
        $(".cnpj").mask("99.999.999/9999-99");

        $('.modalFaixas').click(function(){
            var idBeneficiaria = $(this).attr('idBeneficiaria');
            var nmBeneficiaria = $(this).attr('nmBeneficiaria');
            $('#corpoFaixasSalariais').load('<?php echo $this->url(array('module' => 'operadora', 'controller' => 'index', 'action' => 'buscar-faixas-salariais')); ?>/idBeneficiaria/'+idBeneficiaria);
        });
        $('.excel').click(function() {
            $('#form').attr('action','<?php echo $this->url(array('module' => 'operadora', 'controller' => 'index', 'action' => 'exportar-excel'), '', true); ?>');
            $('#form').attr('target','');
            $('#form').submit();
        });
        $('.aprovar').click(function() {
            $('#form').attr('action','<?php echo $this->url(array('module' => 'operadora', 'controller' => 'index', 'action' => 'consultar-beneficiarias'), '', true); ?>');
            $('#form').attr('target','');
            $('#form').submit();
        });
    });
</script>