<div class="container-fluid-full">
    <div class="row-fluid">

        <!-- start: Main Menu -->
        <div id="sidebar-left" class="span2">

            <div class="row-fluid actions">

                <input type="text" class="search span12" placeholder="O que deseja buscar?"/>

            </div>
            <?php include_once 'menu.phtml'; ?>
        </div>
        <!-- end: Main Menu -->

        <!-- start: Content -->
        <div id="content" class="span10">


            <div class="row-fluid"><!--/span-->

            </div>

            <div class="row-fluid"></div>

            <div class="row-fluid">

                <div class="box span12">
                    <div class="box-header">
                        <h2><i class="icon-edit"></i>Respons&aacute;vel pela Empresa</h2>
                        <div class="box-icon">

                        </div>
                    </div>
                    <div class="box-content">
                        <fieldset>
                            <form method="POST" id="formResponsavel" enctype="multipart/form-data"
                                  action="<?php echo $this->url(array('module' => 'operadora', 'controller' => 'index', 'action' => 'atualizar-dados-responsavel')); ?>">
                                <input type="hidden" name="idResponsavel" id="idResponsavel"
                                       value="<?php echo $this->responsavel['idResponsavel']; ?>"/>
                                <input type="hidden" name="idOperadora" id="idOperadora"
                                       value="<?php echo $this->idOperadora; ?>"/>
                                <table width="100%" class="table table-striped table-bordered bootstrap-datatable ">
                                    <tr>
                                        <td class="destacar bold" width="40%">Responsável:</td>
                                        <td class="destacar bold" width="60%">Cargo:</td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <b><?php echo $this->responsavel['nmResponsavel']; ?></b>
                                            <br/>
                                            CPF: <?php echo $this->responsavel['nrCpfResponsavel']; ?>
                                        </td>
                                        <td>
                                            <select name="CDCBO" id="CDCBO" style="width: 400px;">
                                                <option value="-1"> - SELECIONE -</option>
                                                <?php foreach ($this->CBOs as $CBO): ?>
                                                    <option value="<?php echo $CBO['CD_CBO']; ?>" <?php if ($CBO['CD_CBO'] == $this->responsavel['cdCbo']) {
                                                        echo 'selected="selected"';
                                                    } ?>>
                                                        <?php echo $CBO['NM_CBO']; ?>
                                                    </option>
                                                <?php endforeach; ?>
                                            </select>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="destacar bold">Telefones:</td>
                                        <td class="destacar bold">E-mails:</td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <table class="table table-bordered table-hover" style="margin-bottom: 0px;">
                                                <?php $countTel = count($this->responsavel['telefonesResponsavel']); ?>
                                                <?php foreach ($this->responsavel['telefonesResponsavel'] as $tel): ?>
                                                    <tr>
                                                        <td>
                                                            <?php if ($tel['idTipoTelefone'] == 2): ?>
                                                                <?php echo $tel['TelResponsavel']; ?>
                                                            <?php elseif ($tel['idTipoTelefone'] == 4): ?>
                                                                <?php echo $tel['FaxResponsavel']; ?>
                                                            <?php endif; ?>
                                                        </td>
                                                        <td width="100" style="text-align: center;">
                                                            <?php if ($countTel > 1): ?>
                                                                <button type="button"
                                                                        valor="<?php echo $tel['idTelefone']; ?>"
                                                                        style="width: 90px;"
                                                                        class="btn btn-danger excluirTel">Excluir
                                                                </button>
                                                            <?php endif; ?>
                                                        </td>
                                                    </tr>
                                                <?php endforeach; ?>
                                            </table>
                                        </td>
                                        <td colspan="2">
                                            <table class="table table-bordered table-hover" style="margin-bottom: 0px;">
                                                <?php $countEmail = count($this->responsavel['emailsResponsavel']); ?>
                                                <?php foreach ($this->responsavel['emailsResponsavel'] as $em): ?>
                                                    <tr>
                                                        <td>
                                                            <?php echo $em['dsEmail']; ?>
                                                        </td>
                                                        <td width="100" style="text-align: center;">
                                                            <?php if ($countEmail > 1): ?>
                                                                <button type="button"
                                                                        valor="<?php echo $em['idEmail']; ?>"
                                                                        style="width: 90px;"
                                                                        class="btn btn-danger excluirEmail">Excluir
                                                                </button>
                                                            <?php endif; ?>
                                                        </td>
                                                    </tr>
                                                <?php endforeach; ?>
                                            </table>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            Procuração representante da empresa:
                                            <?php if (null != $this->urlArquivo) : ?>
                                                <a href="<?php echo $this->urlArquivo ?>" style="float: right;"
                                                   target="_blank"><b>baixar o arquivo</b></a>
                                            <?php endif; ?>
                                        </td>
                                        <td>
                                            <input type="file" name="ANEXO_11" id="ANEXO_11"
                                                   class="input_simples arquivosBlock files"/>
                                            <label for="ANEXO_11" id="ERROR_ANEXO_11" class="error"
                                                   style="display: none; margin-top: 2px"></label>
                                        </td>
                                    </tr>
                                </table>
                                <div class="form-actions">
                                    <button type="submit" id="btnAtualizar" class="btn btn-primary">Atualizar</button>
                                    <a href="<?php echo $this->url(array('module' => 'operadora', 'controller' => 'index', 'action' => 'responsavel'), '', true); ?>"
                                       class="btn btn-danger">Voltar</a>
                                </div>
                            </form>

                            <br clear="all"/>
                        </fieldset>
                    </div>
                    <div class="box-header">
                        <h2><i class="icon-edit"></i>Adicionar dados</h2>
                        <div class="box-icon"></div>
                    </div>
                    <div class="box-content">
                        <fieldset>
                            <table width="100%" class="table table-striped table-bordered bootstrap-datatable ">
                                <tr>
                                    <td class="destacar bold" width="40%">Novo telefone:</td>
                                    <td class="destacar bold">Novo e-mail:</td>
                                </tr>
                                <tr>
                                    <td>
                                        <form method="POST" id=""
                                              action="<?php echo $this->url(array('module' => 'operadora', 'controller' => 'index', 'action' => 'add-telefone-responsavel')); ?>">
                                            <input type="hidden" name="idResponsavel"
                                                   value="<?php echo $this->responsavel['idResponsavel']; ?>"/>
                                            <input type="hidden" name="idBeneficiaria"
                                                   value="<?php echo $this->idOperadora; ?>"/>
                                            <table class="table table-bordered table-hover" style="margin-bottom: 0px;">
                                                <tr>
                                                    <td>
                                                        <input type="text" class="input_simples telefone" required
                                                               style="margin-bottom: 0px;" name="TelResponsavel"
                                                               id="TelResponsavel">
                                                    </td>
                                                    <td width="100" style="text-align: center;">
                                                        <button class="btn btn-success" style="width: 90px;">Adicionar
                                                        </button>
                                                    </td>
                                                </tr>
                                            </table>
                                        </form>
                                    </td>
                                    <td>
                                        <form method="POST" id=""
                                              action="<?php echo $this->url(array('module' => 'operadora', 'controller' => 'index', 'action' => 'add-email-responsavel')); ?>">
                                            <input type="hidden" name="idResponsavel"
                                                   value="<?php echo $this->responsavel['idResponsavel']; ?>"/>
                                            <input type="hidden" name="idBeneficiaria"
                                                   value="<?php echo $this->idOperadora; ?>"/>
                                            <table class="table table-bordered table-hover" style="margin-bottom: 0px;">
                                                <tr>
                                                    <td>
                                                        <input type="text" class="input_simples" required
                                                               style="width: 350px; margin-bottom: 0px;"
                                                               name="emailResponsavel" id="emailResponsavel">
                                                    </td>
                                                    <td width="100" style="text-align: center;">
                                                        <button class="btn btn-success" style="width: 90px;">Adicionar
                                                        </button>
                                                    </td>
                                                </tr>
                                            </table>
                                        </form>
                                    </td>
                                </tr>
                            </table>
                            <br clear="all"/>
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end: Content -->

</div><!--/fluid-row-->


<div class="clearfix"></div>
<br>

</div>

<script>
    jQuery(document).ready(function () {

        $(".telefone").mask("(99) 9999-9999?9");

        $('.excluirTel').click(function () {

            var idTelefone = $(this).attr('valor')
            var idResponsavel = $('#idResponsavel').val();
            var idOperadora = $('#idOperadora').val();

            window.location = '<?php echo $this->url(array('module' => 'operadora', 'controller' => 'index', 'action' => 'del-telefone-responsavel'), '', true);?>/idTelefone/' + idTelefone + '/idResponsavel/' + idResponsavel + '/idOperadora/' + idOperadora;

        });

        $('.excluirEmail').click(function () {

            var idEmail = $(this).attr('valor')
            var idResponsavel = $('#idResponsavel').val();
            var idOperadora = $('#idOperadora').val();

            window.location = '<?php echo $this->url(array('module' => 'operadora', 'controller' => 'index', 'action' => 'del-email-responsavel'), '', true);?>/idEmail/' + idEmail + '/idResponsavel/' + idResponsavel + '/idOperadora/' + idOperadora;

        });

    });
</script>