<div class="nav-collapse sidebar-nav">
    <ul class="nav nav-tabs nav-stacked main-menu">
        <li>
            <a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'index', 'action' => 'index'), '', true); ?>">
                <i class="icon-home"></i>
                <span class="hidden-tablet" title="P&aacute;gina Inicial"> P&aacute;gina Inicial</span>
            </a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('module' => 'operadora', 'controller' => 'index', 'action' => 'dadosoperadora'), '', true); ?>">
                <i class="icon-th-list"></i>
                <span class="hidden-tablet"> Dados da Operadora</span>
            </a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('module' => 'operadora', 'controller' => 'index', 'action' => 'telefones'), '', true); ?>">
                <i class="icon-phone"></i>
                <span class="hidden-tablet"> Telefones</span>
            </a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('module' => 'operadora', 'controller' => 'index', 'action' => 'arquivos'), '', true); ?>">
                <i class="icon-folder-open"></i>
                <span class="hidden-tablet"> Arquivos Enviados </span>
            </a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('module' => 'operadora', 'controller' => 'index', 'action' => 'responsavel'), '', true); ?>">
                <i class="icon-user"></i>
                <span class="hidden-tablet"> Respons&aacute;veis </span>
            </a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('module' => 'operadora', 'controller' => 'index', 'action' => 'nao-responsavel'), '', true); ?>">
                <i class="icon-user"></i>
                <span class="hidden-tablet">Não Responsáveis </span>
            </a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('module' => 'operadora', 'controller' => 'index', 'action' => 'emitircertificado'), '', true); ?>">
                <i class="icon-certificate"></i>
                <span class="hidden-tablet">Consultar Certificado</span>
            </a>
        </li>
        <li>
            <a href="<?php echo $this->url(array('module' => 'operadora', 'controller' => 'index', 'action' => 'consultar-beneficiarias'), '', true); ?>">
                <i class="icon-search"></i>
                <span class="hidden-tablet">Consultar Beneficiárias</span>
            </a>
        </li>
        <?php if ($this->admin): ?>
            <li>
                <a href="<?php echo $this->url(array('module' => 'minc', 'controller' => 'admin', 'action' => 'index'), '', true); ?>">
                    <i class="icon-angle-left"></i>
                    <span class="hidden-tablet"> Retornar ao menu administrativo </span>
                </a>
            </li>
        <?php endif; ?>


        <!--li>
            <a class="dropmenu" href="#"><i class="icon-folder-close-alt"></i><span class="hidden-tablet"> MENU USUÁRIO</span> <span class="label">3</span></a>
            <ul>
                <li><a class="submenu" href="#"><i class="icon-hdd"></i><span class="hidden-tablet"> Meus Dados</span></a></li>
                <li><a class="submenu" href="#"><i class="icon-envelope"></i><span class="hidden-tablet"> Mensagens</span></a></li>
                <li><a class="submenu" href="#"><i class="icon-tasks"></i><span class="hidden-tablet"> Ajuda</span></a></li>
            </ul>	
        </li-->
        <li>
            <a href="<?php echo $this->url(array('module' => 'minc', 'controller' => 'login', 'action' => 'logout'), '', true); ?>"><i
                        class="icon-signout"></i><span class="hidden-tablet"> Sair do Sistema</span></a></li>
    </ul>
</div>