<div class="container-fluid-full">
    <div class="row-fluid">

        <!-- start: Main Menu -->
        <div id="sidebar-left" class="span2">

            <div class="row-fluid actions">

                <input type="text" class="search span12" placeholder="O que deseja buscar?" />

            </div>	
            <?php include_once 'menu.phtml'; ?>
        </div>
        <!-- end: Main Menu -->

        <!-- start: Content -->
        <div id="content" class="span10">

            <div class="row-fluid">

                <div class="box span12">
                    <div class="box-header">
                        <h2><i class="icon-edit"></i>Respons&aacute;vel pela Empresa</h2>
                        <div class="box-icon">

                        </div>
                    </div>
                    <div class="box-content">
                        <fieldset>
                            <form method="POST" id="formResponsavel" action="<?php echo $this->url(array('module' => 'operadora', 'controller' => 'index', 'action' => 'salvar-responsavel'));?>" >
                                <input type="hidden" name="idOperadora" id="idOperadora" value="<?php echo $this->idOperadora; ?>" />    
                                <input type="hidden" name="IDPF" id="IDPF" value="0" />
                                <table width="100%" class="table table-striped table-bordered bootstrap-datatable ">
                                    <td width="33%" class="destacar bold">CPF:</td>
                                    <td width="33%" class="destacar bold">Nome:</td>
                                    <td width="33%" class="destacar bold">Cargo:</td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <input type="text" class="input_simples w150" name="RESPONSAVEL_CPF" required id="RESPONSAVEL_CPF">
                                        </td>
                                        <td>
                                            <img src="<?php echo $this->baseUrl('img/ajax-loader_4.gif');?>" id="imgPF" style="display: none;" />
                                            <b><label id="RESPONSAVEL_NOME"></label></b>
                                        </td>
                                        <td>
                                            <select name="CDCBO" id="CDCBO" required>
                                                <option value=""> - SELECIONE - </option>
                                                <?php foreach($this->CBOs as $CBO): ?>
                                                <option value="<?php echo $CBO['CD_CBO']; ?>">
                                                    <?php echo $CBO['NM_CBO']; ?>
                                                </option>
                                                <?php endforeach; ?>
                                            </select>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="destacar bold">E-mail:</td>
                                        <td class="destacar bold" colspan="2">Confirmar E-mail:</td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <input type="text" class="input_simples w150" required name="emailResponsavel" id="emailResponsavel">
                                        </td>
                                        <td colspan="2">
                                            <input type="text" class="input_simples w150" required name="confirmEmailResponsavel" id="confirmEmailResponsavel">
                                            <span id="erroEmail" style="color: red; font-weight: bold;"></span>
                                            <span id="txtErroEmail" style="color: red; font-weight: bold;"></span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="destacar bold">Fone:</td>
                                        <td class="destacar bold" colspan="2">Fax:</td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <input type="text" class="input_simples w150 telefone" required name="TelResponsavel" id="TelResponsavel">
                                        </td>
                                        <td colspan="2">
                                            <input type="text" class="input_simples w150 telefone" name="FaxResponsavel" id="FaxResponsavel">
                                        </td>
                                    </tr>
                                </table>

                                <div class="form-actions">
                                    <button type="submit" id="btnCadastrar" class="btn btn-primary hide">Cadastrar</button>
                                    <a href="<?php echo $this->url(array('module' => 'operadora', 'controller' => 'index', 'action' => 'responsavel'), '', true);?>" class="btn btn-danger">Cancelar</a>
                                </div>
                            </form>

                            <br clear="all" />
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end: Content -->

</div><!--/fluid-row-->


<div class="clearfix"></div>
<br>

</div>

<script>
    jQuery(document).ready(function() {
        
        // Vamos buscar os dados do CNPJ Agora!
        $('#RESPONSAVEL_CPF').focusout(function(){

            $('#IDPF').val('');
            $('#RESPONSAVEL_NOME').html('');
            $('#imgPF').show();
            $('#btnCadastrar').hide();
                            
            var txt = $(this).val();
            var idEmpresa = $('#idOperadora').val();
            
            if(txt == '___.___.___-__'){
                $('#imgPF').hide();
            }else{
                
                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->url(array('module' => 'operadora', 'controller' => 'cadastro', 'action' => 'busca-pessoa-fisica')); ?>',
                    data: {RESPONSAVEL_CPF: $(this).val(), TIPO_VINCULO: 'O', idEmpresa: idEmpresa},
                    dataType: 'json',
                    success: function(data) {
                        
                        if(data.error != ''){
                            $('#RESPONSAVEL_NOME').html(data.error);
                            $('#imgPF').hide();
                            $('#btnCadastrar').hide();
                        }else{
                            // Preenche os dados
                            $('#IDPF').val(data.dados.idpf);
                            $('#RESPONSAVEL_NOME').html(data.dados.nome);
                            $('#RESPONSAVEL_CARGO').focus();
                            $('#imgPF').hide();
                            $('#btnCadastrar').show();
                        }
                        
                    },error: function(data) {
                        $('#RESPONSAVEL_NOME').html(data.error);
                        $('#imgPF').hide();
                        $('#btnCadastrar').hide();
                    }
                });
            }
            
        });
        
        $('#formResponsavel').submit(function(){
            
            var original = $('#emailResponsavel').val();
            var valor = $('#confirmEmailResponsavel').val();
            
            if(valor != original){
                $('#txtErroEmail').html('Email não confere!');
                return false;
            }
            
        });
        
        $(".telefone").mask("(99) 9999-9999?9");
        $("#RESPONSAVEL_CPF").mask("999.999.999-99");
        
    });
</script>