<div class="container-fluid-full">
    <div class="row-fluid">

        <!-- start: Main Menu -->
        <div id="sidebar-left" class="span2">
            <div class="row-fluid actions">
                <input type="text" class="search span12" placeholder="O que deseja buscar?" />
            </div>	
            <?php include_once 'menu.phtml'; ?>
        </div>
        <!-- end: Main Menu -->

        <!-- start: Content -->
        <div id="content" class="span10">
            <div class="row-fluid">

                <div class="box span12">
                    <div class="box-header">
                        <h2><i class="icon-edit"></i>Cadastrar Telefones da Empresa</h2>
                        <div class="box-icon"></div>
                    </div>
                    <div class="box-content">
                        <fieldset>
                            <form method="POST" id="formResponsavel" action="<?php echo $this->url(array('module' => 'operadora', 'controller' => 'index', 'action' => 'add-telefone')); ?>" >
                                <input type="hidden" name="idOperadora" id="idOperadora" value="<?php echo $this->idOperadora; ?>" />    
                                
                                <table width="100%" class="table table-striped table-bordered bootstrap-datatable ">
                                    <tr>
                                        <td width="100" class="destacar bold">DDD:</td>
                                        <td width="300" class="destacar bold">Número:</td>
                                        <td class="destacar bold">Complemento:</td>
                                        <td width="100" class="destacar bold"></td>
                                    </tr>
                                    <tr>
                                        <td><input type="text" id="DDD" name="DDD" class="input-mini" maxlength="2" onkeyup="num(this);" /></td>
                                        <td><input type="text" name="TELEFONE" class="" maxlength="15" onkeyup="num(this);" required /></td>
                                        <td><input type="text" name="COMPLEMENTO" class="" maxlength="50" /></td>
                                        <td style="text-align: center;">
                                            <button type="submit" id="btnAtualizar" class="btn btn-primary">Cadastrar</button>
                                        </td>
                                    </tr>
                                </table>
                            </form>
                            <br clear="all" />
                        </fieldset>
                    </div>
                </div>
            </div>
            
            <div class="row-fluid">
                <div class="box span12">
                    <div class="box-header">
                        <h2><i class="icon-edit"></i>Telefone SAC - Sistema de Atendimento ao Cliente</h2>
                        <div class="box-icon"></div>
                    </div>
                    <div class="box-content">
                        <fieldset>
                                
                            <table width="100%" class="table table-striped table-bordered bootstrap-datatable ">
                                <tr>
                                    <td width="100" class="destacar bold">DDD:</td>
                                    <td width="300" class="destacar bold">Número:</td>
                                    <td class="destacar bold">Complemento:</td>
                                    <td width="100" class="destacar bold"></td>
                                </tr>
                                <?php foreach($this->telefones as $t):?>
                                <tr>
                                    <td class="destacar bold"><?php echo $t['cdDDD'] == 0 ? '' : $t['cdDDD'];?></td>
                                    <td class="destacar bold"><?php echo $t['nrTelefone'];?></td>
                                    <td class="destacar bold"><?php echo $t['dsTelefone'];?></td>
                                    <td class="destacar bold" style="text-align: center;">
                                        <button type="button" onclick="excluirFone('<?php echo $t['idTelefone'];?>');" class="btn btn-danger">Excluir</button>
                                    </td>
                                </tr>
                                <?php endforeach; ?>
                            </table>
                            <br clear="all" />
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- end: Content -->

</div><!--/fluid-row-->


<div class="clearfix"></div>
<br>

</div>

<script>
    
    function num(dom){
            dom.value=dom.value.replace(/\D/g,'');
    }
    
    function excluirFone(id){
        window.location = '<?php echo $this->url(array('module' => 'operadora', 'controller' => 'index', 'action' => 'del-telefone')); ?>/IDTELEFONE/'+id;
    }
    
    jQuery(document).ready(function() {
        
        $('#emailResponsavel').keyup(function(){
            
            var repet = $(this).attr('repet');
            var val = $(this).val();
            
            if(val != repet){
                $('#confirmEmailResponsavel').attr('disabled', false);
            }else{
                $('#confirmEmailResponsavel').attr('disabled', true);
                $('#erroEmail').html('');
            }
            
        });
        
        $('#confirmEmailResponsavel').keyup(function(){
            
            var original = $('#emailResponsavel').val();
            var val = $(this).val();
            
            if(val != original){
                $('#erroEmail').html('*');
            }else{
                $('#erroEmail').html('');
                $('#txtErroEmail').html('');
            }
            
        });
        
        $('#cpfResponsavelNovo').keyup(function(){
            
            var original = $('#cpfResponsavel').val();
            var val = $(this).val();
            
            if(val != original){
                $('#nmResponsavel').val('');
                $('#emailResponsavel').val('');
                $('#TelResponsavel').val('');
                $('#FaxResponsavel').val('');
            }else{
                $('#erroEmail').html('');
            }
            
        });
        
        $('#formResponsavel').submit(function(){
            
            var email = $('#erroEmail').html();
            if(email == '*'){
                $('#txtErroEmail').html('Email não confere!');
                return false;
            }
            
        });
        
        $("#DDD").mask("99");
        $(".telefone").mask("(99) 9999-9999?9");
        $("#cpfResponsavelNovo").mask("999.999.999-99");
        
    });
</script>