<div class="container-fluid-full">
    <div class="row-fluid">

        <!-- start: Main Menu -->
        <div id="sidebar-left" class="span2">

            <div class="row-fluid actions">
                <input type="text" class="search span12" placeholder="O que deseja buscar?" />
            </div>
            
            <?php include_once 'menu.phtml'; ?>
            
        </div>
        <!-- end: Main Menu -->

        <!-- start: Content -->
        <div id="content" class="span10">

            <div class="row-fluid">

                <div class="box span12">
                    <div class="box-header">
                        <h2><i class="icon-edit"></i>Gerenciar Empresas Operadoras</h2>
                        <div class="box-icon">

                        </div>
                    </div>
                    <div class="box-content">
                        <fieldset>
                            <div id="conteudo">
                                <form action="<?php echo $this->url(array('module' => 'minc', 'controller' => 'consulta', 'action' => 'lista-operadora')); ?>" method="POST" >
                                    <table class="table table-striped table-bordered bootstrap-datatable ">
                                        <tr>
                                            <td>CNPJ</td>
                                            <td>Nome</td>
                                            <td>Status</td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <input name="CNPJ" type="text" class="cnpj" value="<?php echo $this->cnpj ?>" />
                                            </td>
                                            <td>
                                                <input name="NOME" type="text" value="<?php echo $this->nome ?>" />
                                            </td>
                                            <td>
                                                <select name="SITUACAO">
                                                    <option value="0">- SELECIONE -</option>
                                                    <?php foreach ($this->situacoes as $situacao): ?>
                                                        <option value="<?php echo $situacao['ID_TIPO_SITUACAO'] ?>" <?php echo $situacao['ID_TIPO_SITUACAO'] == $this->situacao ? "selected" : '' ?>>
                                                            <?php echo $situacao['DS_TIPO_SITUACAO']; ?>
                                                        </option>
                                                    <?php endforeach; ?>
                                                </select>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="1">Data de Cadastro (Minima)</td>
                                            <td colspan="2">Data de Cadastro (Maxima)</td>
                                        </tr>
                                        <tr>
                                            <td colspan="1">
                                                <input type="text" name="DTINICIO" id="DTINICIO" value="<?php echo $this->dtInicio ?>" class="data" />
                                            </td>
                                            <td colspan="2">
                                                <input type="text" name="DTFIM" id="DTFIM" value="<?php echo $this->dtFim ?>" class="data" />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="3">
                                                <button class="btn btn-primary aprovar">Filtrar</button>
                                            </td>
                                        </tr>
                                    </table>
                                </form>
                                <form method="post" action="listaOperadora.htm">
                                    <table width="100%" class="table table-striped table-bordered bootstrap-datatable " style="margin-bottom: 50px; margin-top: 20px;">
                                        <tr>
                                            <td class="destacar bold centro"><strong>CNPJ</strong></td>
                                            <td class="destacar bold centro"><strong>Nome</strong></td>
                                            <td class="destacar bold centro" style="text-align: center;"><strong>Data de Cadastro</strong></td>
                                            <td class="destacar bold centro" style="text-align: center;"><strong>Situa&ccedil;&atilde;o</strong></td>
                                            <td class="destacar bold centro" style="text-align: center;"><strong>Analisar</strong></td>  
                                        </tr>
                                        <?php foreach ($this->operadoras as $op): ?>
                                        <tr>
                                            <td class="centro"><?php echo $this->mascara($op->nrCnpj, 'cnpj'); ?></td>
                                            <td><?php echo ($op->nmFantasia===" ") ? $op->nmRazaoSocial : $op->nmFantasia; ?></td>
                                            <td class="centro" style="text-align: center;"><?php echo $op->dtInscricao; ?></td>
                                            <td style="text-align: center; color: <?php echo $this->verificarSituacao($op->situacao, 'cor', 'O'); ?>">
                                                <?php echo $this->verificarSituacao($op->situacao, 'st', 'O'); ?>
                                            </td>                    
                                            <td class="centro" style="text-align: center;">
                                                <a class="btn btn-success" title="Avaliar" href="<?php echo $this->url(array('module' => 'minc', 'controller' => 'consulta', 'action' => 'avaliar-operadora', 'operadora' => $op->idOperadora)); ?>">
                                                    <i class="icon-zoom-in "></i>  
                                                </a>                           
                                            </td>
                                        </tr>
                                        <?php endforeach; ?>
                                    </table>
                                </form>
                            </div>
                        </fieldset>
                        </form>   

                    </div>
                </div>
            </div>
        </div>
        <!-- end: Content -->

    </div><!--/fluid-row-->

</div><!--/.fluid-container-->
<script>
    $(document).ready(function() {
        $(".cnpj").mask("99.999.999/9999-99");
        $(".data").mask("99/99/9999");
    });
</script>