<div class="container-fluid-full">
    <div class="row-fluid">

        <!-- start: Main Menu -->
        <div id="sidebar-left" class="span2">

            <div class="row-fluid actions">

                <input type="text" class="search span12" placeholder="O que deseja buscar?" />

            </div>	
            <?php include_once 'menu.phtml'; ?>
        </div>
        <!-- end: Main Menu -->

        <!-- start: Content -->
        <div id="content" class="span10">

            <div class="row-fluid">

                <div class="box span12">
                    <div class="box-header">
                        <h2><i class="icon-edit"></i>Gerenciar Empresas Benefici&aacute;rias</h2>
                        <div class="box-icon">

                        </div>
                    </div>
                    <div class="box-content">
                        <fieldset>
                            <div id="conteudo">
                                <form action="<?php echo $this->url(array('module' => 'minc', 'controller' => 'consulta', 'action' => 'lista-beneficiarios')); ?>" method="POST" >
                                    <table class="table table-striped table-bordered bootstrap-datatable ">
                                        <!--tr>
                                            <td colspan="3">
                                                <strong>Filtros</strong>
                                            </td>
                                        </tr-->
                                        <tr>
                                            <td>
                                                CNPJ
                                            </td>
                                            <td>
                                                Nome
                                            </td>
                                            <td>
                                                Status
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <input name="CNPJ" type="text" class="cnpj" value="<?php echo $this->cnpj ?>" />
                                            </td>
                                            <td>
                                                <input name="NOME" type="text" value="<?php echo $this->nome ?>" />
                                            </td>
                                            <td>
                                                <select name="SITUACAO">
                                                    <option value="0">- SELECIONE -</option>
                                                    <?php foreach ($this->situacoes as $situacao): ?>
                                                        <option value="<?php echo $situacao['ID_TIPO_SITUACAO'] ?>" <?php echo $situacao['ID_TIPO_SITUACAO'] == $this->situacao ? "selected" : '' ?>>
                                                            <?php echo $situacao['DS_TIPO_SITUACAO']; ?>
                                                        </option>
                                                    <?php endforeach; ?>
                                                </select>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="1">
                                                Data de Cadastro (Minima)
                                            </td>
                                            <td colspan="2">
                                                Data de Cadastro (Maxima)
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="1">
                                                <input type="text" name="DTINICIO" id="DTINICIO" value="<?php echo $this->dtInicio ?>" class="data" />
                                            </td>
                                            <td colspan="2">
                                                <input type="text" name="DTFIM" id="DTFIM" value="<?php echo $this->dtFim ?>" class="data" />
                                            </td>
                                        </tr>
                                        <tr>
                                            <td colspan="3">
                                                <button class="btn btn-primary aprovar">Filtrar</button>
                                            </td>
                                        </tr>
                                    </table>
                                </form>
                                <form method="post" action="listaOperadora.htm">
                                    <table class="table table-striped table-bordered bootstrap-datatable " style="margin-bottom: 50px; margin-top: 20px;">
                                        <?php if (count($this->beneficiarias) <= 0): ?>
                                            <tr>
                                                <td class="destacar bold centro" colspan="4"><strong>Nenhuma Benefici&aacute;ria localizada!</strong></td>
                                            </tr>
                                        <?php else: ?>
                                            <tr>
                                                <td class="destacar bold centro" width="150px"><strong>CNPJ</strong></td>
                                                <td class="destacar bold centro"><strong>Nome</strong></td>
                                                <td class="destacar bold centro" style="text-align: center;"><strong>Data de Cadastro</strong></td>
                                                <td class="destacar bold centro" style="text-align: center;"><strong>Status</strong></td>
                                                <td class="destacar bold centro" style="text-align: center;"><strong>Visualizar</strong></td>
                                            </tr>
                                            
                                            <?php foreach ($this->beneficiarias as $b): ?>
                                                <tr>
                                                    <td class="centro"><?php echo $this->mascara($b->nrCnpj, 'cnpj'); ?></td>
                                                    <td><?php echo $b->nmFantasia; ?></td>
                                                    <td class="centro" style="text-align: center;"><?php echo $b->dtInscricao; ?></td>
                                                    <td style="text-align: center; color: <?php echo $this->verificarSituacao($b->situacao, 'cor', 'B'); ?>">
                                                        <?php echo $this->verificarSituacao($b->situacao, 'st', 'B'); ?>
                                                    </td> 
                                                    <td class="centro" style="text-align: center;">
                                                        <a class="btn btn-success" href="<?php echo $this->url(array('module' => 'minc', 'controller' => 'consulta', 'action' => 'avaliar-beneficiaria', 'beneficiaria' => $b->idBeneficiaria)); ?>">
                                                            <i class="icon-zoom-in "></i>  
                                                        </a>                           
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                        <?php endif; ?>
                                    </table>
                                </form>
                                <?php echo $this->paginationControl($this->beneficiarias, 'Sliding', 'paginador.phtml'); ?>
                            </div>
                        </fieldset>
                        </form>   

                    </div>
                </div>
            </div>
        </div>
        <!-- end: Content -->

    </div><!--/fluid-row-->

    <div class="modal hide fade" id="myModal">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h3>Settings</h3>
        </div>
        <div class="modal-body">
            <p>Here settings can be configured...</p>
        </div>
        <div class="modal-footer">
            <a href="#" class="btn" data-dismiss="modal">Close</a>
            <a href="#" class="btn btn-primary">Save changes</a>
        </div>
    </div>

    <div class="clearfix"></div>
    <br>

</div><!--/.fluid-container-->
<script>
    $(document).ready(function() {
        $(".cnpj").mask("99.999.999/9999-99");
        $(".data").mask("99/99/9999");
    });
</script>