<div class="container-fluid-full">
    <div class="row-fluid">

        <!-- start: Main Menu -->
        <div id="sidebar-left" class="span2">

            <div class="row-fluid actions">

                <input type="text" class="search span12" placeholder="O que deseja buscar?"/>

            </div>
        </div>
        <!-- end: Main Menu -->

        <!-- start: Content -->
        <div id="content" class="span10">


            <div class="row-fluid"><!--/span-->

            </div>

            <div class="row-fluid"></div>

            <div class="row-fluid">

                <div class="box span12">
                    <div class="box-header">
                        <h2><i class="icon-edit"></i>Alterar Senha</h2>
                        <div class="box-icon">

                        </div>
                    </div>
                    <div class="box-content">
                        <fieldset>
                            <div id="conteudo">
                                <form id="formSenha" method="POST"
                                      action="<?php echo $this->url(array('module' => 'minc', 'controller' => 'index', 'action' => 'alterarsenhaaction'), null, true); ?>">
                                    <table class="table table-striped table-bordered bootstrap-datatable ">
                                        <tr>
                                            <td class="destacar bold">Nova senha:</td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <input type="password" name="NOVA_SENHA" class="input_simples w150">
                                            </td>
                                        </tr>
                                        <tr>
                                            <td class="destacar bold">Confirme a nova senha:</td>
                                        </tr>
                                        <tr>
                                            <td>
                                                <input type="password" name="NOVA_SENHA_CONFIMA"
                                                       class="input_simples w150">
                                            </td>
                                        </tr>
                                    </table>


                                    <div class="form-actions">
                                        <a id="btnAprovar" onclick="$('#formSenha').submit();" class="btn btn-primary">Atualizar</a>
                                    </div>
                                </form>

                                <br clear="all"/>
                            </div>
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
        <!-- end: Content -->

    </div><!--/fluid-row-->


    <div class="clearfix"></div>
    <br>

</div>