<div class="modal hide fade" id="myModal">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>Configura&ccedil;&otilde;es</h3>
    </div>
    <div class="modal-body">
        <p>Aqui ajustes podem ser configurados...</p>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Fechar</a>
        <a href="#" class="btn btn-primary">Salvar altera&ccedil;&otilde;es</a>
    </div>
</div>

<div class="clearfix"></div>

<footer>
    <p>
        <span style="text-align:left;float:left">&copy; 2013 <a href="#" alt="Vale Cultura">Vale Cultura</a></span>
        <span class="hidden-phone" style="text-align:right;float:right">Todos os Direitos Reservados. <a href="#"
                                                                                                         alt="Minist&eacute;rio da Cultura">Minist&eacute;rio da Cultura</a></span>
    </p>

</footer>

</div><!--/.fluid-container-->        </div><!--/.fluid-container-->
</div><!--/.fluid-container-->
</div><!--/.fluid-container-->
</div><!--/.fluid-container-->
</body>
</html>


