<div class="modal hide fade" id="myModal">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>Configura&ccedil;&otilde;es</h3>
    </div>
    <div class="modal-body">
        <p>Aqui ajustes podem ser configurados...</p>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Fechar</a>
        <a href="#" class="btn btn-primary">Salvar altera&ccedil;&otilde;es</a>
    </div>
</div>

<div class="modal hide fade" id="myModalOperadorasInfo">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">X</button>
        <h3 style="text-transform: uppercase;">Informa&ccedil;&otilde;es para o preenchimento dos dados</h3>
    </div>
    <div class="modal-body">
        <div class="nextF">
            <table align="center" border="0" class="tabela" width="95%"
                   background="<?php echo $this->baseUrl('img/benificiario.png') ?>">
                <tr>
                    <td style="text-align: center;">
                        <h2 class="footer-headline">
                            <span>Orienta&ccedil;&atilde;o ao usu&aacute;rio sobre as compet&ecirc;ncias da operadora</span>
                        </h2>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>
                        <p>
                            A operadora &eacute; a empresa respons&aacute;vel por produzir e comercializar o cart&atilde;o
                            vale-cultura. Para se cadastrar no Programa de Cultura do Trabalhador e se tornar uma
                            operadora, a empresa deve possuir:
                        </p>
                        <p>
                        <ul style="font-style: italic; font-weight: bold;">
                            <li>I - Inscri&ccedil;&atilde;o regular no Cadastro Nacional da Pessoa Jur&iacute;dica
                                (CNPJ);
                            </li>
                            <li>II - Qualifica&ccedil;&atilde;o t&eacute;cnica para produzir e comercializar o
                                vale-cultura, observado o
                                disposto no
                                art. 6&#186; da Lei 12.761/2012. (Decreto 8.084/2013, art. 5&#186;, incisos I e II).
                            </li>
                        </ul>
                        </p>
                        <p>
                            A empresa interessada em aderir ao programa dever&aacute; tamb&eacute;m observar os
                            requisitos previstos no <b>art. 3&#186; e 4&#186; da instru&ccedil;&atilde;o normativa n&#186;
                                2/2013</b> (<a
                                    href="http://www.planalto.gov.br/ccivil_03/_Ato2011-2014/2012/Lei/L12761.htm"
                                    target="_blank" style="cursor: pointer; color: #000; font-weight: bold;">acessar</a>), inclusive no que diz respeito
                            ao representante legal da empresa junto ao Minist&eacute;rio da Cidadania, que tratar&aacute;
                            de todos os assuntos relacionados com sua participa&ccedil;&atilde;o no Programa de Cultura
                            do Trabalhador.
                        </p>
                    </td>
                </tr>
            </table>
        </div>

        <div class="nextF">
            <table align="center" border="0" class="tabela" width="95%"
                   background="<?php echo $this->baseUrl('img/benificiario.png') ?>">
                <tr>
                    <td style="text-align: center;">
                        <h2 class="footer-headline">
                            <span>Orienta&ccedil;&atilde;o com as principais informa&ccedil;&otilde;es sobre o Vale-Cultura</span>
                        </h2>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>
                        <p>
                            A empresa operadora, possuidora do Certificado de Inscri&ccedil;&atilde;o no Programa de
                            Cultura do
                            Trabalhador, &eacute;
                            respons&aacute;vel por produzir e comercializar o cart&atilde;o vale-cultura e habilitar as
                            recebedoras ao
                            recebimento do cart&atilde;o vale-cultura.<br/>
                            Tamb&eacute;m s&atilde;o deveres da operadora (<b>art. 6&#186; do Decreto 8.084/2013</b>):
                        </p>
                        <p>
                        <ul style="font-style: italic; font-weight: bold;">
                            <li>I - Observar limites de cobran&ccedil;a de taxa de administra&ccedil;&atilde;o;</li>
                            <li>II - Apresentar ao Minist&eacute;rio da Cultura relat&oacute;rios peri&oacute;dicos
                                relativos a acesso
                                e
                                frui&ccedil;&atilde;o de
                                produtos e servi&ccedil;os culturais;
                            </li>
                            <li>III - Tomar provid&ecirc;ncias para que empresas recebedoras cumpram os deveres
                                previstos no
                                art. 9&#186;,
                                e inabilit&aacute;-las em caso de descumprimento.
                            </li>
                        </ul>
                        </p>
                        <p>
                            Ressaltamos a import&acirc;ncia de atentar &agrave; legisla&ccedil;&atilde;o do programa (<a
                                    href="http://www.planalto.gov.br/ccivil_03/_Ato2011-2014/2013/Decreto/D8084.htm"
                                    target="_blank" style="cursor: pointer; color: #000; font-weight: bold;">acessar</a>), em especial ao <b>art. 12 da Lei 12.761/2012, aos
                                arts. 6&#186;,
                                7&#186; e
                                8&#186; do Decreto
                                8.084/2013
                                e &agrave; Instru&ccedil;&atilde;o Normativa n&#186; 2/2013</b>.
                        </p>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Fechar</a>
    </div>
</div>

<div class="modal hide fade" id="myModalBeneficiariasInfo">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">X</button>
        <h3 style="text-transform: uppercase;">Informa&ccedil;&otilde;es para o preenchimento dos dados</h3>
    </div>
    <div class="modal-body">
        <div class="nextF">
            <table align="center" border="0" class="tabela" width="95%"
                   background="<?php echo $this->baseUrl('img/benificiario.png') ?>">
                <tr>
                    <td style="text-align: center;">
                        <h2 class="footer-headline">
                            <span>Orienta&ccedil;&atilde;o ao usu&aacute;rio sobre as compet&ecirc;ncias da benefici&aacute;ria</span>
                        </h2>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>
                        <p>
                            A benefici&aacute;ria &eacute; a empresa optante pelo Programa de Cultura do Trabalhador,
                            autorizada a
                            distribuir
                            o vale-cultura a seus trabalhadores com v&iacute;nculo empregat&iacute;cio. Para se
                            cadastrar no programa
                            a
                            empresa
                            deve atender aos seguintes requisitos:
                        </p>
                        <p>
                        <ul style="font-style: italic; font-weight: bold;">
                            <li>I - Inscri&ccedil;&atilde;o regular no CNPJ;</li>
                            <li>II - Indica&ccedil;&atilde;o de empresa operadora possuidora de Certificado de Inscri&ccedil;&atilde;o
                                no Programa
                                de
                                Cultura do Trabalhador;
                            </li>
                            <li>III - Indica&ccedil;&atilde;o do n&uacute;mero de trabalhadores com v&iacute;nculo
                                empregat&iacute;cio,
                                conforme a faixa de
                                renda
                                mensal.
                            </li>
                        </ul>
                        </p>
                        <p>
                            Ressaltamos que o respons&aacute;vel pela empresa junto ao Minist&eacute;rio da Cidadania
                            tratar&aacute; de todos
                            os
                            assuntos relacionados com sua participa&ccedil;&atilde;o no Programa de Cultura do
                            Trabalhador, portanto
                            deve ser
                            indicado um representante que possa responder pela empresa.
                        </p>
                    </td>
                </tr>
            </table>
        </div>

        <div class="nextF">
            <table align="center" border="0" class="tabela" width="95%"
                   background="<?php echo $this->baseUrl('img/benificiario.png') ?>">
                <tr>
                    <td style="text-align: center;">
                        <h2 class="footer-headline"><span>Orienta&ccedil;&atilde;o para o campo faixa salarial</span>
                        </h2>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>
                        <p>
                            Informe o n&uacute;mero de funcion&aacute;rios vinculados &agrave; empresa, de acordo com as
                            faixas
                            salarias.
                            Ressaltamos
                            que estagi&aacute;rios n&atilde;o poder&atilde;o ser adicionados, pois n&atilde;o preenchem
                            o requisito necess&aacute;rio
                            exigido pela
                            legisla&ccedil;&atilde;o do Programa de Cultura do Trabalhador – Vale-Cultura.
                        </p>
                    </td>
                </tr>
            </table>
            <table align="center" border="0" class="tabela" width="95%"
                   background="<?php echo $this->baseUrl('img/benificiario.png') ?>">
                <tr>
                    <td style="text-align: center;">
                        <h2 class="footer-headline">
                            <span>Orienta&ccedil;&atilde;o quanto &agrave; escolha da operadora</span>
                        </h2>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>
                        <p>
                            Escolha uma entre as empresas operadoras cadastradas e autorizadas a emitir o cart&atilde;o
                            Vale-Cultura
                            dos seus funcion&aacute;rios.
                        </p>
                        <p>
                            A escolha da operadora, no momento do cadastro, &eacute; uma inten&ccedil;&atilde;o. O
                            empregador &eacute; livre para
                            contratar
                            qualquer uma das operadoras habilitadas no Programa de Cultura do Trabalhador –
                            Vale-Cultura.
                            Ressaltamos que qualquer altera&ccedil;&atilde;o, dever&aacute; ser registrada no sistema do
                            Vale-Cultura e
                            submetida &agrave;
                            an&aacute;lise e aprova&ccedil;&atilde;o do t&eacute;cnico do Minist&eacute;rio da
                            Cidadania.
                        </p>
                    </td>
                </tr>
            </table>
        </div>

        <div class="nextF">
            <table align="center" border="0" class="tabela" width="95%"
                   background="<?php echo $this->baseUrl('img/benificiario.png') ?>">
                <tr>
                    <td style="text-align: center;">
                        <h2 class="footer-headline">
                            <span>Orienta&ccedil;&atilde;o com as principais informa&ccedil;&otilde;es sobre o Vale-Cultura</span>
                        </h2>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>
                        <p>
                            A benefici&aacute;ria &eacute; a empresa optante pelo Programa de Cultura do Trabalhador,
                            autorizada a
                            distribuir
                            o vale-cultura a seus trabalhadores com v&iacute;nculo empregat&iacute;cio.
                        </p>
                        <p>
                            <b>Art. 11. S&atilde;o deveres da empresa benefici&aacute;ria (art. 11 do Decreto
                                8.084/2013)</b>:
                        <ul style="font-style: italic; font-weight: bold;">
                            <li>I - oferecer o vale-cultura nos termos do Cap&iacute;tulo III;</li>
                            <li>II - prestar ao Minist&eacute;rio da Cultura as informa&ccedil;&otilde;es referentes aos
                                usu&aacute;rios,
                                conforme
                                faixa de
                                renda mensal, e mant&ecirc;-las atualizadas;
                            </li>
                            <li>
                                III - divulgar e incentivar o acesso e a frui&ccedil;&atilde;o de produtos e servi&ccedil;os
                                culturais pelos
                                usu&aacute;rios.<br/>
                                Ressaltamos a import&acirc;ncia de atentar &agrave; legisla&ccedil;&atilde;o do programa
                                (<a href="http://www.planalto.gov.br/ccivil_03/_Ato2011-2014/2013/Decreto/D8084.htm"
                                    target="_blank" style="cursor: pointer; color: #000; font-weight: bold;">acessar</a>), em especial ao art. 12 da Lei 12.761/2012, e
                                &agrave; Instru&ccedil;&atilde;o
                                Normativa n&#186;
                                2/2013.
                            </li>
                        </ul>
                        </p>
                    </td>
                </tr>
            </table>
        </div>

        <div class="nextF">
            <table align="center" border="0" class="tabela" width="95%"
                   background="<?php echo $this->baseUrl('img/benificiario.png') ?>">
                <tr>
                    <td style="text-align: center;">
                        <h2 class="footer-headline">
                            <span>Divulga&ccedil;&atilde;o de dados da benefici&aacute;ria</span></h2>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td>
                        <p>
                            A divulga&ccedil;&atilde;o dos dados implica t&atilde;o somente em informar que a benefici&aacute;ria
                            participa ou
                            participou
                            do Programa de Cultura do Trabalhador, para fins de monitoramento e avalia&ccedil;&atilde;o
                            da pol&iacute;tica
                            p&uacute;blica.
                            N&atilde;o ser&atilde;o divulgados dados pessoais ou sigilosos, apenas indica&ccedil;&atilde;o
                            de nome da empresa como
                            participante do programa.
                        </p>
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Fechar</a>
    </div>
</div>

<div class="clearfix"></div>

<footer>
    <p>
        <span style="text-align:left;float:left">&copy; 2013 <a href="#" alt="Vale Cultura">Vale Cultura</a></span>
        <span class="hidden-phone" style="text-align:right;float:right">Todos os Direitos Reservados. <a href="#"
                                                                                                         title="Ministério da Cultura">Minist&eacute;rio da Cultura</a></span>
    </p>

</footer>

</div><!--/.fluid-container-->        </div><!--/.fluid-container-->
</div><!--/.fluid-container-->
</div><!--/.fluid-container-->
</div><!--/.fluid-container-->
</body>
</html>


