<style type="text/css">
    .errorAjax {
        background-color: #e8a4a4;
        border: 2px solid #e06767;
        height: auto;
        font-family: arial;
        font-size: 9pt;
        padding: 5px;
        margin: 0px;
    }

    .tabela th {
        text-align: left;
    }

    .descEmpresa {
        display: none;
    }

    .descEmpresa label {
        cursor: default;
    }

    #msgAjaxPJ {
        display: none;
        color: red;
        cursor: default;
    }

    #msgAjaxPF, #msgAjaxPFEmpresa, #msgAjaxPFNaoEmpresa {
        display: none;
        color: red;
        cursor: default;
    }

    .arquivoTd {
        vertical-align: top;
        border-bottom: 1px solid #ccc;
    }

    .arquivoTdAq {
        padding-left: 30px;
        border-bottom: 1px solid #ccc;
    }

    .action-pass {
        width: 95%;
        margin: 0;
        padding: 0;
        position: absolute;
        top: 500px;
    }
</style>


<div id="passo1" class="nextF">
    <div class="action-pass">
        <button type="button" style="float: right;" class="nextPass btn btn-info" data-val="passo2">Próximo</button>
    </div>
    <table align="center" border="0" class="tabela" width="95%"
           background="<?php echo $this->baseUrl('img/benificiario.png') ?>">
        <tr>
            <td style="text-align: center;">
                <h3 class="footer-headline"><span>Orientação ao usuário sobre as competências da operadora</span>
                </h3>
            </td>
        </tr>
        <tr>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>
                <p>
                    A operadora é a empresa responsável por produzir e comercializar o cartão vale-cultura. Para se
                    cadastrar no Programa de Cultura do Trabalhador e se tornar uma operadora, a empresa deve
                    possuir:
                </p>
                <p>
                <ul style="font-style: italic; font-weight: bold;">
                    <li>I - Inscrição regular no Cadastro Nacional da Pessoa Jurídica (CNPJ);</li>
                    <li>II - Qualificação técnica para produzir e comercializar o vale-cultura, observado o disposto no
                        art. 6º da Lei 12.761/2012. (Decreto 8.084/2013, art. 5º, incisos I e II).
                    </li>
                </ul>
                </p>
                <p>
                    A empresa interessada em aderir ao programa deverá também observar os requisitos previstos no <b>art.
                        3º e 4º da instrução normativa nº 2/2013</b> (colocar link para a legislação), inclusive no que
                    diz
                    respeito ao representante legal da empresa junto ao Ministério da Cidadania, que tratará de todos os
                    assuntos relacionados com sua participação no Programa de Cultura do Trabalhador.
                </p>
            </td>
        </tr>
    </table>
</div>

<div id="passo2" class="nextF" style="display: none;">
    <div class="action-pass">
        <button type="button" style="float: right;" class="nextPass btn btn-info" data-val="conteudo">Ir para
            Formulário
        </button>
        <button type="button" style="float: right; margin-right: 10px !important;" class="nextPass btn btn-info"
                data-val="passo1">Anterior
        </button>
    </div>
    <table align="center" border="0" class="tabela" width="95%"
           background="<?php echo $this->baseUrl('img/benificiario.png') ?>">
        <tr>
            <td style="text-align: center;">
                <h3 class="footer-headline"><span>Orientação com as principais informações sobre o Vale-Cultura</span>
                </h3>
            </td>
        </tr>
        <tr>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>
                <p>
                    A empresa operadora, possuidora do Certificado de Inscrição no Programa de Cultura do Trabalhador, é
                    responsável por produzir e comercializar o cartão vale-cultura e habilitar as recebedoras ao
                    recebimento do cartão vale-cultura.<br/>
                    Também são deveres da operadora (<b>art. 6º do Decreto 8.084/2013</b>):
                </p>
                <p>
                <ul style="font-style: italic; font-weight: bold;">
                    <li>I - Observar limites de cobrança de taxa de administração;</li>
                    <li>II - Apresentar ao Ministério da Cultura relatórios periódicos relativos a acesso e fruição de
                        produtos e serviços culturais;
                    </li>
                    <li>III - Tomar providências para que empresas recebedoras cumpram os deveres previstos no art. 9º,
                        e inabilitá-las em caso de descumprimento.
                    </li>
                </ul>
                </p>
                <p>
                    Ressaltamos a importância de atentar à legislação do programa (incluir link para acesso à
                    legislação), em especial ao <b>art. 12 da Lei 12.761/2012, aos arts. 6º, 7º e 8º do Decreto
                        8.084/2013
                        e à Instrução Normativa nº 2/2013</b>.
                </p>
            </td>
        </tr>
    </table>
</div>
<div id="passo1" class="nextF">
    <div class="action-pass">
        <button type="button" style="float: right;" class="nextPass btn btn-info" data-val="passo2">Próximo</button>
    </div>
    <table align="center" border="0" class="tabela" width="95%"
           background="<?php echo $this->baseUrl('img/benificiario.png') ?>">
        <tr>
            <td style="text-align: center;">
                <h3 class="footer-headline"><span>Orientação ao usuário sobre as competências da operadora</span>
                </h3>
            </td>
        </tr>
        <tr>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>
                <p>
                    A operadora é a empresa responsável por produzir e comercializar o cartão vale-cultura. Para se
                    cadastrar no Programa de Cultura do Trabalhador e se tornar uma operadora, a empresa deve
                    possuir:
                </p>
                <p>
                <ul style="font-style: italic; font-weight: bold;">
                    <li>I - Inscrição regular no Cadastro Nacional da Pessoa Jurídica (CNPJ);</li>
                    <li>II - Qualificação técnica para produzir e comercializar o vale-cultura, observado o disposto no
                        art. 6º da Lei 12.761/2012. (Decreto 8.084/2013, art. 5º, incisos I e II).
                    </li>
                </ul>
                </p>
                <p>
                    A empresa interessada em aderir ao programa deverá também observar os requisitos previstos no <b>art.
                        3º e 4º da instrução normativa nº 2/2013</b> (colocar link para a legislação), inclusive no que
                    diz
                    respeito ao representante legal da empresa junto ao Ministério da Cidadania, que tratará de todos os
                    assuntos relacionados com sua participação no Programa de Cultura do Trabalhador.
                </p>
            </td>
        </tr>
    </table>
</div>

<div id="passo2" class="nextF" style="display: none;">
    <div class="action-pass">
        <button type="button" style="float: right;" class="nextPass btn btn-info" data-val="conteudo">Ir para
            Formulário
        </button>
        <button type="button" style="float: right; margin-right: 10px !important;" class="nextPass btn btn-info"
                data-val="passo1">Anterior
        </button>
    </div>
    <table align="center" border="0" class="tabela" width="95%"
           background="<?php echo $this->baseUrl('img/benificiario.png') ?>">
        <tr>
            <td style="text-align: center;">
                <h3 class="footer-headline"><span>Orientação com as principais informações sobre o Vale-Cultura</span>
                </h3>
            </td>
        </tr>
        <tr>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>
                <p>
                    A empresa operadora, possuidora do Certificado de Inscrição no Programa de Cultura do Trabalhador, é
                    responsável por produzir e comercializar o cartão vale-cultura e habilitar as recebedoras ao
                    recebimento do cartão vale-cultura.<br/>
                    Também são deveres da operadora (<b>art. 6º do Decreto 8.084/2013</b>):
                </p>
                <p>
                <ul style="font-style: italic; font-weight: bold;">
                    <li>I - Observar limites de cobrança de taxa de administração;</li>
                    <li>II - Apresentar ao Ministério da Cultura relatórios periódicos relativos a acesso e fruição de
                        produtos e serviços culturais;
                    </li>
                    <li>III - Tomar providências para que empresas recebedoras cumpram os deveres previstos no art. 9º,
                        e inabilitá-las em caso de descumprimento.
                    </li>
                </ul>
                </p>
                <p>
                    Ressaltamos a importância de atentar à legislação do programa (incluir link para acesso à
                    legislação), em especial ao <b>art. 12 da Lei 12.761/2012, aos arts. 6º, 7º e 8º do Decreto
                        8.084/2013
                        e à Instrução Normativa nº 2/2013</b>.
                </p>
            </td>
        </tr>
    </table>
</div>

<div id="conteudo" class="nextF" style="display: none;">
    <div id="iframe" style="display:none; margin-bottom: -10px;">
        <iframe name="_frameForm" id="_frameForm" style="border: 0px #fff solid; width: 100%; height: 110px;"></iframe>
    </div>
    <form id="cadastroOperadora" enctype="multipart/form-data" target="_frameForm"
          action="<?php echo $this->url(array('module' => 'operadora', 'controller' => 'cadastro', 'action' => 'cadastrar')); ?>"
          method="post">
        <input type="hidden" name="IDPJ" id="IDPJ" value="0"/>
        <input type="hidden" name="IDPF" id="IDPF" value="0"/>
        <input type="hidden" name="ID_NAO_EMPRESA_PF" id="ID_NAO_EMPRESA_PF" value="0"/>
        <input type="hidden" name="ID_ENDERECO" id="ID_ENDERECO" value="0"/>

        <table align="center" border="0" class="tabela" width="95%"
               background="<?php echo $this->baseUrl('img/operadora.png') ?>">
            <tr>
                <td colspan="3" style="text-align: center;">
                    <span style="font-size: 15px; color: red;">
                        Empresário, se deseja oferecer o Vale-Cultura aos seus funcionários,
                        <a onclick="abrirCadastroBeneficiaria();"
                           style="cursor: pointer; color: #000; font-weight: bold;">clique aqui</a> e faça a adesão de sua empresa ao programa.
                    </span>
                </td>
            </tr>
            <tr>
                <td colspan="3" style="text-align: center;">
                    <h3 class="footer-headline">
                        <span>
                            Dados da Empresa Operadora <img class="nextPass" data-val="passo1"
                                                            src="<?php echo $this->baseUrl('img/help-icon.png'); ?>"
                                                            style="width: 25px; height: 25px; cursor: pointer; margin-top: 0;border: 0; padding: 0;"
                                                            title="Informações para o preenchimento dos dados"/>
                        </span>
                    </h3>
                </td>
            </tr>
            <tr>
                <th valign="top" class="destacar bold top-left" colspan="3">CNPJ:</th>
            </tr>
            <tr>
                <td valign="top" width="33%"><input name="EMPRESA_CNPJ" id="EMPRESA_CNPJ" type="text"
                                                    class="input_simples w200 cnpj"/></td>
                <td valign="top" colspan="2">
                    <img src="<?php echo $this->baseUrl('img/ajax-loader_4.gif'); ?>" id="imgPJ"
                         style="display: none;"/>
                    <label id="msgAjaxPJ"></label>
                </td>
            </tr>
            <tr class="descEmpresa">
                <th valign="top" width="33%">Raz&atilde;o Social:</th>
                <th valign="top" width="34%">Nome Fantasia:</th>
                <th valign="top" width="33%">Natureza Juridica:</th>
            </tr>
            <tr class="descEmpresa">
                <td valign="top"><label id="EMPRESA_RAZAOSOCIAL">&nbsp;</label></td>
                <td valign="top"><label id="EMPRESA_NOMEFANTASIA">&nbsp;</label></td>
                <td valign="top"><label id="NATUREZA_JURIDICA">&nbsp;</label></td>
            </tr>
            <tr class="descEmpresa">
                <th valign="top">Atividade Econ&ocirc;mica Principal:</th>
                <th valign="top">Atividades Econ&ocirc;micas Secund&aacute;rias:</th>
                <th valign="top">Situação do CNPJ:</th>
            </tr>
            <tr class="descEmpresa">
                <td valign="top"><label id="CNAE_PRIMARIO">&nbsp;</label></td>
                <td valign="top"><label id="CNAE_SECUNDARIOS">&nbsp;</label></td>
                <td valign="top"><label id="EMPRESA_SITUACAO">&nbsp;</label></td>
            </tr>
            <tr>
                <th colspan="3" valign="top" class="destacar bold">Telefone SAC - Serviço de Atendimento ao Cliente:
                </th>
            </tr>
            <tr>
                <td valign="top" colspan="3">
                    <input type="text" id="SAC_DDD" name="SAC_DDD" class="input-mini" maxlength="2" onkeyup="num(this);"
                           placeholder="DDD"/>
                    <input name="SAC_TELEFONE" id="SAC_TELEFONE" onkeyup="num(this);" maxlength="10" type="text"
                           class="input_simples telefone-simples" style="width: 125px;" placeholder="Número"/>
                    <input name="SAC_COMPLEMENTO" id="SAC_COMPLEMENTO" maxlength="100" type="text" class="input_simples"
                           style="width: 350px;" placeholder="Ex: Regiões Metropolitanas/Capitais/Demais Cidades"/>
                </td>
            </tr>
            <tr>
                <th colspan="2" valign="top" class="destacar bold">E-mail institucional:</th>
            </tr>
            <tr>
                <td valign="top" colspan="2">
                    <input name="INSTITUCIONAL_EMAIL" id="RESPONSAVEL_INSTITUCIONAL" maxlength="80" type="text"
                           class="input_simples w400"/>
                </td>
            </tr>


            <tr>
                <th colspan="2" valign="top" class="destacar bold">Endere&ccedil;o Eletr&ocirc;nico:</th>
            </tr>
            <tr>
                <td valign="top" colspan="2">
                    <input name="DS_SITE" id="DS_SITE" type="text" class="input_simples w400"/>
                </td>
            </tr>


        </table>

        <table align="center" border="0" class="tabela" width="95%">
            <tr>
                <td colspan="3" style="text-align: center;"><h3 class="footer-headline">Endere&ccedil;o comercial</h3>
                </td>
            </tr>
            <tr>
                <th valign="top" class="destacar bold">CEP:</th>
                <td valign="top" colspan="2"><img src="<?php echo $this->baseUrl('img/ajax-loader_4.gif'); ?>"
                                                  id="imgPJ" style="display: none;"/></td>
            </tr>
            <tr>
                <td valign="top">
                    <input name="EMPRESA_CEP" id="EMPRESA_CEP" valor="" onchange="buscaCep(this)" type="text"
                           class="input_simples w500 block cep"/>
                    <label for="EMPRESA_CEP" id="EMPRESA_CEP_VALIDADOR" class="error" style="display: none"></label>
                </td>
                <td align="left" colspan="2">
                    <a href="http://www.buscacep.correios.com.br/" target="_blank" class="btn">Busca CEP</a>
                </td>
            </tr>
            <tr>
                <th valign="top" class="destacar bold">Estado:</th>
                <th valign="top" class="destacar bold">Munic&iacute;pio:</th>
                <th valign="top" class="destacar bold">Bairro:</th>
            </tr>
            <tr>
                <td valign="top">
                    <select name="EMPRESA_UF" id="EMPRESA_UF" disabled="true" class="select_simples w200 block">
                        <option> - Informe o CEP -</option>
                    </select>
                </td>
                <td valign="top">
                    <select name="EMPRESA_MUNICIPIO" id="EMPRESA_MUNICIPIO" disabled="true"
                            class="select_simples w200 block">
                        <option> - Informe o CEP -</option>
                    </select>
                </td>
                <td valign="top">
                    <select name="EMPRESA_BAIRRO" id="EMPRESA_BAIRRO" disabled="true" class="select_simples w200 block">
                        <option> - Informe o CEP -</option>
                    </select>
                </td>
            </tr>
            <tr>
                <th valign="top" class="destacar bold">Endere&ccedil;o:</th>
                <th valign="top" class="destacar bold">Complemento:</th>
                <th valign="top" class="destacar bold">Número:</th>
            </tr>
            <tr>
                <td valign="top">
                    <input name="EMPRESA_ENDERECO" id="EMPRESA_ENDERECO" disabled="true" value="- Informe o CEP -"
                           type="text" class="input_simples w200 block"/>
                </td>
                <td valign="top"><input name="EMPRESA_COMPLEMENTO" id="EMPRESA_COMPLEMENTO" maxlength="100" type="text"
                                        class="input_simples w200 block"/></td>
                <td valign="top"><input name="EMPRESA_NUMERO" id="EMPRESA_NUMERO" maxlength="10" type="text"
                                        class="input_simples w100 block"/></td>
            </tr>

        </table>

        <table width="95%" align="center" class="tabela">
            <tr>
                <td valign="top" colspan="3">
                    <input type="checkbox" name="Confirmo_mais_de_3_anos" id="confirmCheckbox"/>
                    Declaro ter qualifica&ccedil;&atilde;o t&eacute;cnica nos termos do inciso II do Art. 5&ordm; do
                    Decreto n&ordm; 8.084 de 2013 e do Art. 4º da Instrução Normativa nº 02.
                </td>
            </tr>
        </table>

        <table width="95%" border="0" align="center" class="tabela" id="AnexoArquivos">
            <tr>
                <th colspan="3"><h3 class="footer-headline"><span>Arquivos</span></h3></th>
            </tr>
            <tr>
                <td width="45%" colspan="2"><b>Documento:</b></td>
                <td class="w100"><b>Arquivo:</b></td>
            </tr>
            <tr id="arquivo_1">
                <td class="arquivoTd" colspan="2">
                    Inscri&ccedil;&atilde;o regular CNPJ
                    <input type="hidden" value="Inscrição regular CNPJ" name="ANEXO_1_NOME" style="width: 90%"
                           class="input_simples w500 arquivosBlock"/>
                </td>
                <td class="arquivoTdAq">
                    <input type="file" name="ANEXO_1" id="ANEXO_1" class="input_simples arquivosBlock files"/>
                    <label for="ANEXO_1" id="ERROR_ANEXO_1" class="error"
                           style="display: none; margin-top: 2px"></label>
                </td>
            </tr>
            <tr id="arquivo_2">
                <td class="arquivoTd" colspan="2">
                    Contrato Social, estatuto ou regulamento institucional
                    <input type="hidden" value="Contrato Social, estatuto ou regulamento institucional"
                           name="ANEXO_2_NOME" style="width: 90%" class="input_simples w500 arquivosBlock"/>
                </td>
                <td class="arquivoTdAq">
                    <input type="file" name="ANEXO_2" id="ANEXO_2" class="input_simples arquivosBlock files"/>
                    <label for="ANEXO_2" id="ERROR_ANEXO_2" class="error"
                           style="display: none; margin-top: 2px"></label>
                </td>
            </tr>
            <tr id="arquivo_3">
                <td class="arquivoTd" colspan="2">
                    Procura&ccedil;&atilde;o designando representante legal
                    <input type="hidden" value="Procuração designando representante legal" name="ANEXO_3_NOME"
                           style="width: 90%" class="input_simples w500 arquivosBlock"/>
                </td>
                <td class="arquivoTdAq">
                    <input type="file" name="ANEXO_3" id="ANEXO_3" class="input_simples arquivosBlock files"/>
                    <label for="ANEXO_3" id="ERROR_ANEXO_3" class="error"
                           style="display: none; margin-top: 2px"></label>
                </td>
            </tr>
            <tr id="arquivo_4">
                <td class="arquivoTd" colspan="2">
                    Regularidade quanto a Tributos e Contribui&ccedil;&otilde;es Federais &ndash; RFB
                    <input type="hidden" value="Regularidade quanto a Tributos e Contribuições Federais – RFB"
                           name="ANEXO_4_NOME" style="width: 90%" class="input_simples w500 arquivosBlock"/>
                </td>
                <td class="arquivoTdAq">
                    <input type="file" name="ANEXO_4" id="ANEXO_4" class="input_simples arquivosBlock files"/>
                    <label for="ANEXO_4" id="ERROR_ANEXO_4" class="error"
                           style="display: none; margin-top: 2px"></label>
                </td>
            </tr>
            <tr id="arquivo_5">
                <td class="arquivoTd" colspan="2">
                    Regularidade Previdenci&aacute;ria &ndash; Certid&atilde;o Negativa de D&eacute;bito &ndash; CND
                    <input type="hidden" value="Regularidade Previdenciária – Certidão Negativa de Débito – CND"
                           name="ANEXO_5_NOME" style="width: 90%" class="input_simples w500 arquivosBlock"/>
                </td>
                <td class="arquivoTdAq">
                    <input type="file" name="ANEXO_5" id="ANEXO_5" class="input_simples arquivosBlock files"/>
                    <label for="ANEXO_5" id="ERROR_ANEXO_5" class="error"
                           style="display: none; margin-top: 2px"></label>
                </td>
            </tr>
            <tr id="arquivo_6">
                <td class="arquivoTd" colspan="2">
                    Regularidade CADIN &ndash; SISBACEN
                    <input type="hidden" value="Regularidade CADIN – SISBACEN" name="ANEXO_6_NOME" style="width: 90%"
                           class="input_simples w500 arquivosBlock"/>
                </td>
                <td class="arquivoTdAq">
                    <input type="file" name="ANEXO_6" id="ANEXO_6" class="input_simples arquivosBlock files"/>
                    <label for="ANEXO_6" id="ERROR_ANEXO_6" class="error"
                           style="display: none; margin-top: 2px"></label>
                </td>
            </tr>
            <tr id="arquivo_7">
                <td class="arquivoTd" colspan="2">
                    Regularidade no FGTS
                    <input type="hidden" value="Regularidade no FGTS" name="ANEXO_7_NOME" style="width: 90%"
                           class="input_simples w500 arquivosBlock"/>
                </td>
                <td class="arquivoTdAq">
                    <input type="file" name="ANEXO_7" id="ANEXO_7" class="input_simples arquivosBlock files"/>
                    <label for="ANEXO_7" id="ERROR_ANEXO_7" class="error"
                           style="display: none; margin-top: 2px"></label>
                </td>
            </tr>
            <tr id="arquivo_8">
                <td class="arquivoTd" colspan="2">
                    Certid&atilde;o Negativa de D&eacute;bitos Trabalhistas
                    <input type="hidden" value="Certidão Negativa de Débitos Trabalhistas" name="ANEXO_8_NOME"
                           style="width: 90%" class="input_simples w500 arquivosBlock"/>
                </td>
                <td class="arquivoTdAq">
                    <input type="file" name="ANEXO_8" id="ANEXO_8" class="input_simples arquivosBlock files"/>
                    <label for="ANEXO_8" id="ERROR_ANEXO_8" class="error"
                           style="display: none; margin-top: 2px"></label>
                </td>
            </tr>
            <tr id="arquivo_9">
                <td class="arquivoTd" colspan="2">
                    Nome do documento:
                    <input type="text" name="ANEXO_9_NOME" style="width: 90%" maxlength="100"
                           class="input_simples w500 arquivosBlock"/>
                </td>
                <td class="arquivoTdAq">
                    <input type="file" name="ANEXO_9" id="ANEXO_9" class="input_simples arquivosBlock files"/>
                    <label for="ANEXO_9" id="ERROR_ANEXO_9" class="error"
                           style="display: none; margin-top: 2px"></label>
                </td>
            </tr>
            <tr id="arquivo_9">
                <td class="arquivoTd" colspan="2">
                    Nome do documento:
                    <input type="text" name="ANEXO_10_NOME" style="width: 90%" maxlength="100"
                           class="input_simples w500 arquivosBlock"/>
                </td>
                <td class="arquivoTdAq">
                    <input type="file" name="ANEXO_10" id="ANEXO_10" class="input_simples arquivosBlock files"/>
                    <label for="ANEXO_10" id="ERROR_ANEXO_10" class="error"
                           style="display: none; margin-top: 2px"></label>
                </td>
            </tr>
        </table>

        <table width="95%" align="center" class="tabela">
            <tr>
                <th colspan="3"><h3 class="footer-headline"><span>Responsável pelas informações da empresa</span></h3>
                </th>
            </tr>

            <tr>
                <td colspan="3" class="destacar bold">Informe abaixo os dados da pessoa responsável pela inserção das
                    informações da empresa junto ao Ministério da Cultura.
                </td>
            </tr>

            <tr>
                <td colspan="2" class="destacar bold">&nbsp;</td>
            </tr>

            <tr>
                <td colspan="2" class="destacar bold">
                    É o Responsável pelas informações da empresa?
                    <input type="radio" value="1" name="responsavel_empresa" class="responsavel_empresa"
                           checked="checked"/> Sim
                    <input type="radio" value="0" name="responsavel_empresa" class="responsavel_empresa"/> Não
                </td>
        </table>

        <table id="responsavel-nao-empresa" align="center" border="0" class="tabela hide" width="95%">
            <tr>
                <td colspan="3">
                    &nbsp;
                </td>
            </tr>
            <tr>
                <td colspan="3" class="destacar bold">
                    <h4 class="">Dados do não Responsável pela Empresa</h4>
                </td>
            </tr>
            <tr>
                <td colspan="3">
                    <div id="msgAjaxNaoEmpresa" class="errorAjax" style="display:none;"></div>
                </td>
            </tr>
            <tr>
                <td valign="top" class="w100">CPF: <img src="<?php echo $this->baseUrl('img/ajax-loader_4.gif'); ?>"
                                                        id="imgPFNaoEmpresa" style="display: none;"/></td>
                <td valign="top">Nome:</td>
                <td valign="top" class="destacar bold">Cargo:</td>
            </tr>
            <tr>
                <td valign="top"><input name="RESPONSAVEL_NAO_EMPRESA_CPF" id="RESPONSAVEL_NAO_EMPRESA_CPF" type="text"
                                        class="input_simples cpf"/></td>
                <td valign="top"><input disabled="true" name="RESPONSAVEL_NAO_EMPRESA_NOME"
                                        id="RESPONSAVEL_NAO_EMPRESA_NOME" type="text" maxlength="100"
                                        class="input_simples"/></td>
                <td valign="top">
                    <select name="RESPONSAVEL_NAO_EMPRESA_CARGO" id="RESPONSAVEL_NAO_EMPRESA_CARGO">
                        <option> - SELECIONE -</option>
                        <?php
                        foreach ($this->CBOs as $CBO) {
                            ?>
                            <option value="<?php echo $CBO['CD_CBO'] ?>">
                                <?php echo $CBO['NM_CBO'] ?>
                            </option>
                            <?php
                        }
                        ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td valign="top" class="destacar bold">E-mail:</td>
                <td valign="top" class="destacar bold">Fone:</td>
                <td valign="top" class="destacar bold" colspan="2">Fax:</td>
            </tr>
            <tr>
                <td><input name="RESPONSAVEL_NAO_EMPRESA_EMAIL" id="RESPONSAVEL_NAO_EMPRESA_EMAIL" maxlength="80"
                           type="text"
                           class="input_simples w300"/></td>
                <td valign="top"><input name="RESPONSAVEL_NAO_EMPRESA_FONE" id="RESPONSAVEL_NAO_EMPRESA_FONE"
                                        type="text"
                                        class="input_simples w100 telefone"/></td>
                <td valign="top"><input name="RESPONSAVEL_NAO_EMPRESA_FAX" id="RESPONSAVEL_NAO_EMPRESA_FAX" type="text"
                                        class="input_simples w100 telefone" colspan="2"/></td>
            </tr>
            <tr>
                <td valign="top" class="destacar bold">Confirme o E-mail:</td>
                <td colspan="2"></td>
            </tr>
            <tr>
                <td><input name="RESPONSAVEL_NAO_EMPRESA_EMAIL_CONFIRMA" id="RESPONSAVEL_NAO_EMPRESA_EMAIL_CONFIRMA"
                           type="text" maxlength="80" class="input_simples w300"/></td>
                <td colspan="2"></td>
            </tr>
        </table>

        <table id="responsavel-empresa" align="center" border="0" class="tabela" width="95%">
            <tr>
                <td colspan="3">
                    <div id="msgAjax" class="errorAjax" style="display:none;"></div>
                </td>
            </tr>
            <tr>
                <td colspan="3">&nbsp;</td>
            </tr>
            <tr>
                <td colspan="3" class="destacar bold">
                    <h4 class="">Dados do Responsável pela Empresa</h4>
                </td>
            </tr>
            <tr>
                <td valign="top" class="w100">CPF:</td>
                <td valign="top">Nome:</td>
                <td valign="top" class="destacar bold">Cargo:</td>
            </tr>
            <tr>
                <td valign="top"><input name="RESPONSAVEL_CPF" id="RESPONSAVEL_CPF" type="text"
                                        class="input_simples cpf" maxlength="14"/></td>
                <td valign="top"><input disabled="true" name="RESPONSAVEL_NOME" id="RESPONSAVEL_NOME" type="text"
                                        class="input_simples" maxlength="100"/></td>
                <td valign="top">
                    <select name="RESPONSAVEL_CARGO" id="RESPONSAVEL_CARGO">
                        <option> - SELECIONE -</option>
                        <?php
                        foreach ($this->CBOs as $CBO) {
                            ?>
                            <option value="<?php echo $CBO['CD_CBO'] ?>">
                                <?php echo $CBO['NM_CBO'] ?>
                            </option>
                            <?php
                        }
                        ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td valign="top" class="destacar bold">E-mail:</td>
                <td valign="top" class="destacar bold">Fone:</td>
                <td valign="top" class="destacar bold" colspan="2">Fax:</td>
            </tr>
            <tr>
                <td><input name="RESPONSAVEL_EMAIL" id="RESPONSAVEL_EMAIL" type="text" maxlength="80"
                           class="input_simples w300"/></td>
                <td valign="top"><input name="RESPONSAVEL_FONE" id="RESPONSAVEL_FONE" type="text"
                                        class="input_simples w100 telefone"/></td>
                <td valign="top"><input name="RESPONSAVEL_FAX" id="RESPONSAVEL_FAX" type="text"
                                        class="input_simples w100 telefone" colspan="2"/></td>
            </tr>
            <tr>
                <td valign="top" class="destacar bold">Confirme o E-mail:</td>
                <td colspan="2"></td>
            </tr>
            <tr>
                <td><input name="RESPONSAVEL_EMAIL_COMFIRMA" id="RESPONSAVEL_EMAIL_COMFIRMA" type="text"
                           class="input_simples w300" maxlength="80"/></td>
                <td colspan="2"></td>
            </tr>
            <tr id="arquivo_10">
                <td class="arquivoTd" colspan="3">
                    Procuração representante da empresa:
                    <input type="file" name="ANEXO_11" id="ANEXO_11" class="input_simples arquivosBlock files"/>
                    <label for="ANEXO_11" id="ERROR_ANEXO_11" class="error"
                           style="display: none; margin-top: 2px"></label>
                </td>
            </tr>
            <tr>
                <td colspan="3">&nbsp;</td>
            </tr>
        </table>

        <table width="95%" align="center" class="tabela">
            <tr>
                <th><h3 class="footer-headline"><span>Início da comercialização</span></h3></th>
            </tr>
            <tr>
                <th colspan="2" valign="top" class="destacar bold">Data de início da comercialização</th>
            </tr>
            <tr>
                <td valign="top" colspan="2">
                    <input name="INICIO_COMERCIALIZACAO" id="INICIO_COMERCIALIZACAO" type="text"
                           class="input_datsimples w400 data-simples datepickerClass" maxlength="10"/>
                </td>
            </tr>
        </table>

        <table width="95%" align="center" class="tabela">
            <tr>
                <th><h3 class="footer-headline"><span>Veracidade</span></h3></th>
            </tr>
            <tr>
                <td class="destacar bold">Texto de orientação ao usuário sobre as competências da operadora
                    e do seu representante legal em relação ao Vale-Cultura (a ser definido)
                </td>
            </tr>
            <tr>
                <td class="destacar bold">&nbsp;</td>
            </tr>
            <tr>
                <td>
                    <input type="checkbox" name="ConfimaRegras" id="ConfimaRegras" style="float:left"/>
                    <div>&nbsp; Li e estou de acordo com as regras do Programa de Cultura do Trabalhador e confirmo, sob
                        as penas da lei, a veracidade de todas as informações prestadas neste cadastro.
                    </div>
                </td>
            </tr>
            <tr>
                <td>
                    <input type="checkbox" name="ConfimaLei" id="ConfimaLei" style="float:left"/>
                    <div>&nbsp; Confirmo sob pena de lei a veracidade de todas as informa&ccedil;&otilde;es
                        prestadas neste cadastro.
                    </div>

                </td>
            </tr>
            <tr>
                <td>Digite o c&oacute;digo abaixo: <input name="captcha[input]" id="captcha[input]"
                                                          class="input_simples" type="text"></td>
            </tr>
            <tr>
                <td id="captcha" style="height: 80px">

                </td>
            </tr>
        </table>
        <br/>
        <table class="tabela">
            <tr>
                <td class="centro">
                    <button id="btnSalvar" class="btn btn btn-inverse" type="submit" style="float:center;"
                            id="enviaForm">Salvar
                    </button>
                    <button id="btnCancelar" class="btn btn btn-inverse" type="button" style="float:center;"
                            onclick="fechaModal();">Cancelar
                    </button>
                    <button id="btnResetar" class="btn btn btn-inverse" type="reset" style="float:center;">Limpar
                    </button>
                </td>
            </tr>
        </table>
    </form>
    <br clear="all"/>
    <table id="btFechar" style="display:none" class="tabela">
        <tr>
            <!--td class="centro">
                <br><br>
                <button class="btn btn btn-inverse" onclick="parent.fechaModal()" type="submit" style="float:center;" name="submit" value="Submit">Fechar</button>
            </td-->
        </tr>
    </table>

</div>

<script type="text/javascript">

    function num(dom) {
        dom.value = dom.value.replace(/\D/g, '');
    }

    jQuery(document).ready(function () {

        $('.nextPass').click(function () {
            $('.nextF').hide();
            $('#' + $(this).attr('data-val')).show();
        });

        gerarCaptcha();

        $("#SAC_DDD").mask("99");
        $(".telefone").mask("(99) 9999-9999?9");
        $(".telefone-simples").mask("9999-9999?9");
        $(".data-simples").mask("99/99/9999");

        $('#btnResetar').click(function () {
            $('#IDPJ').val('');
            $('#ID_NAO_EMPRESA_PF').val('');
            $('#EMPRESA_RAZAOSOCIAL').html('');
            $('#EMPRESA_NOMEFANTASIA').html('');
            $('#NATUREZA_JURIDICA').html('');
            $('#CNAE_PRIMARIO').html('');
            $('#CNAE_SECUNDARIOS').html('');
            $('#EMPRESA_SITUACAO').html('');
            $('#EMPRESA_COMPLEMENTO').val('');
            $('#EMPRESA_NUMERO').val('');
            $('#EMPRESA_CEP').val('');
            $('#EMPRESA_CEP').attr('valor', '');
            $('#ID_ENDERECO').val('0');

            $('#EMPRESA_UF').html('<option> - Informe o CEP - </option>');
            $('#EMPRESA_MUNICIPIO').html('<option> - Informe o CEP - </option>');
            $('#EMPRESA_BAIRRO').html('<option> - Informe o CEP - </option>');
            $('#EMPRESA_ENDERECO').html('- Informe o CEP -');

            $('#msgAjaxPJ').html('');
            $('#msgAjaxPJ').show();

            $('#msgAjaxPF').html('');
            $('#msgAjaxPF').show();

            $('#msgAjaxPFNaoEmpresa').html('');
            $('#msgAjaxPFNaoEmpresa').show();
        });

        $('.responsavel_empresa').click(function () {
            $('#responsavel-nao-empresa').addClass('hide');

            $("#RESPONSAVEL_NAO_EMPRESA_CPF").rules("remove");
            $("#RESPONSAVEL_NAO_EMPRESA_FONE").rules("remove");
            $("#RESPONSAVEL_NAO_EMPRESA_EMAIL").rules("remove");
            $("#RESPONSAVEL_NAO_EMPRESA_EMAIL_CONFIRMA").rules("remove");

            if ($(this).val() == 0) {
                $('#responsavel-nao-empresa').removeClass('hide');

                $("#RESPONSAVEL_NAO_EMPRESA_CPF").rules("add", {
                    required: true,
                    messages: {
                        required: "Informe o CPF"
                    }
                });

                $("#RESPONSAVEL_NAO_EMPRESA_FONE").rules("add", {
                    required: true,
                    messages: {
                        required: "Campo obrigat&oacute;rio"
                    }
                });

                $("#RESPONSAVEL_NAO_EMPRESA_EMAIL").rules("add", {
                    required: true,
                    email: true,
                    messages: {
                        required: "Informe o E-mail",
                        email: "Digite um e-mail v&aacute;lido"
                    }
                });

                $("#RESPONSAVEL_NAO_EMPRESA_EMAIL_CONFIRMA").rules("add", 'emailnaoempresacheck');
            }
        });

        $('.telefone').focusout(function () {
            var phone, element;
            element = $(this);
            element.unmask();
            phone = element.val().replace(/\D/g, '');
            if (phone.length > 10) {
                element.mask("(99) 99999-999?9");
            } else {
                element.mask("(99) 9999-9999?9");
            }
        }).trigger('focusout');

        $(".data").mask("99/99/9999");
        $(".cpf").mask("999.999.999-99");
        $(".cnpj").mask("99.999.999/9999-99");
        $(".cep").mask("99999-999");

        $("#cadastroOperadora").validate({
            rules: {
                EMPRESA_CNPJ: {
                    required: true
                },
                EMPRESA_CEP: {
                    required: true
                },
                RESPONSAVEL_EMAIL: {
                    required: true, email: true
                },
                RESPONSAVEL_EMAIL_COMFIRMA: 'emailcheck',
                RESPONSAVEL_CPF: {
                    required: true
                },
                captchaForm: {
                    required: true
                },
                RESPONSAVEL_FONE: {
                    required: true
                },
                INICIO_COMERCIALIZACAO: {
                    required: true
                }
            },
            messages: {
                EMPRESA_CNPJ: {
                    required: "Informe o CNPJ"
                },
                EMPRESA_CEP: {
                    required: "Informe o CEP"
                },
                RESPONSAVEL_EMAIL: {
                    required: "Informe o E-mail do respons&aacute;vel",
                    email: "Digite um e-mail v&aacute;lido"
                },
                RESPONSAVEL_CPF: {
                    required: "Informe o CPF"
                },
                captchaForm: {
                    required: "Campo obrigat&oacute;rio"
                },
                RESPONSAVEL_FONE: {
                    required: "Campo obrigat&oacute;rio"
                },
                INICIO_COMERCIALIZACAO: {
                    required: "Informe a data de início da comercialização"
                }
            }
        });

        // $("#INICIO_COMERCIALIZACAO").datepicker({
        //     //format: 'dd/mm/yyyy',
        //     language: 'pt-BR',
        //     separator: ' ',
        //     minDate: new Date(),
        //     dayNames: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
        //     dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S', 'D'],
        //     dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'],
        //     monthNames: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
        //     monthNamesShort: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
        //     nextText: 'Próximo',
        //     prevText: 'Anterior',
        //     dateFormat: 'dd/mm/yy'
        // });

        // Vamos buscar os dados do CNPJ Agora!
        $('#EMPRESA_CNPJ').focusout(function () {

            $('#IDPJ').val('');
            $('#EMPRESA_RAZAOSOCIAL').html('');
            $('#EMPRESA_NOMEFANTASIA').html('');
            $('#NATUREZA_JURIDICA').html('');
            $('#CNAE_PRIMARIO').html('');
            $('#CNAE_SECUNDARIOS').html('');
            $('#EMPRESA_SITUACAO').html('');
            $('#EMPRESA_COMPLEMENTO').val('');
            $('#EMPRESA_NUMERO').val('');
            $('#EMPRESA_CEP').val('');
            $('#EMPRESA_CEP').attr('valor', '');
            $('#ID_ENDERECO').val('0');

//            $('.descEmpresa').hide();
            $('#msgAjaxPJ').html('');
            $('#imgPJ').show();

            var txt = $(this).val();

            if (txt == '__.___.___/____-__') {
                $('#imgPJ').hide();
            } else {

                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->url(array('module' => 'operadora', 'controller' => 'cadastro', 'action' => 'busca-pessoa-juridica')); ?>',
                    data: {EMPRESA_CNPJ: $(this).val(), tipoPJ: 'O'},
                    dataType: 'json',
                    success: function (data) {

                        $('#imgPJ').hide();
                        if (data.error != '') {
                            $('#msgAjaxPJ').html(data.error);
                            $('#msgAjaxPJ').show();
                        } else {
                            // Preenche os dados
                            $('#IDPJ').val(data.dados.idpj);
                            $('#EMPRESA_RAZAOSOCIAL').html(data.dados.razaosocial);
                            if (data.dados.nomefantasia === " ") {
                                $('#EMPRESA_NOMEFANTASIA').html('<input name="EMPRESA_NMFANTASIA" id="EMPRESA_NMFANTASIA" maxlength="100" type="text" class="input_simples w200 block" />');
                            } else {
                                $('#EMPRESA_NOMEFANTASIA').html(data.dados.nomefantasia);
                            }
                            $('#NATUREZA_JURIDICA').html(data.dados.naturezajuridica);
                            $('#CNAE_PRIMARIO').html(data.dados.CNAEPrimario);
                            $('#CNAE_SECUNDARIOS').html(data.dados.CNAESecundarios);
                            $('#EMPRESA_SITUACAO').html(data.dados.situacaocnpj);
                            $('#EMPRESA_COMPLEMENTO').val(data.dados.dscomplementoendereco);
                            $('#EMPRESA_NUMERO').val(data.dados.nrcomplemento);
                            if (data.dados.cep != 'N') {
                                $('#EMPRESA_CEP').val(data.dados.cep);
                                $('#EMPRESA_CEP').attr('valor', data.dados.cep);
                                $('#ID_ENDERECO').val(data.dados.idendereco);
                                $.ajax({
                                    type: "POST",
                                    url: '<?php echo $this->url(array('module' => 'operadora', 'controller' => 'cadastro', 'action' => 'buscaenderecoporcep')); ?>',
                                    data: {CEP: data.dados.cep},
                                    dataType: 'json',
                                    success: function (data) {
                                        carregaEndereco(data);
                                    }
                                });
                                $('#SAC_DDD').focus();
                            }
                            $('.descEmpresa').show();
                        }

                    }, error: function (data) {
                        $('#msgAjaxPJ').html(data.error);
                        $('#msgAjaxPJ').show();
                        $('#imgPJ').hide();
                    }
                });
            }
        });

        // Vamos buscar os dados do CNPJ Agora!
        $('#RESPONSAVEL_NAO_EMPRESA_CPF').focusout(function () {

            $('#ID_NAO_EMPRESA_PF').val('');
            $('#RESPONSAVEL_NAO_EMPRESA_NOME').val('');
            $('#msgAjaxNaoEmpresa').hide();
            $('#imgPFNaoEmpresa').show();

            var txt = $(this).val();

            if (txt == '___.___.___-__') {
                $('#imgPFNaoEmpresa').hide();
            } else {

                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->url(array('module' => 'operadora', 'controller' => 'cadastro', 'action' => 'busca-pessoa-fisica')); ?>',
                    data: {RESPONSAVEL_CPF: $(this).val(), TIPO_VINCULO: 'O'},
                    dataType: 'json',
                    success: function (data) {

                        if (data.error != '') {
                            $('#msgAjaxNaoEmpresa').html(data.error);
                            $('#msgAjaxNaoEmpresa').show();
                            $('#imgPFNaoEmpresa').hide();
                        } else {
                            // Preenche os dados
                            $('#ID_NAO_EMPRESA_PF').val(data.dados.idpf);
                            $('#RESPONSAVEL_NAO_EMPRESA_NOME').val(data.dados.nome);
                            $('#RESPONSAVEL_NAO_EMPRESA_CARGO').focus();
                            $('#imgPFNaoEmpresa').hide();
                        }

                    }, error: function (data) {
                        $('#msgAjaxNaoEmpresa').html(data.error);
                        $('#msgAjaxNaoEmpresa').show();
                        $('#imgPFNaoEmpresa').hide();
                    }
                });
            }
        });


        // Vamos buscar os dados do CNPJ Agora!
        $('#RESPONSAVEL_CPF').focusout(function () {

            $('#IDPF').val('');
            $('#RESPONSAVEL_NOME').val('');
            $('#msgAjax').hide();
            $('#imgPF').show();

            var txt = $(this).val();

            if (txt == '___.___.___-__') {
                $('#imgPF').hide();
            } else {

                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->url(array('module' => 'operadora', 'controller' => 'cadastro', 'action' => 'busca-pessoa-fisica')); ?>',
                    data: {RESPONSAVEL_CPF: $(this).val(), TIPO_VINCULO: 'O'},
                    dataType: 'json',
                    success: function (data) {

                        if (data.error != '') {
                            $('#msgAjax').html(data.error);
                            $('#msgAjax').show();
                            $('#imgPF').hide();
                        } else {
                            // Preenche os dados
                            $('#IDPF').val(data.dados.idpf);
                            $('#RESPONSAVEL_NOME').val(data.dados.nome);
                            $('#RESPONSAVEL_CARGO').focus();
                            $('#imgPF').hide();
                        }

                    }, error: function (data) {
                        $('#msgAjax').html(data.error);
                        $('#msgAjax').show();
                        $('#imgPF').hide();
                    }
                });
            }

        });

        // $(document).find('.files').each(function(){
        //     document.getElementById($(this).attr(id)).addEventListener('change', handleFileSelect, false);
        // });

    });

    jQuery.validator.addMethod('emailcheck', function (value, element) {
        if ($('#RESPONSAVEL_EMAIL_COMFIRMA').val() != $('#RESPONSAVEL_EMAIL').val()) {
            return false;
        }
        return true;
    }, 'Verifique o E-mail');

    jQuery.validator.addMethod('emailnaoempresacheck', function (value, element) {
        if ($('#RESPONSAVEL_NAO_EMPRESA_EMAIL_CONFIRMA').val() != $('#RESPONSAVEL_NAO_EMPRESA_EMAIL').val()) {
            return false;
        }
        return true;
    }, 'Verifique o E-mail');

    function fechaForm() {
        $("#cadastroOperadora").fadeOut();
        $("#btFechar").show();
    }

    function exibeRetorno(top) {
        if (top > 150) {
            top = 150;
        }

        if (top < 80) {
            top = 80;
        }

        $('#_frameForm').css('height', top + 'px');
        $('#iframe').css('display', 'block');
        $('#janelaLoad').animate({scrollTop: 0}, 'slow');
        $('html body').animate({scrollTop: 0}, 'slow');
        gerarCaptcha();
    }

    function buscaCep(obj) {

        valor = $(obj).attr('valor');
        valorAtual = $(obj).val().replace("-", "");

        if ((valor != '') && valor == valorAtual) {
            return false;
        }

        $('#EMPRESA_COMPLEMENTO').val('');
        $('#EMPRESA_NUMERO').val('');

        $.ajax({
            type: "POST",
            url: '<?php echo $this->url(array('module' => 'operadora', 'controller' => 'cadastro', 'action' => 'buscaenderecoporcep')); ?>',
            data: {CEP: $(obj).val()},
            dataType: 'json',
            success: function (data) {
                carregaEndereco(data);
            }
        });
    }

    function gerarCaptcha() {
        $.ajax({
            type: "GET",
            url: '<?php echo $this->url(array('module' => 'operadora', 'controller' => 'cadastro', 'action' => 'gerarcaptcha')); ?>',
            success: function (data) {
                $('#captcha').html(data);
                setTimeout('gerarCaptcha()', 600000);
            }
        });
    }

    function carregaEndereco(data) {
        if (!data.error) {
            $('#EMPRESA_CEP_VALIDADOR').fadeOut();
            if (data.dados.TPCEP != 0) {
                if (data.dados.NM_LOGRADOURO.length > 0) {
                    $('#EMPRESA_ENDERECO').val(data.dados.DS_TIPO_LOGRADOURO + ' ' + data.dados.NM_LOGRADOURO);
                    if (data.dados.DS_TIPO_LOGRADOURO !== 'M' && data.dados.DS_TIPO_LOGRADOURO !== 'D' && data.dados.DS_TIPO_LOGRADOURO !== 'P') {
                        $('#EMPRESA_ENDERECO').attr('disabled', 'true');
                    } else {
                        $('#EMPRESA_ENDERECO').val('');
                        $('#EMPRESA_ENDERECO').removeAttr('disabled');
                    }
                }
                if (data.dados.DS_COMPLEMENTO.length > 2) {
                    $('#EMPRESA_COMPLEMENTO').val(data.dados.DS_COMPLEMENTO);
                    $('#EMPRESA_COMPLEMENTO').attr('disabled', 'true');
                }

                $('#EMPRESA_BAIRRO').html('');

                for (var i = 0; i < data.dados.bairros.length; i++) {
                    var complemento = '';
                    if (i == 0) {
                        complemento = 'selected';
                    }
                    var option = "<option value='" + data.dados.bairros[i].ID_BAIRRO + "' " + complemento + ">" + data.dados.bairros[i].NM_BAIRRO + "</option>";
                    $('#EMPRESA_BAIRRO').append(option);
                }
                if (data.dados.bairros.length > 1) {
                    $('#EMPRESA_BAIRRO').removeAttr('disabled');
                } else {
                    $('#EMPRESA_BAIRRO').attr('disabled', 'true');
                }

                $('#EMPRESA_UF').html('');
                var option = "<option value='" + data.dados.SG_UF + "' selected >" + data.dados.NM_UF + "</option>";
                $('#EMPRESA_UF').append(option);
                $('#EMPRESA_UF').attr('disabled', 'true');

                $('#EMPRESA_MUNICIPIO').html('');
                var option = "<option value='" + data.dados.ID_MUNICIPIO + "' selected >" + data.dados.NM_MUNICIPIO + "</option>";
                $('#EMPRESA_MUNICIPIO').append(option);
                $('#EMPRESA_MUNICIPIO').attr('disabled', 'true');

            } else {
                //libera campos para preenchimento
                $('#EMPRESA_BAIRRO').removeAttr('disabled');
                $('#EMPRESA_ENDERECO').removeAttr('disabled');
            }
        } else {
            //CEP INVALIDO
            $('#EMPRESA_CEP_VALIDADOR').html('CEP inv&aacute;lido');
            $('#EMPRESA_CEP_VALIDADOR').fadeIn();

            var option = "<option> - Informe o CEP - </option>";
            $('#EMPRESA_BAIRRO').html(option);
            $('#EMPRESA_UF').html(option);
            $('#EMPRESA_MUNICIPIO').html(option);

            $('#EMPRESA_ENDERECO').val('');
            $('#EMPRESA_COMPLEMENTO').val('');
        }
    }

    //Verificando os arquivos em anexo

    // Check for the various File API support.
    if (window.File && window.FileReader && window.FileList && window.Blob) {
        // Great success! All the File APIs are supported.
    } else {
        alert('The File APIs are not fully supported in this browser.');
    }

    function handleFileSelect(evt) {
        //alert(123);
        var files = evt.target.files; // FileList object

        // files is a FileList of File objects. List some properties.
        var output = [];
        for (var i = 0, f; f = files[i]; i++) {
            if (f.type !== 'application/pdf') {
                $('#ERROR_' + $(evt.currentTarget).attr('id')).html("Apenas aquivos no formato PDF são validos");
                $('#ERROR_' + $(evt.currentTarget).attr('id')).show();
            }

            if (f.size >= 5242880) {
                $('#ERROR_' + $(evt.currentTarget).attr('id')).html("Tamanho maximo do arquivo deve ser de 5mb");
                $('#ERROR_' + $(evt.currentTarget).attr('id')).show();
            }
            if (f.size < 5242880 && f.type === 'application/pdf') {
                $('#ERROR_' + $(evt.currentTarget).attr('id')).hide();
            }

        }

    }

    document.getElementById('ANEXO_1').addEventListener('change', handleFileSelect, false);
    document.getElementById('ANEXO_2').addEventListener('change', handleFileSelect, false);
    document.getElementById('ANEXO_3').addEventListener('change', handleFileSelect, false);
    document.getElementById('ANEXO_4').addEventListener('change', handleFileSelect, false);
    document.getElementById('ANEXO_5').addEventListener('change', handleFileSelect, false);
    document.getElementById('ANEXO_6').addEventListener('change', handleFileSelect, false);
    document.getElementById('ANEXO_7').addEventListener('change', handleFileSelect, false);
    document.getElementById('ANEXO_8').addEventListener('change', handleFileSelect, false);
    document.getElementById('ANEXO_9').addEventListener('change', handleFileSelect, false);
    document.getElementById('ANEXO_10').addEventListener('change', handleFileSelect, false);
    document.getElementById('ANEXO_11').addEventListener('change', handleFileSelect, false);


    function print_r(arr) {
        var text = (text ? text : "Array \n("), tab = (tab ? tab : "\t");

        for (key in arr) {
            if (typeof arr[key] == "object")
                text = print_r(arr[key], text + "\n" + tab + "[" + key + "] => Array \n" + tab + "(", "\t" + tab);
            else
                text += "\n" + tab + "[" + key + "] => " + arr[key];

            text += "\n" + (tab.substr(0, tab.length - 1)) + ")\n";
        }
        return text;

    }


    function bloqueaCadastro() {
        // Dados da empresa
        $('#EMPRESA_TIPO_LUCRO').attr('disabled', true);
        $('#EMPRESA_OPERADORA').attr('disabled', true);
        $('#EMPRESA_CEP').attr('disabled', true);
        $('#EMPRESA_COMPLEMENTO').attr('disabled', true);
        $('#EMPRESA_NUMERO').attr('disabled', true);
        // Quantidades de funcionarios
        $('.nrFuncionarios').attr('disabled', true);
        // Dados do Responsavel
        $('#RESPONSAVEL_CPF').attr('disabled', true);
        $('#RESPONSAVEL_CARGO').attr('disabled', true);
        $('#RESPONSAVEL_EMAIL').attr('disabled', true);
        $('#RESPONSAVEL_FONE').attr('disabled', true);
        $('#RESPONSAVEL_FAX').attr('disabled', true);
        $('#RESPONSAVEL_EMAIL_COMFIRMA').attr('disabled', true);

        $('#RESPONSAVEL_NAO_EMPRESA_CPF').attr('disabled', true);
        $('#RESPONSAVEL_NAO_EMPRESA_CARGO').attr('disabled', true);
        $('#RESPONSAVEL_NAO_EMPRESA_EMAIL').attr('disabled', true);
        $('#RESPONSAVEL_NAO_EMPRESA_FAX').attr('disabled', true);
        $('#RESPONSAVEL_NAO_EMPRESA_FONE').attr('disabled', true);
        $('#RESPONSAVEL_NAO_EMPRESA_EMAIL_CONFIRMA').attr('disabled', true);

        // Botão de Salvar
        $('#btnSalvar').hide();
    }

    function desbloqueaCadastro() {
        // Dados da empresa
        $('#EMPRESA_TIPO_LUCRO').attr('disabled', false);
        $('#EMPRESA_OPERADORA').attr('disabled', false);
        $('#EMPRESA_CEP').attr('disabled', false);
        $('#EMPRESA_COMPLEMENTO').attr('disabled', false);
        $('#EMPRESA_NUMERO').attr('disabled', false);
        // Quantidades de funcionarios
        $('.nrFuncionarios').attr('disabled', false);
        // Dados do Responsavel
        $('#RESPONSAVEL_CPF').attr('disabled', false);
        $('#RESPONSAVEL_CARGO').attr('disabled', false);
        $('#RESPONSAVEL_EMAIL').attr('disabled', false);
        $('#RESPONSAVEL_FONE').attr('disabled', false);
        $('#RESPONSAVEL_FAX').attr('disabled', false);
        $('#RESPONSAVEL_EMAIL_COMFIRMA').attr('disabled', false);

        $('#RESPONSAVEL_NAO_EMPRESA_CPF').attr('disabled', false);
        $('#RESPONSAVEL_NAO_EMPRESA_CARGO').attr('disabled', false);
        $('#RESPONSAVEL_NAO_EMPRESA_EMAIL').attr('disabled', false);
        $('#RESPONSAVEL_NAO_EMPRESA_FAX').attr('disabled', false);
        $('#RESPONSAVEL_NAO_EMPRESA_FONE').attr('disabled', false);
        $('#RESPONSAVEL_NAO_EMPRESA_EMAIL_CONFIRMA').attr('disabled', false);
        // Botão de Salvar
        $('#btnSalvar').show();
    }

</script>
