<div class="container-fluid-full">
    <div class="row-fluid">

        <!-- start: Main Menu -->
        <div id="sidebar-left" class="span2">

            <div class="row-fluid actions">

                <input type="text" class="search span12" placeholder="O que deseja buscar?" />

            </div>	
            <?php include_once 'menu.phtml'; ?>
        </div>
        <!-- end: Main Menu -->

        <!-- start: Content -->
        <div id="content" class="span10">

            <div class="row-fluid"><!--/span-->

            </div>

            <div class="row-fluid"></div>	

            <div class="row-fluid">

                <div class="box span12">

                    <?php include_once 'mensagem.phtml'; ?>

                    <div class="box-header">
                        <h2><i class="icon-edit"></i>Gerenciar Empresas Benefici&aacute;rias</h2>
                        <div class="box-icon">

                        </div>
                    </div>
                    <div class="box-content">
                        <fieldset>
                            <div id="conteudo">

                                <table class="table table-striped table-bordered bootstrap-datatable ">
                                    <tr>
                                        <th colspan="2">Dados da Empresa Benefici&aacute;ria</th>
                                    </tr>
                                    <tr>
                                        <td class="destacar bold">CNPJ:</td>
                                        <td class="destacar bold">Raz&atilde;o Social:</td>
                                    </tr>
                                    <tr>
                                        <td><?php echo $this->mascara($this->beneficiaria['nrCnpj'], 'cnpj'); ?></td>
                                        <td><?php echo $this->beneficiaria['nmRazaoSocial']; ?></td>
                                    </tr>
                                    <tr>
                                        <td class="destacar bold">Nome Fantasia:</td>
                                        <td class="destacar bold" colspan="2">Regime de tributação:</td>
                                    </tr>
                                    <tr>
                                        <td><?php echo $this->beneficiaria['nmFantasia']; ?></td>
                                        <td><?php echo $this->beneficiaria['dsTipoLucro']; ?></td>
                                    </tr>
                                    <tr>
                                        <td class="destacar bold">Natureza Juridica:</td>
                                        <td class="destacar bold">CNAE Principal:</td>
                                    </tr>
                                    <tr>
                                        <td><?php echo $this->beneficiaria['dsNaturezaJuridica']; ?></td>
                                        <td>
                                            <?php foreach ($this->beneficiaria['nmCnaePrincipal'] as $CNAE): ?>
                                            <?php echo $CNAE['ID_CNAE'] ?> - <?php echo $CNAE['dsCNAE'] ?><br />     
                                            <?php endforeach; ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="destacar bold" colspan="3">CNAEs Secundários:</td>
                                    <tr>
                                        <td colspan="2">
                                            <?php foreach ($this->beneficiaria['cnaeSecundarios'] as $CNAE): ?>
                                            <?php echo $CNAE['ID_CNAE'] ?> - <?php echo $CNAE['dsCNAE'] ?><br />     
                                            <?php endforeach; ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="destacar bold">CEP:</td>
                                        <td class="destacar bold" colspan="2">Endere&ccedil;o:</td>
                                    </tr>
                                    <tr>
                                        <td><?php echo $this->mascara($this->beneficiaria['cep'], 'cep'); ?></td>
                                        <td><?php echo $this->beneficiaria['logradouro']; ?></td>

                                    </tr>
                                    <tr>
                                        <td class="destacar bold">Bairro:</td>
                                        <td class="destacar bold">Munic&iacute;pio:</td>
                                    </tr>
                                    <tr>
                                        <td><?php echo $this->beneficiaria['nmBairro']; ?></td>
                                        <td><?php echo $this->beneficiaria['Municipio']; ?></td>
                                    </tr>
                                    <tr>
                                        <td class="destacar bold">Complemento:</td>
                                        <td class="destacar bold">Número:</td>
                                    </tr>
                                    <tr>
                                        <td><?php echo $this->beneficiaria['dsComplementoEndereco']; ?></td>
                                        <td><?php echo $this->beneficiaria['nrComplemento']; ?></td>
                                    </tr>
                                    <tr>
                                        <td class="destacar bold">Estado:</td>
                                        <td class="destacar bold">Pa&iacute;s:</td>
                                    </tr>
                                    <tr>
                                        <td><?php echo $this->beneficiaria['Estado']; ?></td>
                                        <td><?php echo $this->beneficiaria['Pais']; ?></td>
                                    </tr>
                                    <tr>
                                        <td class="destacar bold">Situa&ccedil;&atilde;o Cadastral:</td>
                                        <td class="destacar bold">Data Atualiza&ccedil;&atilde;o Situa&ccedil;&atilde;o Cadastral:</td>
                                    </tr>
                                    <tr>
                                        <td><?php echo $this->beneficiaria['descricaoSituacaoCadastral']; ?></td>
                                        <td><?php echo $this->beneficiaria['dataSituacaoCadastral']; ?></td>
                                    </tr>
                                </table>

                                <table class="table table-striped table-bordered bootstrap-datatable ">
                                    <div class="box-header">
                                        <h2><i class="icon-edit"></i>Faixa Salárial</h2>
                                        <div class="box-icon"></div>
                                    </div>
                                    <tr>
                                        <td class="destacar bold"><strong>Faixa salárial</strong></td>
                                        <td class="destacar bold"><strong>Quantidade de funcionários</strong></td>
                                    </tr>
                                    <?php $total = 0 ?>
                                    <?php foreach ($this->beneficiaria['faixaSalarial'] as $value): ?>

                                        <tr>
                                            <td>
                                                <?php echo $value->dsTipoFaixaSalarial ?> 
                                            </td>
                                            <td>
                                                <?php echo $value->qtTrabalhadorFaixaSalarial ?>   
                                            </td>
                                        </tr>
                                        <?php $total += $value->qtTrabalhadorFaixaSalarial ?>
                                    <?php endforeach; ?>
                                    <td>
                                        Total
                                    </td>
                                    <td>
                                        <?php echo $total ?>   
                                    </td>
                                    </tr>
                                </table>

                                <table class="table table-striped table-bordered bootstrap-datatable ">
                                    <div class="box-header">
                                        <h2><i class="icon-edit"></i>Respons&aacute;vel pela Empresa</h2>
                                        <div class="box-icon"></div>
                                    </div>
                                    <?php foreach($this->beneficiaria['responsaveis'] as $resp):?>
                                    <tr>
                                        <th class="destacar bold">CPF:</th>
                                        <th class="destacar bold">Nome:</th>
                                        <th class="destacar bold">Cargo:</th>
                                    </tr>
                                    <tr>
                                        <td><?php echo $this->mascara($resp['nrCpfResponsavel'], 'cpf'); ?></td>
                                        <td><?php echo $resp['nmResponsavel']; ?></td>
                                        <td><?php echo $resp['cargoResponsavel']; ?></td>
                                    </tr>
                                    <tr>
                                        <th class="destacar bold">E-mail:</th>
                                        <th class="destacar bold">Telefones:</th>
                                        <th class="destacar bold">Fax:</th>
                                    </tr>
                                    <tr>
                                        <td>
                                            <?php foreach($resp['emailsResponsavel'] as $em):?>
                                            <div class="descricao"><?php echo $em['emailResponsavel']; ?></div>
                                            <?php endforeach; ?>
                                        </td>
                                        <td>
                                            <?php foreach($resp['telefonesResponsavel'] as $tel):?>
                                            <?php if($tel['tipoTel'] == 2):?>
                                            <div class="descricao"><?php echo $tel['TelResponsavel']; ?></div>
                                            <?php endif;?>
                                            <?php endforeach; ?>
                                        </td>
                                        <td>
                                            <?php foreach($resp['telefonesResponsavel'] as $tel):?>
                                            <?php if($tel['tipoTel'] == 4):?>
                                            <div class="descricao"><?php echo $tel['TelResponsavel']; ?></div>
                                            <?php endif;?>
                                            <?php endforeach; ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="3" style="background: #ccc;"></td>
                                    </tr>
                                    <?php endforeach; ?>
                                </table>

                                <table class="table table-striped table-bordered bootstrap-datatable ">
                                    <div class="box-header">
                                        <h2><i class="icon-edit"></i>Operadora</h2>
                                        <div class="box-icon"></div>
                                    </div>
                                    <tr>
                                        <td class="destacar bold"><strong>Nome</strong></td>
                                        <td class="destacar bold"><strong>Status</strong></td>
                                    </tr>
                                    <tr>
                                        <td class="">
                                            <?php
                                            if (ctype_space($this->beneficiaria['nmFantasiaOperadora']) || $this->beneficiaria[''] == '' || $this->beneficiaria['nmFantasiaOperadora'] === NULL || empty($this->beneficiaria['nmFantasiaOperadora']) ) {
                                                $nomeOperadora = $this->beneficiaria['nmRazaoSocialOperadora'];
                                            } else {
                                                $nomeOperadora = $this->beneficiaria['nmFantasiaOperadora'];
                                            }
                                            echo $nomeOperadora; ?></td>
                                        <td class=""><?php echo isset($this->beneficiaria['dsTipoSituacaoOperadora']) ? $this->beneficiaria['dsTipoSituacaoOperadora'] : ''; ?></td>
                                    </tr>
                                </table>

                                <table class="table table-striped table-bordered bootstrap-datatable ">
                                    <div class="box-header">
                                        <h2><i class="icon-edit"></i>Hist&oacute;rico de Ativa&ccedil;&atilde;o / Inativa&ccedil;&atilde;o</h2>
                                        <div class="box-icon"></div>
                                    </div>
                                    <tr>
                                        <td class="destacar bold"><strong>Status</strong></td>
                                        <td class="destacar bold"><strong>Data da atualiza&ccedil;&atilde;o</strong></td>
                                        <td class="destacar bold"><strong>Justificativa</strong></td>
                                    </tr>
                                    <?php foreach ($this->historico as $h): ?>
                                        <tr>
                                            <td class=""><?php echo $h['dsTipoSituacao']; ?></td>
                                            <td class=""><?php echo $h['dtSituacao']; ?></td>
                                            <td class=""><?php echo $h['dsJustificativa']; ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                </table>

                                <div class="form-actions">
                                    <?php if ($this->beneficiaria['idTipoSituacao'] == 1 OR $this->beneficiaria['idTipoSituacao'] == ''): ?>
                                        <button class="btn btn-primary aprovar">Aprovar</button>
                                        <button class="btn btn-danger reprovar">Reprovar</button>
                                        <button id="atualizar-dados-rf-confirm" class="btn btn-info">Atualizar Dados RF</button>
                                        <a href="<?php echo $this->url(array('module' => 'minc', 'controller' => 'admin', 'action' => 'lista-beneficiarios'), null, true); ?>" class="btn" >Voltar</a>
                                    <?php elseif ($this->beneficiaria['idTipoSituacao'] == 2): ?>
                                        <button class="btn btn-danger inativar">Inativar</button>
                                        <button id="atualizar-dados-rf-confirm" class="btn btn-info">Atualizar Dados RF</button>
                                        <a href="<?php echo $this->url(array('module' => 'minc', 'controller' => 'admin', 'action' => 'lista-beneficiarios'), null, true); ?>" class="btn" >Voltar</a>
                                    <?php elseif ($this->beneficiaria['idTipoSituacao'] == 3): ?>
                                        <button class="btn btn-danger aprovar">Aprovar</button>
                                        <button id="atualizar-dados-rf-confirm" class="btn btn-info">Atualizar Dados RF</button>
                                        <a href="<?php echo $this->url(array('module' => 'minc', 'controller' => 'admin', 'action' => 'lista-beneficiarios'), null, true); ?>" class="btn" >Voltar</a>
                                    <?php elseif ($this->beneficiaria['idTipoSituacao'] == 4): ?>
                                        <button class="btn btn-primary ativar">Ativar</button>
                                        <button id="atualizar-dados-rf-confirm" class="btn btn-info">Atualizar Dados RF</button>
                                        <a href="<?php echo $this->url(array('module' => 'minc', 'controller' => 'admin', 'action' => 'lista-beneficiarios'), null, true); ?>" class="btn" >Voltar</a>
                                    <?php endif; ?>
                                </div>

                                <br clear="all" />
                            </div>
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
        <!-- end: Content -->

    </div><!--/fluid-row-->

    <div id="dialog-confirm" title="Confirmação" style="display: none;">
        <form id="formOperacao" method="POST" action="<?php echo $this->url(array('module' => 'minc', 'controller' => 'admin', 'action' => 'mudar-situacao', 'id' => $this->idbeneficiaria, 'idOperadora' => $this->beneficiaria['idOperadora']), null, true); ?>">
            <input type="hidden" name="situacao" id="situacao" />
            <input type="hidden" name="opcao" id="opcao" value="beneficiaria" />
            <label id="lbJus">Justificativa</label>
            <textarea name="dsJustificativa" id="dsJustificativa" style="resize: none; width: 97%; height: 100px; border: 1px solid #ccc;"></textarea>
        </form>
    </div>

    <div id="dialog-atualizar-dados-rf-confirm" title="Confirmação" style="display: none;">
        Esta ação irá atualizar os dados da Beneficiária com os dados oriundos da Receita Federal, e irá gerar custos ao Ministério da Cultura.
        Deseja realmente efetuar esta ação?
        <form id="form-atualizar-dados-rf" action="<?php
            echo $this->url(
                    array(
                        'module' => 'minc',
                        'controller' => 'admin',
                        'action' => 'atualizar-dados-receita-federal',
                        'beneficiaria' => $this->idbeneficiaria,
                        'cnpj' => $this->beneficiaria['nrCnpj'],
                    ),
                    null,
                    true);
            ?>"></form>
    </div>

    <!-- mascara para cobrir o site -->	
    <div id="mascara"></div>

    <div class="clearfix"></div>
    <br>

</div>

<script type="text/javascript">

    $(document).ready(function() {

        $(".aprovar").click(function() {

            $("#dialog-confirm").attr("title", "Deseja realmente aprovar a beneficiaria?");
            $("#situacao").val(2);

            $('#dsJustificativa').val('Inscrição aprovada em conformidade com as normas vigentes.');
            $('#dsJustificativa').attr('readonly', 'readonly');
            
            $("#dialog-confirm").dialog({
                resizable: false,
                width: 520,
                height: 280,
                modal: true,
                open: function(event, ui) {
                    $(".ui-dialog-titlebar-close").hide(); // Hide the [x] button
                },
                buttons: {
                    "Aprovar": function() {
                        var jus = document.getElementById('dsJustificativa').value;
                        if (jus.length <= 0) {
                            $('#lbJus').html('A Justificativa é obrigatório!');
                            $('#lbJus').css('color', 'red');
                            return false;
                        }
                        $("#formOperacao").submit();
                    },
                    "Cancelar": function() {
                        $(this).dialog("close");
                        $('#dsJustificativa').val('');
                    }
                }
            });
        });

        $("#atualizar-dados-rf-confirm").click(function() {
            $("#dialog-atualizar-dados-rf-confirm").dialog({
                resizable: false,
                width: 520,
                height: 200,
                modal: true,
                open: function(event, ui) {
                    $(".ui-dialog-titlebar-close").hide(); // Hide the [x] button
                },
                buttons: {
                    "Sim": function() {
                        $("#form-atualizar-dados-rf").submit();
                    },
                    "Não": function() {
                        $(this).dialog("close");
                    }
                }
            });
        });

        $(".reprovar").click(function() {

            $("#dialog-confirm").attr("title", "Deseja realmente reprovar a beneficiaria?");
            $("#situacao").val(3);
            $("#dialog-confirm").dialog({
                resizable: false,
                width: 500,
                height: 280,
                modal: true,
                open: function(event, ui) {
                    $(".ui-dialog-titlebar-close").hide(); // Hide the [x] button
                },
                buttons: {
                    "Reprovar": function() {
                        var jus = document.getElementById('dsJustificativa').value;
                        if (jus.length <= 0) {
                            $('#lbJus').html('A Justificativa é obrigatório!');
                            $('#lbJus').css('color', 'red');
                            return false;
                        }
                        $("#formOperacao").submit();
                    },
                    "Cancelar": function() {
                        $(this).dialog("close");
                        $('#dsJustificativa').val('');
                    }
                }
            });
        });


        $(".inativar").click(function() {

            $("#dialog-confirm").attr("title", "Deseja realmente inativar a beneficiaria?");
            $("#situacao").val(4);
            $("#dialog-confirm").dialog({
                resizable: false,
                width: 500,
                height: 280,
                modal: false,
                open: function(event, ui) {
                    $(".ui-dialog-titlebar-close").hide(); // Hide the [x] button
                },
                buttons: {
                    "Inativar": function() {
                        var jus = document.getElementById('dsJustificativa').value;
                        if (jus.length <= 0) {
                            $('#lbJus').html('A Justificativa é obrigatório!');
                            $('#lbJus').css('color', 'red');
                            return false;
                        }
                        $("#formOperacao").submit();
                    },
                    "Cancelar": function() {
                        $(this).dialog("close");
                        $('#dsJustificativa').val('');
                    }
                }
            });
        });


        $(".ativar").click(function() {

            $("#dialog-confirm").attr("title", "Deseja realmente ativar a beneficiaria?");
            $("#situacao").val(2);

            $("#dialog-confirm").dialog({
                resizable: false,
                width: 500,
                height: 280,
                modal: true,
                open: function(event, ui) {
                    $(".ui-dialog-titlebar-close").hide(); // Hide the [x] button
                },
                buttons: {
                    "Ativar": function() {
                        var jus = document.getElementById('dsJustificativa').value;
                        if (jus.length <= 0) {
                            $('#lbJus').html('A Justificativa é obrigatório!');
                            $('#lbJus').css('color', 'red');
                            return false;
                        }
                        $("#formOperacao").submit();
                    },
                    "Cancelar": function() {
                        $(this).dialog("close");
                        $('#dsJustificativa').val('');
                    }
                }
            });
        });
    });

</script>