<style>
    .descricao {
        min-height: 30px;
        line-height: 30px;
        border-bottom: solid 1px #f3f3f3;
    }
</style>
<div class="container-fluid-full">
    <div class="row-fluid">

        <!-- start: Main Menu -->
        <div id="sidebar-left" class="span2">

            <div class="row-fluid actions">

                <input type="text" class="search span12" placeholder="O que deseja buscar?"/>

            </div>
            <?php include_once 'menu.phtml'; ?>
        </div>
        <!-- end: Main Menu -->

        <!-- start: Content -->
        <div id="content" class="span10">

            <div class="row-fluid"><!--/span-->

            </div>

            <div class="row-fluid"></div>

            <div class="row-fluid">

                <div class="box span12">

                    <?php include_once 'mensagem.phtml'; ?>

                    <div class="box-header">
                        <h2><i class="icon-edit"></i>Gerenciar Empresas Operadoras</h2>
                        <div class="box-icon">

                        </div>
                    </div>
                    <div class="box-content">
                        <fieldset>
                            <div id="conteudo">

                                <table class="table table-striped table-bordered bootstrap-datatable ">
                                    <tr>
                                        <th colspan="3">Dados da Empresa Operadora</th>
                                    </tr>
                                    <tr>
                                        <td class="destacar bold">CNPJ:</td>
                                        <td class="destacar bold" colspan="2">Raz&atilde;o Social:</td>
                                    </tr>
                                    <tr>
                                        <td><?php echo $this->mascara($this->operadora['nrCnpj'], 'cnpj'); ?></td>
                                        <td colspan="2"><?php echo $this->operadora['nmRazaoSocial']; ?></td>
                                    </tr>
                                    <tr>
                                        <td colspan="3" class="destacar bold">E-mail institucional:</td>
                                    </tr>
                                    <tr>
                                        <td colspan="3" class="destacar bold">
                                            <?php echo empty($this->emailInstitucional) ? '&nbsp;' : $this->emailInstitucional['DS_EMAIL']; ?>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="destacar bold">Nome Fantasia:</td>
                                        <td class="destacar bold" colspan="2">Endere&ccedil;o:</td>
                                    </tr>
                                    <tr>
                                        <td><?php echo $this->operadora['nmFantasia']; ?></td>
                                        <td colspan="2"><?php echo $this->operadora['logradouro']; ?></td>
                                    </tr>
                                    <tr>
                                        <td class="destacar bold">Complemento:</td>
                                        <td class="destacar bold" colspan="2">Número:</td>
                                    </tr>
                                    <tr>
                                        <td><?php echo $this->operadora['dsComplementoEndereco']; ?></td>
                                        <td colspan="2"><?php echo $this->operadora['nrComplemento']; ?></td>
                                    </tr>
                                    <tr>
                                        <td class="destacar bold">Bairro:</td>
                                        <td class="destacar bold" colspan="2">CEP:</td>
                                    </tr>
                                    <tr>
                                        <td><?php echo $this->operadora['nmBairro']; ?></td>
                                        <td colspan="2"><?php echo $this->mascara($this->operadora['cep'], 'cep'); ?></td>
                                    </tr>
                                    <tr>
                                        <td class="destacar bold">Pa&iacute;s:</td>
                                        <td class="destacar bold">Estado:</td>
                                        <td class="destacar bold">Munic&iacute;pio:</td>
                                    </tr>
                                    <tr>
                                        <td><?php echo $this->operadora['Pais']; ?></td>
                                        <td><?php echo $this->operadora['Estado']; ?></td>
                                        <td><?php echo $this->operadora['Municipio']; ?></td>
                                    </tr>
                                </table>

                                <table class="table table-striped table-bordered bootstrap-datatable ">
                                    <div class="box-header">
                                        <h2><i class="icon-edit"></i>Respons&aacute;vel pela Empresa</h2>
                                        <div class="box-icon"></div>
                                    </div>
                                    <?php foreach ($this->operadora['responsaveis'] as $resp): ?>
                                        <tr>
                                            <th class="destacar bold">CPF:</th>
                                            <th class="destacar bold">Nome:</th>
                                            <th class="destacar bold">Cargo:</th>
                                        </tr>
                                        <tr>
                                            <td><?php echo $this->mascara($resp['nrCpfResponsavel'], 'cpf'); ?></td>
                                            <td><?php echo $resp['nmResponsavel']; ?></td>
                                            <td><?php echo $resp['cargoResponsavel']; ?></td>
                                        </tr>
                                        <tr>
                                            <th class="destacar bold">E-mail:</th>
                                            <th class="destacar bold">Telefones:</th>
                                            <th class="destacar bold">Fax:</th>
                                        </tr>
                                        <tr>
                                            <td>
                                                <?php foreach ($resp['emailsResponsavel'] as $em): ?>
                                                    <div class="descricao"><?php echo $em['emailResponsavel']; ?></div>
                                                <?php endforeach; ?>
                                            </td>
                                            <td>
                                                <?php foreach ($resp['telefonesResponsavel'] as $tel): ?>
                                                    <?php if ($tel['tipoTel'] == 2): ?>
                                                        <div class="descricao"><?php echo $tel['TelResponsavel']; ?></div>
                                                    <?php endif; ?>
                                                <?php endforeach; ?>
                                            </td>
                                            <td>
                                                <?php foreach ($resp['telefonesResponsavel'] as $tel): ?>
                                                    <?php if ($tel['tipoTel'] == 4): ?>
                                                        <div class="descricao"><?php echo $tel['TelResponsavel']; ?></div>
                                                    <?php endif; ?>
                                                <?php endforeach; ?>
                                            </td>
                                        </tr>
                                        <tr>
                                            <th colspan="3" class="destacar bold">Situação</th>
                                        </tr>
                                        <tr>
                                            <td colspan="3"><?php echo $resp['stAtivo'] == 'A' ? 'Ativo' : 'Inativo' ?></td>
                                        </tr>
                                        <tr>
                                            <td colspan="3" style="background: #ccc;"></td>
                                        </tr>
                                    <?php endforeach; ?>
                                </table>

                                <?php if (count($this->operadora['nao-responsaveis']) > 0) : ?>
                                    <table class="table table-striped table-bordered bootstrap-datatable ">
                                        <div class="box-header">
                                            <h2><i class="icon-edit"></i>Não Respons&aacute;vel pela Empresa</h2>
                                            <div class="box-icon"></div>
                                        </div>
                                        <?php foreach ($this->operadora['nao-responsaveis'] as $resp): ?>
                                            <tr>
                                                <th class="destacar bold">CPF:</th>
                                                <th class="destacar bold">Nome:</th>
                                                <th class="destacar bold">Cargo:</th>
                                            </tr>
                                            <tr>
                                                <td><?php echo $this->mascara($resp['nrCpfResponsavel'], 'cpf'); ?></td>
                                                <td><?php echo $resp['nmResponsavel']; ?></td>
                                                <td><?php echo $resp['cargoResponsavel']; ?></td>
                                            </tr>
                                            <tr>
                                                <th class="destacar bold">E-mail:</th>
                                                <th class="destacar bold">Telefones:</th>
                                                <th class="destacar bold">Fax:</th>
                                            </tr>
                                            <tr>
                                                <td>
                                                    <?php foreach ($resp['emailsResponsavel'] as $em): ?>
                                                        <div class="descricao"><?php echo $em['emailResponsavel']; ?></div>
                                                    <?php endforeach; ?>
                                                </td>
                                                <td>
                                                    <?php foreach ($resp['telefonesResponsavel'] as $tel): ?>
                                                        <?php if ($tel['tipoTel'] == 2): ?>
                                                            <div class="descricao"><?php echo $tel['TelResponsavel']; ?></div>
                                                        <?php endif; ?>
                                                    <?php endforeach; ?>
                                                </td>
                                                <td>
                                                    <?php foreach ($resp['telefonesResponsavel'] as $tel): ?>
                                                        <?php if ($tel['tipoTel'] == 4): ?>
                                                            <div class="descricao"><?php echo $tel['TelResponsavel']; ?></div>
                                                        <?php endif; ?>
                                                    <?php endforeach; ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td colspan="3" style="background: #ccc;"></td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </table>
                                <?php endif; ?>

                                <table width="100%" class="table table-striped table-bordered bootstrap-datatable ">
                                    <div class="box-header">
                                        <h2><i class="icon-edit"></i>Arquivos Anexados</h2>
                                        <div class="box-icon">

                                        </div>
                                    </div>
                                    <br>
                                    <?php if (count($this->arquivosOperadora) > 0): ?>
                                        <?php foreach ($this->arquivosOperadora as $arq): ?>
                                            <tr>
                                                <td class=""><?php echo $arq['dsArquivo']; ?></td>
                                                <td class="destacar" style="width: 20%; text-align: center;"><strong><a
                                                                target="_blank"
                                                                href="<?php echo $this->url(array('module' => 'minc', 'controller' => 'admin', 'action' => 'abrir-arquivo', 'arquivo' => $arq['dsCaminhoArquivo'])); ?>">baixar
                                                            o arquivo</a></strong></td>
                                            </tr>
                                        <?php endforeach; ?>
                                    <?php else: ?>
                                        <tr>
                                            <td class="destacar bold"><strong>Nenhum arquivo cadastrado!</strong></td>
                                        </tr>
                                    <?php endif; ?>
                                </table>

                                <table class="table table-striped table-bordered bootstrap-datatable ">
                                    <div class="box-header">
                                        <h2><i class="icon-edit"></i>Hist&oacute;rico de Ativa&ccedil;&atilde;o /
                                            Inativa&ccedil;&atilde;o</h2>
                                        <div class="box-icon"></div>
                                    </div>
                                    <tr>
                                        <td class="destacar bold"><strong>Status</strong></td>
                                        <td class="destacar bold"><strong>Data da atualiza&ccedil;&atilde;o</strong>
                                        </td>
                                        <td class="destacar bold"><strong>Justificativa</strong></td>
                                    </tr>
                                    <?php foreach ($this->historico as $h): ?>
                                        <tr>
                                            <td class=""><?php echo $h['dsTipoSituacao']; ?></td>
                                            <td class=""><?php echo $h['dtSituacao']; ?></td>
                                            <td class=""><?php echo $h['dsJustificativa']; ?></td>
                                        </tr>
                                    <?php endforeach; ?>
                                </table>

                                <div class="form-actions">
                                    <?php if ($this->operadora['idTipoSituacao'] == 1 OR $this->operadora['idTipoSituacao'] == ''): ?>
                                        <button class="btn btn-primary aprovar">Aprovar</button>
                                        <button class="btn btn-danger reprovar">Reprovar</button>
                                        <a href="<?php echo $this->url(array('module' => 'minc', 'controller' => 'admin', 'action' => 'lista-operadora'), null, true); ?>"
                                           class="btn">Voltar</a>
                                    <?php elseif ($this->operadora['idTipoSituacao'] == 2): ?>
                                        <button class="btn btn-danger inativar">Inativar</button>
                                        <a href="<?php echo $this->url(array('module' => 'minc', 'controller' => 'admin', 'action' => 'lista-operadora'), null, true); ?>"
                                           class="btn">Voltar</a>
                                    <?php elseif ($this->operadora['idTipoSituacao'] == 3): ?>
                                        <button class="btn btn-danger aprovar">Aprovar</button>
                                        <a href="<?php echo $this->url(array('module' => 'minc', 'controller' => 'admin', 'action' => 'lista-operadora'), null, true); ?>"
                                           class="btn">Voltar</a>
                                    <?php elseif ($this->operadora['idTipoSituacao'] == 4): ?>
                                        <button class="btn btn-primary ativar">Ativar</button>
                                        <a href="<?php echo $this->url(array('module' => 'minc', 'controller' => 'admin', 'action' => 'lista-operadora'), null, true); ?>"
                                           class="btn">Voltar</a>
                                    <?php endif; ?>
                                </div>

                                <br clear="all"/>
                            </div>
                        </fieldset>
                    </div>
                </div>
            </div>
        </div>
        <!-- end: Content -->

    </div><!--/fluid-row-->

    <div id="dialog-confirm" title="Confirmação" style="display: none;">
        <form id="formOperacao" method="POST"
              action="<?php echo $this->url(array('module' => 'minc', 'controller' => 'admin', 'action' => 'mudar-situacao', 'id' => $this->idOperadora), null, true); ?>">
            <input type="hidden" name="situacao" id="situacao"/>
            <input type="hidden" name="opcao" id="opcao" value="operadora"/>
            <label id="lbJus">Justificativa</label>
            <textarea name="dsJustificativa" id="dsJustificativa"
                      style="resize: none; width: 97%; height: 100px; border: 1px solid #ccc;"></textarea>
        </form>
    </div>

    <!-- mascara para cobrir o site -->
    <div id="mascara"></div>

    <div class="clearfix"></div>
    <br>

</div>

<script type="text/javascript">

    $(document).ready(function () {

        $(".aprovar").click(function () {

            $("#dialog-confirm").attr("title", "Deseja realmente aprovar a operadora?");
            $(".ui-dialog-titlebar-close").hide();
            $("#situacao").val(2);

            $('#dsJustificativa').val('Inscrição aprovada em conformidade com as normas vigentes.');
            $('#dsJustificativa').attr('readonly', 'readonly');

            $("#dialog-confirm").dialog({
                resizable: false,
                width: 520,
                height: 280,
                modal: true,
                open: function (event, ui) {
                    $(".ui-dialog-titlebar-close").hide(); // Hide the [x] button
                },
                buttons: {
                    "Aprovar": function () {
                        var jus = document.getElementById('dsJustificativa').value;
                        if (jus.length <= 0) {
                            $('#lbJus').html('A Justificativa é obrigatório!');
                            $('#lbJus').css('color', 'red');
                            return false;
                        }
                        $("#formOperacao").submit();
                    },
                    "Cancelar": function () {
                        $(this).dialog("close");
                        $('#dsJustificativa').val('');
                    }
                }
            });
        });

        $(".reprovar").click(function () {

            $("#dialog-confirm").attr("title", "Deseja realmente reprovar a operadora?");
            $(".ui-dialog-titlebar-close").hide();
            $("#situacao").val(3);

            $("#dialog-confirm").dialog({
                resizable: false,
                width: 500,
                height: 280,
                modal: true,
                open: function (event, ui) {
                    $(".ui-dialog-titlebar-close").hide(); // Hide the [x] button
                },
                buttons: {
                    "Reprovar": function () {
                        var jus = document.getElementById('dsJustificativa').value;
                        if (jus.length <= 0) {
                            $('#lbJus').html('A Justificativa é obrigatório!');
                            $('#lbJus').css('color', 'red');
                            return false;
                        }
                        $("#formOperacao").submit();
                    },
                    "Cancelar": function () {
                        $(this).dialog("close");
                        $('#dsJustificativa').val('');
                    }
                }
            });
        });


        $(".inativar").click(function () {

            $("#dialog-confirm").attr("title", "Deseja realmente inativar a operadora?");
            $(".ui-dialog-titlebar-close").hide();
            $("#situacao").val(4);

            $("#dialog-confirm").dialog({
                resizable: false,
                width: 500,
                height: 280,
                modal: true,
                open: function (event, ui) {
                    $(".ui-dialog-titlebar-close").hide(); // Hide the [x] button
                },
                buttons: {
                    "Inativar": function () {
                        var jus = document.getElementById('dsJustificativa').value;
                        if (jus.length <= 0) {
                            $('#lbJus').html('A Justificativa é obrigatório!');
                            $('#lbJus').css('color', 'red');
                            return false;
                        }
                        $("#formOperacao").submit();
                    },
                    "Cancelar": function () {
                        $(this).dialog("close");
                        $('#dsJustificativa').val('');
                    }
                }
            });
        });


        $(".ativar").click(function () {

            $("#dialog-confirm").attr("title", "Deseja realmente ativar a operadora?");
            $(".ui-dialog-titlebar-close").hide();
            $("#situacao").val(2);

            $("#dialog-confirm").dialog({
                resizable: false,
                width: 500,
                height: 280,
                modal: true,
                open: function (event, ui) {
                    $(".ui-dialog-titlebar-close").hide(); // Hide the [x] button
                },
                buttons: {
                    "Ativar": function () {
                        var jus = document.getElementById('dsJustificativa').value;
                        if (jus.length <= 0) {
                            $('#lbJus').html('A Justificativa é obrigatório!');
                            $('#lbJus').css('color', 'red');
                            return false;
                        }
                        $("#formOperacao").submit();
                    },
                    "Cancelar": function () {
                        $(this).dialog("close");
                        $('#dsJustificativa').val('');
                    }
                }
            });
        });


    });

</script>