<div class="container-fluid-full">
    <div class="row-fluid">

        <!-- start: Main Menu -->
        <div id="sidebar-left" class="span2">

            <div class="row-fluid actions">

                <input type="text" class="search span12" placeholder="O que deseja buscar?" />

            </div>
            <?php include_once 'menu.phtml'; ?>
        </div>
        <!-- end: Main Menu -->

        <!-- start: Content -->
        <div id="content" class="span10">

            <div class="row-fluid">

                <div class="box span12">
                    <div class="box-header">
                        <h2><i class="icon-edit"></i>Gerenciar Benefici&aacute;rias</h2>
                        <div class="box-icon">

                        </div>
                    </div>
                    <div class="box-content">
                        <fieldset>
                            <div id="conteudo">
                                <form method="post" action="listaOperadora.htm">
                                    <table class="table table-striped table-bordered bootstrap-datatable " style="margin-bottom: 50px; margin-top: 20px;">
                                        <?php if (count($this->beneficiarias) <= 0): ?>
                                            <tr>
                                                <td class="destacar bold centro" colspan="4"><strong>Nenhuma Benefici&aacute;ria em sua responsabilidade!</strong></td>
                                            </tr>
                                        <?php else: ?>
                                            <tr>
                                                <td class="destacar bold centro"><strong>CNPJ</strong></td>
                                                <td class="destacar bold centro"><strong>Nome</strong></td>
                                                <td class="destacar bold centro" style="text-align: center;"><strong>Data de Cadastro</strong></td>
                                                <td class="destacar bold centro" style="text-align: center;"><strong>Status</strong></td>
                                                <td class="destacar bold centro" style="text-align: center;"><strong>Gerênciar</strong></td>
                                            </tr>
                                            <?php foreach ($this->beneficiarias as $b): ?>
                                                <tr>
                                                    <td class="centro" width="150px"><?php echo $this->mascara($b->nrCnpj, 'cnpj'); ?></td>
                                                    <td><?php echo ($b->nmFantasia===" ") ? $b->nmRazaoSocial : $b->nmFantasia; ?></td>
                                                    <td class="centro" style="text-align: center;"><?php echo $b->dtInscricao; ?></td>
                                                    <td style="text-align: center; color: <?php echo $this->verificarSituacao($b->situacao, 'cor', 'B'); ?>">
                                                        <?php echo $this->verificarSituacao($b->situacao, 'st', 'B'); ?>
                                                    </td>
                                                    <td class="centro" style="text-align: center;">
                                                        <a class="btn btn-success" title="Gerênciar" href="<?php echo $this->url(array('module' => 'beneficiaria', 'controller' => 'index', 'action' => 'index', 'beneficiaria' => $b->idBeneficiaria, 'operadora' => $b->idOperadora)); ?>">
                                                            <i class="icon-ambulance"></i>
                                                        </a>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                        <?php endif; ?>
                                    </table>
                                </form>
                            </div>
                        </fieldset>
                        </form>

                    </div>
                </div>
            </div>
        </div>
        <!-- end: Content -->

    </div><!--/fluid-row-->

    <div class="clearfix"></div>
    <br>

</div><!--/.fluid-container-->
<script>
    $(document).ready(function() {
        $(".cnpj").mask("99.999.999/9999-99");
        $(".data").mask("99/99/9999");
    });
</script>