<div class="container-fluid-full">
    <div class="row-fluid">

        <!-- start: Main Menu -->
        <div id="sidebar-left" class="span2">

            <div class="row-fluid actions">
                <input type="text" class="search span12" placeholder="O que deseja buscar?" />
            </div>

            <?php include_once 'menu.phtml'; ?>

        </div>
        <!-- end: Main Menu -->

        <!-- start: Content -->
        <div id="content" class="span10">

            <div class="row-fluid">

                <div class="box span12">
                    <div class="box-header">
                        <h2><i class="icon-edit"></i>Gerenciar Operadoras</h2>
                        <div class="box-icon">

                        </div>
                    </div>
                    <div class="box-content">
                        <fieldset>
                            <div id="conteudo">

                                <form method="post" action="listaOperadora.htm">
                                    <table width="100%" class="table table-striped table-bordered bootstrap-datatable " style="margin-bottom: 50px; margin-top: 20px;">
                                        <?php if (count($this->operadoras) <= 0): ?>
                                            <tr>
                                                <td class="destacar bold centro" colspan="4"><strong>Nenhuma Operadora em sua responsabilidade!</strong></td>
                                            </tr>
                                        <?php else: ?>
                                        <tr>
                                            <td class="destacar bold centro"><strong>CNPJ</strong></td>
                                            <td class="destacar bold centro"><strong>Nome</strong></td>
                                            <td class="destacar bold centro" style="text-align: center;"><strong>Data de Cadastro</strong></td>
                                            <td class="destacar bold centro" style="text-align: center;"><strong>Situa&ccedil;&atilde;o</strong></td>
                                            <td class="destacar bold centro" style="text-align: center;"><strong>Gerênciar</strong></td>
                                        </tr>
                                        <?php foreach ($this->operadoras as $op): ?>
                                        <tr>
                                            <td class="centro"><?php echo $this->mascara($op->nrCnpj, 'cnpj'); ?></td>
                                            <td><?php echo ($op->nmFantasia===" ") ? $op->nmRazaoSocial : $op->nmFantasia; ?></td>
                                            <td class="centro" style="text-align: center;"><?php echo $op->dtInscricao; ?></td>
                                            <td style="text-align: center; color: <?php echo $this->verificarSituacao($op->situacao, 'cor', 'O'); ?>">
                                                <?php echo $this->verificarSituacao($op->situacao, 'st', 'O'); ?>
                                            </td>
                                            <td class="centro" style="text-align: center;">
                                                <a class="btn btn-success" title="Gerênciar" href="<?php echo $this->url(array('module' => 'operadora', 'controller' => 'index', 'action' => 'index', 'operadora' => $op->idOperadora)); ?>">
                                                    <i class="icon-ambulance"></i>
                                                </a>
                                            </td>
                                        </tr>
                                        <?php endforeach; ?>
                                        <?php endif; ?>
                                    </table>
                                </form>
                            </div>
                        </fieldset>
                        </form>

                    </div>
                </div>
            </div>
        </div>
        <!-- end: Content -->

    </div><!--/fluid-row-->

</div><!--/.fluid-container-->