<link href="<?php echo $this->baseUrl('css/style.min.css') ?>" rel="stylesheet"/>
<style>
    body {
        background-color: #383e4b;
        /*background-color: #3e4b38;*/
        color: #f5f5f5;
    }

    a {
        color: #f5f5f5;
    }

    h1 {
        font-weight: bold;
    }

    h2 {
        font-size: 1.5em;
        line-height: 16px;
        font-weight: bold;
    }
</style>
<div style="margin: 30px;">
    <h1>Rest API - Vale Cultura</h1>
    <p><b>Server path:</b> /api</p>
    <h2>Território</h2>
    <ul>
        <li><a href="/api/trabalhadores/acumulados">GET /trabalhadores/acumulados</a></a></li>
        <li><a href="/api/trabalhadores/acumulados?ano=2016">GET /trabalhadores/acumulados?ano=2016</a></li>
        <li><a href="/api/trabalhadores/acumulados?ano=2016&mes=9">GET /trabalhadores/acumulados?ano=2016&mes=9</a></li>
        <li><a href="/api/trabalhadores/acumulados?regiao=sul">GET /trabalhadores/acumulados?regiao=sul</a></li>
        <li><a href="/api/trabalhadores/acumulados?uf=rs">GET /trabalhadores/acumulados?uf=rs</a></li>
        <li><a href="/api/trabalhadores/ativos">GET /trabalhadores/ativos</a> *</li>
        <li><a href="/api/trabalhadores/ativos?ano=2016&mes=12">GET /trabalhadores/ativos?ano=2016&mes=12</a></li>
    </ul>
    <h2>Beneficiárias</h2>
    <ul>
        <li><a href="/api/beneficiarias/inscritas">GET /beneficiarias/inscritas</a></li>
        <li><a href="/api/beneficiarias/inscritas?ano=2015&mes=12">GET /beneficiarias/inscritas?ano=2015&mes=12</a></li>
        <li><a href="/api/beneficiarias/inscritas?regiao=sul">GET /beneficiarias/inscritas?regiao=sul</a></li>
        <li><a href="/api/beneficiarias/autorizadas">GET /beneficiarias/autorizadas</a></li>
        <li><a href="/api/beneficiarias/autorizadas?ano=2015">GET /beneficiarias/autorizadas?ano=2015</a></li>
        <li><a href="/api/beneficiarias/autorizadas?regiao=sul">GET /beneficiarias/autorizadas?regiao=sul</a></li>
        <li><a href="/api/beneficiarias/nao-autorizadas">GET /beneficiarias/nao-autorizadas</a></li>
        <li><a href="/api/beneficiarias/nao-autorizadas?ano=2015">GET /beneficiarias/nao-autorizadas?ano=2015</a></li>
        <li><a href="/api/beneficiarias/nao-autorizadas?regiao=sul">GET /beneficiarias/nao-autorizadas?regiao=sul</a>
        </li>
        <li><a href="/api/beneficiarias/emitiram-cartao">GET /beneficiarias/emitiram-cartao</a></li>
        <li><a href="/api/beneficiarias/emitiram-cartao?ano=2015">GET /beneficiarias/emitiram-cartao?ano=2015</a></li>
        <li><a href="/api/beneficiarias/emitiram-cartao?regiao=sul">GET /beneficiarias/emitiram-cartao?regiao=sul</a>
        </li>
        <li><a href="/api/beneficiarias/ativos">GET /beneficiarias/ativos?ano=2015</a> *</li>
        <li><a href="/api/beneficiarias/ativos?ano=2015">GET /beneficiarias/ativos?ano=2015</a></li>
    </ul>
    <h2>Consumo</h2>
    <ul>
        <li><a href="/api/consumos">GET /consumos</a></li>
        <li><a href="/api/consumos?regiao=sul">GET /consumos?regiao=sul</a></li>
        <li><a href="/api/consumos?ano=2016&mes=05">GET /consumos?ano=2016&mes=5</a></li>
    </ul>

    <h2>Recebedoras</h2>
    <ul>
        <li><a href="/api/recebedoras">GET /recebedoras</a></li>
        <li><a href="/api/recebedoras?regiao=sul">GET /recebedoras?regiao=sul</a></li>
        <li><a href="/api/recebedoras?ano=2016&mes=05">GET /recebedoras?ano=2016&mes=5</a></li>
    </ul>
    <!--    <p><b>Return type:</b> json</p>-->
</div>