<link href="<?php echo $this->baseUrl('css/style.min.css') ?>" rel="stylesheet" />
<style>
    body {
        background-color: #383e4b;
        /*background-color: #3e4b38;*/
        color: #f5f5f5;
    }
    a {
        color: #f5f5f5;
    }
    h1 {
        font-weight: bold;
    }
    h2 {
        font-size: 1.5em;
        line-height: 16px;
        font-weight: bold;
    }
</style>
<div style="margin: 30px;">
    <h1>Rest API - Vale Cultura</h1>
    <p><b>Server path:</b> /api</p>
    <h2>Território</h2>
    <ul>
        <li><a href="/api/trabalhadores/acumulados">GET /trabalhadores/acumulados</a></a></li>
        <li><a href="/api/trabalhadores/acumulados?ano=2016">GET /trabalhadores/acumulados/ano/2016</a></li>
        <li><a href="/api/trabalhadores/acumulados?ano=2016&mes=9">GET /trabalhadores/acumulados?ano=2016&mes=9</a></li>
        <li><a href="/api/trabalhadores/acumulados?regiao=sul">GET /trabalhadores/acumulados?regiao=sul</a></li>
        <li><a href="/api/trabalhadores/acumulados?uf=rs">GET /trabalhadores/acumulados?uf=rs</a></li>        
        <li><a href="/api/trabalhadores/ativos">GET /trabalhadores/ativos</a></li>
        <li><a href="/api/trabalhadores/ativos?ano=2016&mes=12">GET /trabalhadores/ativos?ano=2016&mes=12</a></li>        
        <li><a href="/api/trabalhadores/inativos">GET /trabalhadores-inativos</a></li>
    </ul>
    <h2>Beneficiárias</h2>
    <ul>
        <li><a href="/api/beneficiarias-acumuladas">GET /beneficiarias-acumuladas</a></li>
        <li><a href="/api/beneficiarias-acumuladas-por-ano">GET /beneficiarias-acumuladas-por-ano</a></li>
        <li><a href="/api/beneficiarias-acumuladas-por-localizacao">GET /beneficiarias-acumuladas-por-localizacao</a></li>
        <li><a href="/api/beneficiarias-inativas">GET /beneficiarias-inativas</a></li>
        <li><a href="/api/consumo-por-periodo">GET /consumo-por-periodo</a></li>
        <li><a href="/api/consumo-por-localizacao">GET /consumo-por-localizacao</a></li>
    </ul>
    <h2>Consumo</h2>
    <ul>
        <li><a href="/api/consumo-por-periodo">GET /consumo-por-periodo</a></li>
        <li><a href="/api/consumo-por-localizacao">GET /consumo-por-localizacao</a></li>
    </ul>
<!--    <p><b>Return type:</b> json</p>-->
</div>